In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
train=pd.read_csv('/users/lisa/Downloads/round1_iflyad_train.txt',sep='\t')
test=pd.read_csv('/users/lisa/Downloads/round1_iflyad_test_feature.txt',sep='\t')

In [5]:
data=pd.concat([train,test],ignore_index=True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [6]:
data.head()

,adid,advert_id,advert_industry_inner,advert_name,app_cate_id,app_id,app_paid,campaign_id,carrier,city,...,make,model,nnt,orderid,os,os_name,osv,province,time,user_tags
0,1560128,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103102105100,...,HUAWEI,HUAWEI-CAZ-AL10,1,3010798,2,android,7.0.0,137103102100100,2190219034,NaN
1,1488859,230000063,102400_102401,B4734117F35EE97F,108.0,2070079.0,False,1000023,3,137105101100100,...,Xiaomi,Redmi Note 4,1,2311397,2,android,6.0,137105101100100,2190221070,"2100191,2100078,3001825,,3001781,3001791,30017..."
2,1537089,230000065,101700_101704,E257895F74792E81,100.0,2089397.0,False,1000021,3,137103104111100,...,OPPO,OPPO+R11s,1,3008491,2,android,7.1.1,137103104100100,2190219793,NaN
3,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137103102113100,...,NaN,OPPO A57,1,3011304,2,android,6.0.1,137103102100100,2190221704,"2100098,gd_2100000,3001791,3001795,3002193,300..."
4,1432367,230000063,102400_102401,B4734117F35EE97F,103.0,1030051.0,False,1000023,1,137103102109100,...,Apple,iPhone 7,3,2304491,1,ios,11.1.1,137103102100100,2190220024,NaN

In [7]:
data

,adid,advert_id,advert_industry_inner,advert_name,app_cate_id,app_id,app_paid,campaign_id,carrier,city,...,make,model,nnt,orderid,os,os_name,osv,province,time,user_tags
0,1560128,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103102105100,...,HUAWEI,HUAWEI-CAZ-AL10,1,3010798,2,android,7.0.0,137103102100100,2190219034,NaN
1,1488859,230000063,102400_102401,B4734117F35EE97F,108.0,2070079.0,False,1000023,3,137105101100100,...,Xiaomi,Redmi Note 4,1,2311397,2,android,6.0,137105101100100,2190221070,"2100191,2100078,3001825,,3001781,3001791,30017..."
2,1537089,230000065,101700_101704,E257895F74792E81,100.0,2089397.0,False,1000021,3,137103104111100,...,OPPO,OPPO+R11s,1,3008491,2,android,7.1.1,137103104100100,2190219793,NaN
3,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137103102113100,...,NaN,OPPO A57,1,3011304,2,android,6.0.1,137103102100100,2190221704,"2100098,gd_2100000,3001791,3001795,3002193,300..."
4,1432367,230000063,102400_102401,B4734117F35EE97F,103.0,1030051.0,False,1000023,1,137103102109100,...,Apple,iPhone 7,3,2304491,1,ios,11.1.1,137103102100100,2190220024,NaN
5,1559158,230000833,4_100206,862FF2E9B0AD4C14,103.0,2071267.0,False,1002835,1,137104104104100,...,"Xiaomi,MI 6,sagit",MI 6,1,3005529,2,android,8.0.0,137104104100100,2190221228,"3002265,3002613,3002993,3003055,3003147,300331..."
6,1580496,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137103101100100,...,Apple,iPhone 7 Plus,1,3012112,1,ios,11.4.1,137103101100100,2190221448,NaN
7,1560128,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137101102100100,...,HUAWEI,HUAWEI-NXT-AL10,1,3010798,2,android,7.0.0,137101102100100,2190221002,"gd_2100000,2100143,ag_2100040,3001837,3002907,..."
8,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137105104114100,...,NaN,OPPO R9s,1,3011304,2,android,6.0.1,137105104100100,2190221002,",3004484,3004430,3004434,3004490,3004468,30045..."
9,1579122,230000063,102400_102401,B4734117F35EE97F,100.0,2089397.0,False,1000023,1,137104101113100,...,vivo,vivo+Y13iL,1,3012120,2,android,4.4.4,137104101100100,2190220484,"2100197,2100150,2100094,2100237,2100132,ag_210..."
10,1579878,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137105102109100,...,vivo,vivo Xplay6,1,3011734,2,android,7.1.1,137105102100100,2190219610,"2100480,2100118,2101058,2100042,2100017,210013..."
11,1580588,230000245,100300_100301,68C5520FFBC5FC19,111.0,2070889.0,False,1003598,3,137104104102100,...,OPPO,OPPO R9s,1,3012310,2,android,6.0.1,137104104100100,2190221545,NaN
12,1548446,230001025,101700_101704,50822F8310CAE01D,108.0,2070463.0,False,1001979,1,137102101107100,...,x600,x600,1,3009834,2,android,6.0,137102101100100,2190220173,"gd_2100001,ag_2100039,3004430,3004434"
13,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137104103112100,...,NaN,vivo X9s,4,3011304,2,android,7.1.2,137104103100100,2190218858,NaN
14,1573112,230000065,101700_101704,E257895F74792E81,103.0,2071103.0,False,1000021,2,137103102105100,...,BBK,vivo Y19t,3,2310543,2,android,6.0,137103102100100,2190221043,NaN
15,1580394,230000245,100300_100301,68C5520FFBC5FC19,103.0,1030051.0,False,1003598,1,137104104102100,...,Xiaomi,MI%206,3,3012288,2,android,7.1.1,137104104100100,2190221640,"gd_2100000,3001771,3001881,3001889,3001899,300..."
16,1580580,230000245,100300_100301,68C5520FFBC5FC19,108.0,1080008.0,False,1003598,1,137104104102100,...,OPPO,OPPO R11s,1,3012306,2,android,7.1.1,137104104100100,2190218712,NaN
17,1574082,230000063,102400_102401,B4734117F35EE97F,107.0,2089303.0,False,1000023,1,137101103109100,...,vivo Y79A,vivo Y79A,1,3011260,2,android,7.1.2,137101103100100,2190219309,NaN
18,1548194,230000063,102400_102401,B4734117F35EE97F,100.0,2089397.0,False,1000023,1,137106101101100,...,OPPO,OPPO+A33,1,3009770,2,android,5.1.1,137106101100100,2190220810,"3003779,3004059,3004214,3004430,3004434"
19,1579858,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137106101101100,...,Xiaomi,MI NOTE LTE,1,3011716,2,android,6.0.1,137106101100100,2190219618,"ag_2100040,3002847,3003097,3003255,3003321,300..."
20,1580210,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137104102101100,...,Apple,iPhone 6,1,3012032,1,ios,9.3.1,137104102100100,2190220763,NaN
21,1451143,230000063,102400_102401,B4734117F35EE97F,105.0,2070241.0,False,1000023,1,137104104117100,...,Apple,iPhone 6 Plus (A1522/A1524/A1593),1,2307029,1,ios,11.4,137104104100100,2190218922,NaN
22,1580210,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137104103101100,...,Apple,iPhone 6 Plus,1,3012032,1,ios,10.3.3,137104103100100,2190220762,NaN
23,1575260,230001694,16_100508,5C84C3D2EBBB9D7C,111.0,2070351.0,False,1003562,1,137103107109100,...,Apple,"iPhone7,2",1,3011376,1,ios,11.3,137103107100100,2190219972,NaN
24,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137104104110100,...,NaN,OPPO R11s,1,3011304,2,android,7.1.1,137104104100100,2190218850,"3004081,3004430,3004434"
25,1579834,230001696,101000_101002,310405E93895BD58,111.0,2070351.0,False,1003456,1,137104104103100,...,Apple,"iPhone7,1",1,3011668,1,ios,9.3.2,137104104100100,2190219218,NaN
26,1580370,230001696,101000_101002,310405E93895BD58,100.0,2071133.0,False,1003456,1,137103101100100,...,Apple,iPhone 7,1,3012068,1,ios,11.4.1,137103101100100,2190220819,NaN
27,1575104,230001547,101700_101704,37E91828E6FB695A,108.0,2090600.0,False,1003211,1,137104104114100,...,HUAWEI,HWI-AL00,1,3011458,2,android,8.0.0,137104104100100,2190218731,"3004430,3004434"
28,1547080,230000065,101700_101704,E257895F74792E81,107.0,2070969.0,False,1000021,1,137103106101100,...,OPPO,OPPO A57t,1,3009240,2,android,6.0.1,137103106100100,2190221846,"3004406,3004430,3004434"
29,1575100,230000063,102400_102401,B4734117F35EE97F,111.0,1110016.0,False,1000023,3,137104106114100,...,OPPO A59s,OPPO A59s,1,2311393,2,android,5.1,137104106100100,2190218452,"2100078,3001769,3001771,3001797,3001799,300187..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1041644,1586162,230001025,101700_101704,50822F8310CAE01D,107.0,2070969.0,False,1001979,1,137101104102100,...,OPPO,OPPO R9s Plus,1,3012866,2,android,6.0.1,137101104100100,2190717965,"3003779,3003843,3003851,3003871,3003877,300393..."
1041645,1577888,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137103105105100,...,NaN,OPPO A57,1,3011828,2,android,6.0.1,137103105100100,2190716065,"3004430,3004434"
1041646,1456557,230000063,102400_102401,B4734117F35EE97F,107.0,1100001.0,False,1000023,1,137104104118100,...,OPPO,OPPO%2525252525252BR9%2525252525252BPlusm%2525...,1,2300169,2,android,5.1.1,137104104100100,2190715633,"2100078,3002099,3002265,3002373,3002393,300239..."
1041647,1517657,230000063,102400_102401,B4734117F35EE97F,108.0,1080008.0,False,1000023,1,137105102108100,...,GIONEE,F100,4,2306891,2,android,5.1.0,137105102100100,2190715716,"3003033,3003505,3004059,3004081,3004089,300410..."
1041648,1456557,230000063,102400_102401,B4734117F35EE97F,107.0,1100001.0,False,1000023,1,137103102101100,...,vivo,vivo%2525252525252BZ1,4,2300169,2,android,8.1.0,137103102100100,2190716351,NaN
1041649,1547080,230000065,101700_101704,E257895F74792E81,107.0,2070969.0,False,1000021,1,137101104110100,...,OPPO,OPPO A83,1,3009240,2,android,7.1.1,137101104100100,2190717313,"3004406,3004430,3004434"
1041650,1549532,230000063,102400_102401,B4734117F35EE97F,100.0,2089397.0,False,1000023,1,137104104106100,...,HUAWEI,SCL-TL00,1,3009080,2,android,5.1.1,137104104100100,2190716090,"3004430,3004434"
1041651,1585512,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103107117100,...,vivo,vivo-Y67A,1,3006301,2,android,6.0.0,137103107100100,2190716542,"3003779,3003863,3003939,3004059,3004081,300408..."
1041652,1585884,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137101103107100,...,OPPO,OPPO-A83,1,3010798,2,android,7.1.1,137101103100100,2190718793,NaN
1041653,1549584,230000065,101700_101704,E257895F74792E81,100.0,2089397.0,False,1000021,1,137105104101100,...,HUAWEI,ALE-TL00,1,3009966,2,android,6.0,137105104100100,2190718442,"3004430,3004434"
1041654,1585966,230001025,101700_101704,50822F8310CAE01D,110.0,2070523.0,False,1001979,1,137101103103100,...,vivo,vivo X9s Plus,0,3012628,2,android,7.1.2,137101103100100,2190717393,"3003123,3003123,3003505,3003779,3003843,300385..."
1041655,1585512,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137105102105100,...,HUAWEI,TRT-AL00A,1,3006301,2,android,7.0.0,137105102100100,2190717846,NaN
1041656,1495325,230000063,102400_102401,B4734117F35EE97F,108.0,2071279.0,False,1000023,1,137105104111100,...,Apple,"iPhone10,2",3,3003463,1,ios,11.0,137105104100100,2190716256,NaN
1041657,1579370,230001620,101700_101799,CC4602621BE800EA,100.0,2089397.0,False,1003328,1,137104101116100,...,OPPO,OPPO+A57,1,3012178,2,android,6.0.1,137104101100100,2190717264,"gd_2100001,ag_2100040,3004430,3004434"
1041658,1547080,230000065,101700_101704,E257895F74792E81,107.0,2070969.0,False,1000021,1,137102103108100,...,HONOR,PRA-AL00X,1,3009240,2,android,8.0.0,137102103100100,2190715520,"3004430,3004434"
1041659,1585436,230000063,102400_102401,B4734117F35EE97F,100.0,2089397.0,False,1000023,1,137103106108100,...,vivo,vivo+X9s+Plus+L,1,3012120,2,android,7.1.2,137103106100100,2190717580,",3003305,3003779,3003843,3003851,3003863,30038..."
1041660,1584418,230001025,101700_101704,50822F8310CAE01D,108.0,2071003.0,False,1001979,1,137103105101100,...,vivo,vivo Y67L,1,3012606,2,android,6.0,137103105100100,2190717495,"3003779,3003795,3003863,3004059,3004081,300408..."
1041661,1577888,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137104101109100,...,NaN,H60-L11,1,3011828,2,android,4.4.2,137104101100100,2190715211,"gd_2100001,2100012,2100121,2100042,ag_2100040,..."
1041662,1585724,230000063,102400_102401,B4734117F35EE97F,105.0,2090638.0,False,1000023,1,137103103102100,...,OPPO,OPPO R9s Plust,1,3012794,2,android,6.0.1,137103103100100,2190715923,"gd_2100000,3002267,3002329,3002393,3002695,300..."
1041663,1585512,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103107116100,...,OPPO,OPPO-A30,1,3006301,2,android,5.1.1,137103107100100,2190718212,"3003795,3003805,3003819,3003851,3003863,gd_210..."
1041664,1585884,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103107108100,...,Xiaomi,Redmi-5A,1,3010798,2,android,7.1.2,137103107100100,2190716264,NaN
1041665,1575398,230001636,101800_101812,42A4CB9035B7F50E,111.0,1110016.0,False,1003514,3,137103106108100,...,OPPO A57,OPPO A57,4,3011154,2,android,6.0.1,137103106100100,2190718412,"2100013,2101242,2100019,2100141,2100909,210081..."
1041666,1577888,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137104104104100,...,NaN,vivo Xplay5S,1,3011828,2,android,6.0,137104104100100,2190717095,"gd_2100000,3002095,3002393,3002581,3002627,300..."
1041667,1573138,230000063,102400_102401,B4734117F35EE97F,111.0,1110016.0,False,1000023,1,137101103103100,...,SM-J5008,SM-J5008,1,3011158,2,android,5.1,137101103100100,2190715929,"gd_2100000,ag_2100040,3001787,3001899,3001989,..."
1041668,1517657,230000063,102400_102401,B4734117F35EE97F,108.0,1080008.0,False,1000023,1,137104103101100,...,HUAWEI,EVA-AL10,0,2306891,2,android,6.0.0,137104103100100,2190716649,"2100909,2101058,2100130,2100144,2101058,210007..."
1041669,1585512,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137106102110100,...,OPPO,OPPO-R9s,1,3006301,2,android,6.0.1,137106102100100,2190717893,"2100013,2100003,2100004,gd_2100000,2100084,210..."
1041670,1585948,230000971,16_100509,D54E631F07CA4751,107.0,2089229.0,False,1002549,1,137101103107100,...,Xiaomi,MI-5X,1,3011366,2,android,7.1.2,137101103100100,2190717210,",3003315,3003321,3003323,3003537,3004081,30044..."
1041671,1586450,230001025,101700_101704,50822F8310CAE01D,110.0,2070523.0,False,1001979,1,137103107116100,...,vivo,vivo Y37,0,3012920,2,android,5.0.2,137103107100100,2190715980,"3003123,gd_2100001,ag_2100038,3004430,3004434"
1041672,1518579,230000063,102400_102401,B4734117F35EE97F,103.0,1030051.0,False,1000023,1,137103106111100,...,vivo,vivo%20Y75A,3,3006011,2,android,7.1.1,137103106100100,2190716114,",3003525,3003563,3003779,3003843,3003851,30038..."
1041673,1575020,230000971,16_100509,D54E631F07CA4751,108.0,2070079.0,False,1002549,1,137104101114100,...,OPPO,A31,1,3010806,2,android,4.4.4,137104101100100,2190715765,"2100235,gd_2100001,2100126,3001793,3001949,300..."

In [8]:
data.nunique()

adid                        2113
advert_id                     39
advert_industry_inner         25
advert_name                   35
app_cate_id                   22
app_id                       439
app_paid                       1
campaign_id                   66
carrier                        4
city                         333
click                          2
creative_has_deeplink          2
creative_height               13
creative_id                  872
creative_is_download           2
creative_is_js                 1
creative_is_jump               2
creative_is_voicead            1
creative_tp_dnf               42
creative_type                  5
creative_width                20
devtype                        4
f_channel                     77
inner_slot_id               1180
instance_id              1041674
make                        3196
model                      14209
nnt                            6
orderid                      953
os                             3
os_name                        3
osv                          303
province                      35
time                      474309
user_tags                 481795
dtype: int64

In [4]:
import pandas as pd
data=pd.read_csv('/users/lisa/Downloads/round1_iflyad_train.txt',sep='/t')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [5]:
data

        instance_id\ttime\tcity\tprovince\tuser_tags\tcarrier\tdevtype\tmake\tmodel\tnnt\tos\tosv\tos_name\tadid\tadvert_id\torderid\tadvert_industry_inner\tcampaign_id\tcreative_id\tcreative_tp_dnf\tapp_cate_id\tf_channel\tapp_id\tinner_slot_id\tcreative_type\tcreative_width\tcreative_height\tcreative_is_jump\tcreative_is_download\tcreative_is_js\tcreative_is_voicead\tcreative_has_deeplink\tapp_paid\tadvert_name\tclick
0        86294719979897807\t2190219034\t137103102105100...
1        2699289844928136052\t2190221070\t1371051011001...
2        3117527168445845752\t2190219793\t1371031041111...
3        3398484891050993371\t2190221704\t1371031021131...
4        2035477570591176488\t2190220024\t1371031021091...
5        2065527640347419040\t2190221228\t1371041041041...
6        9137625226649553828\t2190221448\t1371031011001...
7        8256661937587962948\t2190221002\t1371011021001...
8        2270018983665706006\t2190221002\t1371051041141...
9        5028130673845168373\t2190220484\t1371041011131...
10       7244953732869107657\t2190219610\t1371051021091...
11       6037028576611512255\t2190221545\t1371041041021...
12       650175271525047126\t2190220173\t13710210110710...
13       5475325654902004949\t2190218858\t1371041031121...
14       8998015894377581170\t2190221043\t1371031021051...
15       8426292355035054326\t2190221640\t1371041041021...
16       2325035151095483368\t2190218712\t1371041041021...
17       6055994017121770743\t2190219309\t1371011031091...
18       7772108077327804954\t2190220810\t1371061011011...
19       6037796481926109351\t2190219618\t1371061011011...
20       7690196785927092190\t2190220763\t1371041021011...
21       6834706088421074222\t2190218922\t1371041041171...
22       7035869949207458857\t2190220762\t1371041031011...
23       3391476005996906358\t2190219972\t1371031071091...
24       4366119081754604355\t2190218850\t1371041041101...
25       5814974380636515882\t2190219218\t1371041041031...
26       8708042822830332926\t2190220819\t1371031011001...
27       3966866514749073864\t2190218731\t1371041041141...
28       6596979575596904456\t2190221846\t1371031061011...
29       5243448280380415095\t2190218452\t1371041061141...
...                                                    ...
1001620  5947135890864827366\t2190056554\t1371041041141...
1001621  2680060306955103936\t2190056546\t1371031061061...
1001622  4405731454987817654\t2190058665\t1371011051011...
1001623  6149835897014590570\t2190059922\t1371021021011...
1001624  4625287021976573458\t2190057927\t1371041041061...
1001625  8362821470486156955\t2190058808\t1371011041051...
1001626  577497101729177294\t2190059670\t13710110310210...
1001627  1445329354866945756\t2190058347\t1371041031011...
1001628  1819629263241864895\t2190057048\t1371031021041...
1001629  6219904181232667730\t2190058259\t1371041041101...
1001630  3966271892572386821\t2190057446\t1371031021111...
1001631  4824647861428126155\t2190056788\t1371041041041...
1001632  7389903125897554828\t2190059837\t1371021011091...
1001633  1938582040595718150\t2190059208\t1371041011031...
1001634  9162332309127849700\t2190059185\t1371041021011...
1001635  573994439313108256\t2190057507\t13710110410210...
1001636  7345249847130960415\t2190059259\t1371031071131...
1001637  2148354338721938484\t2190059911\t1371041061071...
1001638  5128378860796553144\t2190058192\t1371031031111...
1001639  8209810809429446914\t2190058802\t1371031071081...
1001640  9034124859155440479\t2190058999\t1371031071081...
1001641  6797049347428402724\t2190056949\t0\t0\t\t1\t2\...
1001642  5494367442716352654\t2190056425\t1371041011011...
1001643  423330999260672812\t2190057784\t13710310410410...
1001644  8940804712109863155\t2190056753\t1371061011061...
1001645  2569120806007737669\t2190058023\t1371041021011...
1001646  5328420823695634765\t2190056965\t1371011031061...
1001647  2732525116033744741\t2190059227\t1371051031081...
1001648  4026815797356128987\t2190057688\t1371031021091...
1001649  2863771093216612552\t2190058546\t1371041061091...

[1001650 rows x 1 columns]

In [6]:
import pandas as pd
data=pd.read_csv('/users/lisa/Downloads/round1_iflyad_train.txt',sep='\t')

In [7]:
data

,instance_id,time,city,province,user_tags,carrier,devtype,make,model,nnt,...,creative_width,creative_height,creative_is_jump,creative_is_download,creative_is_js,creative_is_voicead,creative_has_deeplink,app_paid,advert_name,click
0,86294719979897807,2190219034,137103102105100,137103102100100,NaN,1,2,HUAWEI,HUAWEI-CAZ-AL10,1,...,1280,720,True,False,False,False,False,False,B4734117F35EE97F,0
1,2699289844928136052,2190221070,137105101100100,137105101100100,"2100191,2100078,3001825,,3001781,3001791,30017...",3,2,Xiaomi,Redmi Note 4,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
2,3117527168445845752,2190219793,137103104111100,137103104100100,NaN,3,2,OPPO,OPPO+R11s,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
3,3398484891050993371,2190221704,137103102113100,137103102100100,"2100098,gd_2100000,3001791,3001795,3002193,300...",0,2,NaN,OPPO A57,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
4,2035477570591176488,2190220024,137103102109100,137103102100100,NaN,1,2,Apple,iPhone 7,3,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
5,2065527640347419040,2190221228,137104104104100,137104104100100,"3002265,3002613,3002993,3003055,3003147,300331...",1,2,"Xiaomi,MI 6,sagit",MI 6,1,...,320,480,True,False,False,False,False,False,862FF2E9B0AD4C14,0
6,9137625226649553828,2190221448,137103101100100,137103101100100,NaN,1,2,Apple,iPhone 7 Plus,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
7,8256661937587962948,2190221002,137101102100100,137101102100100,"gd_2100000,2100143,ag_2100040,3001837,3002907,...",1,2,HUAWEI,HUAWEI-NXT-AL10,1,...,1280,720,True,False,False,False,False,False,B4734117F35EE97F,0
8,2270018983665706006,2190221002,137105104114100,137105104100100,",3004484,3004430,3004434,3004490,3004468,30045...",0,2,NaN,OPPO R9s,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
9,5028130673845168373,2190220484,137104101113100,137104101100100,"2100197,2100150,2100094,2100237,2100132,ag_210...",1,2,vivo,vivo+Y13iL,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
10,7244953732869107657,2190219610,137105102109100,137105102100100,"2100480,2100118,2101058,2100042,2100017,210013...",1,2,vivo,vivo Xplay6,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
11,6037028576611512255,2190221545,137104104102100,137104104100100,NaN,3,2,OPPO,OPPO R9s,1,...,300,300,True,False,False,False,False,False,68C5520FFBC5FC19,0
12,650175271525047126,2190220173,137102101107100,137102101100100,"gd_2100001,ag_2100039,3004430,3004434",1,2,x600,x600,1,...,960,640,True,False,False,False,False,False,50822F8310CAE01D,0
13,5475325654902004949,2190218858,137104103112100,137104103100100,NaN,0,2,NaN,vivo X9s,4,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
14,8998015894377581170,2190221043,137103102105100,137103102100100,NaN,2,2,BBK,vivo Y19t,3,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
15,8426292355035054326,2190221640,137104104102100,137104104100100,"gd_2100000,3001771,3001881,3001889,3001899,300...",1,2,Xiaomi,MI%206,3,...,320,480,True,False,False,False,False,False,68C5520FFBC5FC19,0
16,2325035151095483368,2190218712,137104104102100,137104104100100,NaN,1,2,OPPO,OPPO R11s,1,...,960,640,True,False,False,False,False,False,68C5520FFBC5FC19,0
17,6055994017121770743,2190219309,137101103109100,137101103100100,NaN,1,2,vivo Y79A,vivo Y79A,1,...,160,640,True,False,False,False,False,False,B4734117F35EE97F,0
18,7772108077327804954,2190220810,137106101101100,137106101100100,"3003779,3004059,3004214,3004430,3004434",1,2,OPPO,OPPO+A33,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
19,6037796481926109351,2190219618,137106101101100,137106101100100,"ag_2100040,3002847,3003097,3003255,3003321,300...",1,2,Xiaomi,MI NOTE LTE,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
20,7690196785927092190,2190220763,137104102101100,137104102100100,NaN,1,2,Apple,iPhone 6,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
21,6834706088421074222,2190218922,137104104117100,137104104100100,NaN,1,2,Apple,iPhone 6 Plus (A1522/A1524/A1593),1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
22,7035869949207458857,2190220762,137104103101100,137104103100100,NaN,1,2,Apple,iPhone 6 Plus,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
23,3391476005996906358,2190219972,137103107109100,137103107100100,NaN,1,2,Apple,"iPhone7,2",1,...,100,640,True,False,False,False,False,False,5C84C3D2EBBB9D7C,0
24,4366119081754604355,2190218850,137104104110100,137104104100100,"3004081,3004430,3004434",0,2,NaN,OPPO R11s,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
25,5814974380636515882,2190219218,137104104103100,137104104100100,NaN,1,2,Apple,"iPhone7,1",1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
26,8708042822830332926,2190220819,137103101100100,137103101100100,NaN,1,2,Apple,iPhone 7,1,...,320,480,True,False,False,False,False,False,310405E93895BD58,0
27,3966866514749073864,2190218731,137104104114100,137104104100100,"3004430,3004434",1,2,HUAWEI,HWI-AL00,1,...,320,640,True,False,False,False,False,False,37E91828E6FB695A,0
28,6596979575596904456,2190221846,137103106101100,137103106100100,"3004406,3004430,3004434",1,2,OPPO,OPPO A57t,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,1
29,5243448280380415095,2190218452,137104106114100,137104106100100,"2100078,3001769,3001771,3001797,3001799,300187...",3,2,OPPO A59s,OPPO A59s,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001620,5947135890864827366,2190056554,137104104114100,137104104100100,"2100121,2100011,gd_2100001,2100120,2100041,210...",1,2,DIG-AL00,DIG-AL00,1,...,100,640,True,False,False,False,False,False,862FF2E9B0AD4C14,0
1001621,2680060306955103936,2190056546,137103106106100,137103106100100,NaN,0,2,NaN,Lenovo X3c50,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
1001622,4405731454987817654,2190058665,137101105101100,137101105100100,"gd_2100000,3001747,3001791,3001793,3001847,300...",1,2,OPPO,R7c,1,...,960,640,True,False,False,False,False,False,50822F8310CAE01D,0
1001623,6149835897014590570,2190059922,137102102101100,137102102100100,"3003779,3003819,3003843,3003845,3003851,300386...",2,2,MI 6,MI 6,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001624,4625287021976573458,2190057927,137104104106100,137104104100100,"3002747,3003379,3003509,3003537,3003559,300365...",0,2,NaN,OPPO A59m,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
1001625,8362821470486156955,2190058808,137101104105100,137101104100100,"3004430,3004434",0,2,NaN,FLA-AL10,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
1001626,577497101729177294,2190059670,137101103102100,137101103100100,"gd_2100001,ag_2100040,3004430,3004434",1,2,Meizu,m2+note,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
1001627,1445329354866945756,2190058347,137104103101100,137104103100100,3003783,3,2,OPPO,OPPO+A57,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001628,1819629263241864895,2190057048,137103102104100,137103102100100,"3004430,3004434",1,2,vivo,vivo%20Y31,3,...,160,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001629,6219904181232667730,2190058259,137104104110100,137104104100100,NaN,3,2,Meizu,M5s,1,...,960,640,True,False,False,False,False,False,862FF2E9B0AD4C14,0
1001630,3966271892572386821,2190057446,137103102111100,137103102100100,"3004430,3004434",1,2,HUAWEI,NEM-UL10,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001631,4824647861428126155,2190056788,137104104104100,137104104100100,NaN,1,2,Apple,"iPhone9,2",1,...,960,640,True,False,False,False,False,False,862FF2E9B0AD4C14,0
1001632,7389903125897554828,2190059837,137102101109100,137102101100100,"3004430,3004434",2,2,vivo,vivo+Y55,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001633,1938582040595718150,2190059208,137104101103100,137104101100100,"2100017,2101117,2100078,2100122",1,2,SUGAR,SUGAR%20F7,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001634,9162332309127849700,2190059185,137104102101100,137104102100100,"gd_2100000,3004093,3004095,3004430,3004434",1,2,HUAWEI,PLK-AL10,4,...,960,640,True,False,False,False,False,False,50822F8310CAE01D,0
1001635,573994439313108256,2190057507,137101104102100,137101104100100,"gd_2100001,3001825,,3001779,3001787,3001955,30...",1,2,OPPO,OPPO A33,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
1001636,7345249847130960415,2190059259,137103107113100,137103107100100,3004430,1,2,Meizu,M611D,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
1001637,2148354338721938484,2190059911,137104106107100,137104106100100,"gd_2100000,ag_2100039,3007639321,3004430,3004434",1,2,vivo,vivo Y51,1,...,960,640,True,False,False,False,False,False,50822F8310CAE01D,0
1001638,5128378860796553144,2190058192,137103103111100,137103103100100,NaN,1,2,BBK,vivo+Y27,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001639,8209810809429446914,2190058802,137103107108100,137103107100100,NaN,1,2,Qingcheng,GO C2,1,...,960,640,True,False,False,False,False,False,50822F8310CAE01D,1
1001640,9034124859155440479,2190058999,137103107108100,137103107100100,"2100782,2100501,2100144,2101264,2100133,gd_210...",2,2,Meizu,M6+Note,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001641,6797049347428402724,2190056949,0,0,NaN,1,2,Apple,iPhone 6s,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001642,5494367442716352654,2190056425,137104101101100,137104101100100,NaN,1,2,vivo,vivo+Y75A,4,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001643,423330999260672812,2190057784,137103104104100,137103104100100,NaN,1,2,DIG-TL10,DIG-TL10,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001644,8940804712109863155,2190056753,137106101106100,137106101100100,"gd_2100001,2100042,2100041,3002313,3002567,300...",3,2,OPPO,OPPO+A37m,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001645,2569120806007737669,2190058023,137104102101100,137104102100100,NaN,3,2,HUAWEI,BLN-AL40,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
1001646,5328420823695634765,2190056965,137101103106100,137101103100100,"3003123,3003123,3003313,3003321,3003323,300337...",1,2,vivo X9s L,vivo X9s L,4,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001647,2732525116033744741,2190059227,137105103108100,137105103100100,NaN,1,2,vivo,vivo Y79,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
1001648,4026815797356128987,2190057688,137103102109100,137103102100100,"3004406,3004450,3004430,3004434,3004448,3004500",1,2,HUAWEI,EML-AL00,4,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,1
1001649,2863771093216612552,2190058546,137104106109100,137104106100100,NaN,1,2,HUAWEI,KIW-UL00,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,1

In [8]:
data.head()

,instance_id,time,city,province,user_tags,carrier,devtype,make,model,nnt,...,creative_width,creative_height,creative_is_jump,creative_is_download,creative_is_js,creative_is_voicead,creative_has_deeplink,app_paid,advert_name,click
0,86294719979897807,2190219034,137103102105100,137103102100100,NaN,1,2,HUAWEI,HUAWEI-CAZ-AL10,1,...,1280,720,True,False,False,False,False,False,B4734117F35EE97F,0
1,2699289844928136052,2190221070,137105101100100,137105101100100,"2100191,2100078,3001825,,3001781,3001791,30017...",3,2,Xiaomi,Redmi Note 4,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
2,3117527168445845752,2190219793,137103104111100,137103104100100,NaN,3,2,OPPO,OPPO+R11s,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
3,3398484891050993371,2190221704,137103102113100,137103102100100,"2100098,gd_2100000,3001791,3001795,3002193,300...",0,2,NaN,OPPO A57,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
4,2035477570591176488,2190220024,137103102109100,137103102100100,NaN,1,2,Apple,iPhone 7,3,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0

In [10]:
data.columns.values

array(['instance_id', 'time', 'city', 'province', 'user_tags', 'carrier',
       'devtype', 'make', 'model', 'nnt', 'os', 'osv', 'os_name', 'adid',
       'advert_id', 'orderid', 'advert_industry_inner', 'campaign_id',
       'creative_id', 'creative_tp_dnf', 'app_cate_id', 'f_channel',
       'app_id', 'inner_slot_id', 'creative_type', 'creative_width',
       'creative_height', 'creative_is_jump', 'creative_is_download',
       'creative_is_js', 'creative_is_voicead', 'creative_has_deeplink',
       'app_paid', 'advert_name', 'click'], dtype=object)

In [11]:
data['orderid']

0          3010798
1          2311397
2          3008491
3          3011304
4          2304491
5          3005529
6          3012112
7          3010798
8          3011304
9          3012120
10         3011734
11         3012310
12         3009834
13         3011304
14         2310543
15         3012288
16         3012306
17         3011260
18         3009770
19         3011716
20         3012032
21         2307029
22         3012032
23         3011376
24         3011304
25         3011668
26         3012068
27         3011458
28         3009240
29         2311393
            ...
1001620    3006077
1001621    3011304
1001622    3006695
1001623    3011158
1001624    3011304
1001625    3011304
1001626    3008491
1001627    3012120
1001628    2305491
1001629    3005809
1001630    2304589
1001631    3005805
1001632    3010348
1001633    3006011
1001634    3008569
1001635    3009240
1001636    3008491
1001637    3006695
1001638    3012120
1001639    3006695
1001640    3005355
1001641    2307815
1001642    3012120
1001643    3011158
1001644    3010348
1001645    3008491
1001646    2310711
1001647    3009700
1001648    3005605
1001649    3008491
Name: orderid, Length: 1001650, dtype: int64

In [12]:
print(data['orderid'],data['time'])

0          3010798
1          2311397
2          3008491
3          3011304
4          2304491
5          3005529
6          3012112
7          3010798
8          3011304
9          3012120
10         3011734
11         3012310
12         3009834
13         3011304
14         2310543
15         3012288
16         3012306
17         3011260
18         3009770
19         3011716
20         3012032
21         2307029
22         3012032
23         3011376
24         3011304
25         3011668
26         3012068
27         3011458
28         3009240
29         2311393
            ...
1001620    3006077
1001621    3011304
1001622    3006695
1001623    3011158
1001624    3011304
1001625    3011304
1001626    3008491
1001627    3012120
1001628    2305491
1001629    3005809
1001630    2304589
1001631    3005805
1001632    3010348
1001633    3006011
1001634    3008569
1001635    3009240
1001636    3008491
1001637    3006695
1001638    3012120
1001639    3006695
1001640    3005355
1001641    2307815
1001642    3012120
1001643    3011158
1001644    3010348
1001645    3008491
1001646    2310711
1001647    3009700
1001648    3005605
1001649    3008491
Name: orderid, Length: 1001650, dtype: int64 0          2190219034
1          2190221070
2          2190219793
3          2190221704
4          2190220024
5          2190221228
6          2190221448
7          2190221002
8          2190221002
9          2190220484
10         2190219610
11         2190221545
12         2190220173
13         2190218858
14         2190221043
15         2190221640
16         2190218712
17         2190219309
18         2190220810
19         2190219618
20         2190220763
21         2190218922
22         2190220762
23         2190219972
24         2190218850
25         2190219218
26         2190220819
27         2190218731
28         2190221846
29         2190218452
              ...
1001620    2190056554
1001621    2190056546
1001622    2190058665
1001623    2190059922
1001624    2190057927
1001625    2190058808
1001626    2190059670
1001627    2190058347
1001628    2190057048
1001629    2190058259
1001630    2190057446
1001631    2190056788
1001632    2190059837
1001633    2190059208
1001634    2190059185
1001635    2190057507
1001636    2190059259
1001637    2190059911
1001638    2190058192
1001639    2190058802
1001640    2190058999
1001641    2190056949
1001642    2190056425
1001643    2190057784
1001644    2190056753
1001645    2190058023
1001646    2190056965
1001647    2190059227
1001648    2190057688
1001649    2190058546
Name: time, Length: 1001650, dtype: int64

In [13]:
data['orderid'].sort

AttributeError: 'Series' object has no attribute 'sort'

In [14]:
data['orderid'].sort_values()

161855    2300169
563047    2300169
927089    2300169
852583    2300169
563060    2300169
852573    2300169
10618     2300169
927123    2300169
927130    2300169
927136    2300169
927142    2300169
513563    2300169
927157    2300169
927186    2300169
483128    2300169
563087    2300169
563088    2300169
927262    2300169
563090    2300169
816618    2300169
927263    2300169
383088    2300169
483144    2300169
975396    2300169
563045    2300169
927034    2300169
927032    2300169
365370    2300169
926884    2300169
562962    2300169
           ...
356738    3012854
47038     3012854
664991    3012854
47047     3012854
166253    3012854
664813    3012854
356707    3012854
664781    3012854
46951     3012854
664640    3012854
46968     3012854
664659    3012854
356654    3012854
664662    3012854
166145    3012854
664671    3012854
664675    3012854
356609    3012854
664678    3012854
288888    3012854
356666    3012854
166163    3012854
166178    3012854
356678    3012854
664754    3012854
664755    3012854
356701    3012854
664774    3012854
664688    3012854
776824    3012854
Name: orderid, Length: 1001650, dtype: int64

In [15]:
data['time'].sort_values()

874185    2190038403
932291    2190038408
731       2190038409
874289    2190038409
26991     2190038409
499694    2190038409
336305    2190038409
26967     2190038409
336310    2190038409
336021    2190038409
932011    2190038409
363965    2190038409
927       2190038409
676       2190038409
413402    2190038409
932190    2190038409
648947    2190038409
310555    2190038409
336556    2190038409
363766    2190038409
467966    2190038409
29784     2190038410
413491    2190038410
848987    2190038410
75911     2190038410
413598    2190038410
646       2190038410
499693    2190038410
957569    2190038410
957484    2190038410
             ...
268066    2190643059
894089    2190643059
146324    2190643062
147562    2190643063
776997    2190643064
586889    2190643065
21773     2190643066
638893    2190643067
207241    2190643068
268155    2190643069
268133    2190643069
894152    2190643069
21715     2190643070
147618    2190643071
638888    2190643071
638908    2190643072
664971    2190643072
665015    2190643073
400740    2190643073
894047    2190643073
250194    2190643074
776855    2190643074
664616    2190643076
259665    2190643076
147532    2190643077
586948    2190643078
664589    2190643078
259656    2190643078
259689    2190643078
638857    2190643079
Name: time, Length: 1001650, dtype: int64

In [16]:
data['orderid'].apply(lambda x:int(str(x)[:2])).unique()

array([30, 23])

In [17]:
data['orderid'].nunique()

936

In [18]:
data['orderid'].apply(lambda x:int(str(x)[:4])).unique()

array([3010, 2311, 3008, 3011, 2304, 3005, 3012, 3009, 2310, 2307, 3006,
       3004, 2300, 2308, 2306, 2309, 3003, 2302, 3007, 2312, 2305, 2303,
       2301])

In [19]:
data['adid']

0          1560128
1          1488859
2          1537089
3          1577884
4          1432367
5          1559158
6          1580496
7          1560128
8          1577884
9          1579122
10         1579878
11         1580588
12         1548446
13         1577884
14         1573112
15         1580394
16         1580580
17         1574082
18         1548194
19         1579858
20         1580210
21         1451143
22         1580210
23         1575260
24         1577884
25         1579834
26         1580370
27         1575104
28         1547080
29         1575100
            ...
1001620    1558632
1001621    1577884
1001622    1526877
1001623    1573138
1001624    1577884
1001625    1577884
1001626    1537089
1001627    1579122
1001628    1449699
1001629    1558708
1001630    1441921
1001631    1558886
1001632    1553390
1001633    1518559
1001634    1537569
1001635    1547080
1001636    1537089
1001637    1526877
1001638    1579122
1001639    1526877
1001640    1528221
1001641    1453589
1001642    1579122
1001643    1573138
1001644    1553390
1001645    1537089
1001646    1547536
1001647    1548418
1001648    1548574
1001649    1537089
Name: adid, Length: 1001650, dtype: int64

In [20]:
data.groupby('adid')['click'].agg({mean,count})

NameError: name 'mean' is not defined

In [21]:
data.groupby('adid')['click'].agg({'mean','count'})

         count      mean
adid
1403645   9027  0.061925
1412379     18  0.111111
1412387    106  0.018868
1414879     45  0.000000
1427605      1  0.000000
1429239     74  0.783784
1430599      9  0.444444
1430607    230  0.017391
1431151      4  0.250000
1431475    281  0.323843
1432367    777  0.308880
1438027     23  0.260870
1438043     97  0.185567
1441921    951  0.401682
1445779    208  0.168269
1446369   1428  0.004202
1448123     10  0.000000
1448125      3  0.000000
1448129      1  1.000000
1448131      3  0.000000
1448367      1  0.000000
1448371      3  0.000000
1448373      6  0.000000
1448377     10  0.000000
1448379      4  0.250000
1448417      8  0.000000
1448423      3  0.000000
1448425      5  0.000000
1449571      3  0.333333
1449575      3  0.000000
...        ...       ...
1586024     11  0.000000
1586026      6  0.000000
1586028      2  0.000000
1586032      4  0.000000
1586034      3  0.000000
1586036      4  0.000000
1586038      2  0.000000
1586040      3  0.000000
1586044     39  0.025641
1586046     29  0.034483
1586048      2  0.000000
1586060     66  0.348485
1586062     55  0.254545
1586074    120  0.008333
1586076    128  0.000000
1586078    146  0.000000
1586080      3  0.000000
1586082   1360  0.270588
1586084   1479  0.243408
1586130     16  0.000000
1586132     22  0.045455
1586134     47  0.000000
1586136     56  0.000000
1586138     50  0.000000
1586142      2  0.000000
1586144      4  0.000000
1586146      1  0.000000
1586148      3  0.000000
1586150      1  0.000000
1586152      1  0.000000

[2079 rows x 2 columns]

In [22]:
data.groupby('adid')['click'].agg({'mean','count'}).sort_values('click')""

SyntaxError: invalid syntax (<ipython-input-22-2502f2104e8d>, line 1)

In [23]:
data.groupby('adid')['click'].agg({'mean','count'}).sort_values('click')

KeyError: 'click'

In [24]:
data.groupby('adid')['click'].agg({'mean','count'}).sort_values()

TypeError: sort_values() missing 1 required positional argument: 'by'

In [25]:
data.groupby('adid')['click'].agg({'mean','count'}).sort_values('mean')

         count      mean
adid
1577714      3  0.000000
1578536      1  0.000000
1578532      5  0.000000
1578406      1  0.000000
1578402      2  0.000000
1578280      5  0.000000
1578276      2  0.000000
1578164      6  0.000000
1578162      1  0.000000
1578160      5  0.000000
1578538      1  0.000000
1578056      1  0.000000
1578050     11  0.000000
1577956      1  0.000000
1577952      3  0.000000
1577950     14  0.000000
1577830      1  0.000000
1577828      6  0.000000
1577826      1  0.000000
1577824      5  0.000000
1577822      1  0.000000
1578054      4  0.000000
1577820      7  0.000000
1578604      1  0.000000
1578608      1  0.000000
1578938      4  0.000000
1578872      3  0.000000
1578868      1  0.000000
1578866      6  0.000000
1578808      2  0.000000
...        ...       ...
1585208    222  0.635135
1537087    107  0.644860
1575372    138  0.644928
1579934      3  0.666667
1580896     33  0.666667
1491431    128  0.679688
1453939     93  0.688172
1555172     42  0.690476
1584534     45  0.711111
1585432   4288  0.719683
1547072     11  0.727273
1453979     92  0.728261
1585738      4  0.750000
1585744     31  0.774194
1429239     74  0.783784
1585964     14  0.785714
1584440      1  1.000000
1585080      1  1.000000
1585088      1  1.000000
1585490      1  1.000000
1545402      1  1.000000
1575730      1  1.000000
1585440      1  1.000000
1580674      1  1.000000
1580680      2  1.000000
1579360      1  1.000000
1585338      1  1.000000
1502875      2  1.000000
1453779      1  1.000000
1448129      1  1.000000

[2079 rows x 2 columns]

In [26]:
data['ad_prefix']=data['adid'].apply(lambda x:int(str(x)[:3]))
data.groupby('ad_prefix')['click'].agg({'mean','count'}).sort_values('mean')

            count      mean
ad_prefix
141           169  0.023669
148         14203  0.056397
140          9027  0.061925
145         30223  0.076630
144          5705  0.083436
151         48246  0.149132
157        321465  0.150094
150          4359  0.174123
149         12642  0.186521
158        149561  0.195465
147           278  0.197842
155         90870  0.198294
152         13404  0.218517
156         52157  0.242594
143          1421  0.256158
153         52503  0.265928
154        192850  0.299290
146          2492  0.432183
142            75  0.773333

In [27]:
data['ad_prefix']=data['adid'].apply(lambda x:int(str(x)[:2]))
data.groupby('ad_prefix')['click'].agg({'mean','count'}).sort_values('mean')

            count      mean
ad_prefix
14          76235  0.105831
15         925415  0.206090

In [28]:
data['order_prefix']=data['orderid'].apply(lambda x:int(str(x)[:2]))
data.groupby('order_prefix')['click'].agg({'mean','count'}).sort_values('mean')

               count      mean
order_prefix
23            114739  0.135656
30            886911  0.206584

In [29]:
data['order_prefix']=data['orderid'].apply(lambda x:int(str(x)[:2]))
data.groupby('orderid')['click'].agg({'mean','count'}).sort_values('mean')

         count      mean
orderid
3011178     54  0.000000
3011994     37  0.000000
3011990     53  0.000000
3011988     52  0.000000
3005979      3  0.000000
3011984     28  0.000000
3011982     56  0.000000
3011180    188  0.000000
3011972     50  0.000000
3011970     39  0.000000
3006069    119  0.000000
3011964     20  0.000000
3011962     47  0.000000
3011996     33  0.000000
3011958     47  0.000000
3011954     38  0.000000
3011950     40  0.000000
3011948     60  0.000000
3011544     12  0.000000
3011944     46  0.000000
3011546     25  0.000000
3011936     35  0.000000
3011934     30  0.000000
3011928     29  0.000000
3006443     47  0.000000
3011922    139  0.000000
3011920     24  0.000000
3011956     30  0.000000
3011998     42  0.000000
3012000     29  0.000000
...        ...       ...
3012370     87  0.517241
3012046   1044  0.518199
3008057   3283  0.521170
3012712    325  0.523077
3009496    202  0.524752
2310137     55  0.527273
3012798     73  0.534247
3012700     52  0.538462
3012800     50  0.540000
3010338   1339  0.542196
3009234    138  0.543478
3011338    108  0.546296
3010302     80  0.562500
3009888     64  0.562500
3011524    420  0.590476
3011460    247  0.595142
3012368     44  0.613636
3012830     37  0.621622
3007583    105  0.628571
3008493    107  0.644860
3012626    267  0.647940
3012750   6532  0.655695
2311871    128  0.679688
2307867     93  0.688172
3010340     42  0.690476
2307871     92  0.728261
2303959     74  0.783784
3007929      1  1.000000
3012764      1  1.000000
3012728      1  1.000000

[936 rows x 2 columns]

In [30]:
data['order_prefix']=data['orderid'].apply(lambda x:int(str(x)[:4]))
data.groupby('order_prefix')['click'].agg({'mean','count'}).sort_values('mean')

               count      mean
order_prefix
2305            3055  0.016367
2302             399  0.020050
2300           21040  0.032129
2307           14062  0.056962
2308           32927  0.108847
3011          250438  0.126530
3005           31999  0.158880
2306           13432  0.180837
3012          163626  0.198330
3004            6304  0.220336
3010          124904  0.223884
2311           14255  0.238443
3006           87805  0.247742
2310            9420  0.249045
2301              27  0.259259
3008           52345  0.265087
3003            4612  0.276236
3007            6311  0.279670
3009          158567  0.289953
2312            1192  0.304530
2304            2018  0.355302
2309            2777  0.405113
2303             135  0.444444

In [31]:
from sklearn.preprocessing import LabelEncoder
data['o']=data['orderid']
data['t']=data['time']
encoder=['o','t']
col_encoder = LabelEncoder()
for feat in encoder:
    col_encoder.fit(data[feat])
    data[feat] = col_encoder.transform(data[feat])

In [32]:
data['o','t']

KeyError: ('o', 't')

In [33]:
data['o'],data['t']

(0          302
 1           77
 2          214
 3          340
 4           14
 5          120
 6          628
 7          302
 8          340
 9          631
 10         448
 11         701
 12         254
 13         340
 14          67
 15         690
 16         699
 17         335
 18         252
 19         441
 20         590
 21          38
 22         590
 23         354
 24         340
 25         421
 26         606
 27         369
 28         223
 29          76
           ...
 1001620    170
 1001621    340
 1001622    194
 1001623    328
 1001624    340
 1001625    340
 1001626    214
 1001627    631
 1001628     16
 1001629    145
 1001630     15
 1001631    143
 1001632    286
 1001633    162
 1001634    216
 1001635    223
 1001636    214
 1001637    194
 1001638    631
 1001639    194
 1001640    112
 1001641     43
 1001642    631
 1001643    328
 1001644    286
 1001645    214
 1001646     68
 1001647    244
 1001648    134
 1001649    214
 Name: o, Length: 1001650, dtype: int64, 0          128743
 1          129408
 2          129006
 3          129603
 4          129080
 5          129469
 6          129532
 7          129389
 8          129389
 9          129227
 10         128942
 11         129562
 12         129127
 13         128675
 14         129399
 15         129585
 16         128622
 17         128852
 18         129332
 19         128945
 20         129323
 21         128700
 22         129322
 23         129067
 24         128672
 25         128812
 26         129336
 27         128629
 28         129633
 29         128506
             ...
 1001620      7210
 1001621      7206
 1001622      8125
 1001623      8752
 1001624      7787
 1001625      8192
 1001626      8616
 1001627      7966
 1001628      7399
 1001629      7927
 1001630      7561
 1001631      7307
 1001632      8713
 1001633      8392
 1001634      8379
 1001635      7591
 1001636      8419
 1001637      8748
 1001638      7902
 1001639      8190
 1001640      8292
 1001641      7364
 1001642      7159
 1001643      7717
 1001644      7293
 1001645      7820
 1001646      7369
 1001647      8401
 1001648      7675
 1001649      8062
 Name: t, Length: 1001650, dtype: int64)

In [34]:
data['diff']=abs(data['o']-data['t'])

In [35]:
data['diff']

0          128441
1          129331
2          128792
3          129263
4          129066
5          129349
6          128904
7          129087
8          129049
9          128596
10         128494
11         128861
12         128873
13         128335
14         129332
15         128895
16         127923
17         128517
18         129080
19         128504
20         128733
21         128662
22         128732
23         128713
24         128332
25         128391
26         128730
27         128260
28         129410
29         128430
            ...
1001620      7040
1001621      6866
1001622      7931
1001623      8424
1001624      7447
1001625      7852
1001626      8402
1001627      7335
1001628      7383
1001629      7782
1001630      7546
1001631      7164
1001632      8427
1001633      8230
1001634      8163
1001635      7368
1001636      8205
1001637      8554
1001638      7271
1001639      7996
1001640      8180
1001641      7321
1001642      6528
1001643      7389
1001644      7007
1001645      7606
1001646      7301
1001647      8157
1001648      7541
1001649      7848
Name: diff, Length: 1001650, dtype: int64

In [36]:
data.groupby('diff')['click'].agg({'mean','count'}).sort_values('count')

        count      mean
diff
443669      1  0.000000
155325      1  1.000000
155329      1  0.000000
356702      1  1.000000
155335      1  0.000000
155340      1  0.000000
155341      1  0.000000
155323      1  0.000000
155343      1  0.000000
155348      1  0.000000
155351      1  1.000000
155352      1  0.000000
155354      1  1.000000
155356      1  0.000000
155360      1  0.000000
155347      1  0.000000
155322      1  0.000000
356706      1  0.000000
155315      1  0.000000
155257      1  0.000000
155259      1  1.000000
356753      1  0.000000
155262      1  1.000000
155272      1  0.000000
155275      1  0.000000
356736      1  1.000000
356735      1  0.000000
155287      1  0.000000
356727      1  0.000000
155297      1  0.000000
...       ...       ...
61424      24  0.041667
33959      24  0.041667
248535     24  0.000000
223242     24  0.000000
43517      24  0.041667
225752     25  0.080000
222618     25  0.000000
36988      25  0.000000
38250      25  0.000000
227112     26  0.000000
400254     26  0.076923
33884      26  0.000000
223012     26  0.038462
311275     26  0.000000
39951      26  0.038462
468        26  0.038462
407359     26  0.076923
34445      28  0.035714
61155      28  0.000000
222988     29  0.000000
311357     29  0.000000
33899      30  0.000000
37082      31  0.032258
191        32  0.000000
223244     34  0.029412
34255      34  0.000000
223277     35  0.057143
70         41  0.048780
124004     42  0.000000
276        43  0.000000

[386186 rows x 2 columns]

In [37]:
data.groupby('diff')['click'].agg({'mean','count'}).sort_values('mean')

        count  mean
diff
0           3   0.0
255583      1   0.0
255586      1   0.0
255587      1   0.0
255588      3   0.0
255589      1   0.0
255590      5   0.0
255592      1   0.0
255595      1   0.0
255596      1   0.0
255600      1   0.0
255601      1   0.0
255602      1   0.0
255604      3   0.0
255605      1   0.0
255582      2   0.0
255606      2   0.0
255608      2   0.0
255609      1   0.0
255611      1   0.0
255613      1   0.0
255614      1   0.0
255617      2   0.0
255618      3   0.0
255619      2   0.0
255620      1   0.0
255621      1   0.0
255622      1   0.0
255624      2   0.0
255625      1   0.0
...       ...   ...
215143      1   1.0
404346      3   1.0
215146      1   1.0
308265      2   1.0
308256      1   1.0
308251      1   1.0
81903       1   1.0
81910       1   1.0
404327      2   1.0
178978      1   1.0
81855       1   1.0
81853       1   1.0
308406      1   1.0
215104      1   1.0
404288      1   1.0
404289      1   1.0
404292      1   1.0
215105      1   1.0
157153      1   1.0
215305      1   1.0
178988      2   1.0
308390      2   1.0
135908      2   1.0
135907      1   1.0
308349      1   1.0
215129      2   1.0
81847       1   1.0
178981      2   1.0
404298      1   1.0
165034      1   1.0

[386186 rows x 2 columns]

In [38]:
data['dif_pre']=data['diff'].apply(lambda x:int(str(X)[:3]))
data.groupby('dif_pre')['click'].agg({'mean','count'}).sort_values('mean')

NameError: name 'X' is not defined

In [39]:
data['dif_pre']=data['diff'].apply(lambda x:int(str(x)[:3]))
data.groupby('dif_pre')['click'].agg({'mean','count'}).sort_values('mean')

         count      mean
dif_pre
0            3  0.000000
63           3  0.000000
62           3  0.000000
61           5  0.000000
60           6  0.000000
59           7  0.000000
57           4  0.000000
56          12  0.000000
66           8  0.000000
54           9  0.000000
52           4  0.000000
50           3  0.000000
49           3  0.000000
46           8  0.000000
89           4  0.000000
44           7  0.000000
43           3  0.000000
53           5  0.000000
67           4  0.000000
98           2  0.000000
69           4  0.000000
88           5  0.000000
91           1  0.000000
86           3  0.000000
92           3  0.000000
84           2  0.000000
83           5  0.000000
82           8  0.000000
93           3  0.000000
94          11  0.000000
...        ...       ...
745        234  0.264957
825        260  0.265385
974        285  0.266667
746        261  0.268199
585        257  0.268482
981        281  0.270463
563        258  0.275194
744        221  0.276018
480        234  0.277778
803        251  0.278884
581        251  0.278884
842        258  0.279070
904        261  0.279693
16           7  0.285714
51           7  0.285714
765        238  0.285714
597        223  0.295964
475        259  0.308880
64           6  0.333333
38           3  0.333333
47           6  0.333333
97           3  0.333333
87           6  0.333333
79           3  0.333333
72           3  0.333333
31           3  0.333333
55           3  0.333333
17           5  0.400000
12           2  0.500000
35           3  0.666667

[1000 rows x 2 columns]

In [40]:
data['dif_pre']=data['diff'].apply(lambda x:int(str(x)[:2]))
data.groupby('dif_pre')['click'].agg({'mean','count'}).sort_values('mean')

         count      mean
dif_pre
0            3  0.000000
1            5  0.000000
5            4  0.000000
6            5  0.000000
7            6  0.000000
8            3  0.000000
61        2760  0.071377
63        1946  0.083248
62        2063  0.088221
64        1624  0.106527
31       19666  0.107699
65        1555  0.111254
66        1452  0.123278
25       18279  0.128235
12       22252  0.135808
9            7  0.142857
38       17943  0.151703
4           13  0.153846
67        1351  0.154700
19       17935  0.160859
69        1678  0.165077
68        1494  0.167336
60        2476  0.170436
18       25402  0.175183
37       25794  0.181438
45        2721  0.181551
22       26385  0.185977
24       24383  0.187385
96        2613  0.187907
33       26946  0.188080
...        ...       ...
16       25809  0.210547
75        2489  0.210928
35       27432  0.211213
20       23416  0.212035
87        2730  0.212088
40       28467  0.212140
50        2760  0.212681
80        2578  0.213344
77        2482  0.213537
26       22913  0.215031
56        2804  0.215050
39       26110  0.215894
27       25671  0.216665
79        2338  0.216852
36       30721  0.217376
76        2482  0.218775
84        2687  0.218831
82        2572  0.220840
43       29751  0.221102
28       25662  0.221105
52        2835  0.221869
29       26004  0.222620
48        2605  0.223033
44        9709  0.223710
42       28398  0.224065
78        2390  0.224686
41       27214  0.225472
74        2383  0.234578
2            4  0.250000
3            8  0.250000

[100 rows x 2 columns]

In [41]:
data['dif_pre']=data['diff'].apply(lambda x:int(str(x)[:3]))
data.groupby('dif_pre')['click'].agg({'mean','count'}).sort_values('mean')

         count      mean
dif_pre
0            3  0.000000
63           3  0.000000
62           3  0.000000
61           5  0.000000
60           6  0.000000
59           7  0.000000
57           4  0.000000
56          12  0.000000
66           8  0.000000
54           9  0.000000
52           4  0.000000
50           3  0.000000
49           3  0.000000
46           8  0.000000
89           4  0.000000
44           7  0.000000
43           3  0.000000
53           5  0.000000
67           4  0.000000
98           2  0.000000
69           4  0.000000
88           5  0.000000
91           1  0.000000
86           3  0.000000
92           3  0.000000
84           2  0.000000
83           5  0.000000
82           8  0.000000
93           3  0.000000
94          11  0.000000
...        ...       ...
745        234  0.264957
825        260  0.265385
974        285  0.266667
746        261  0.268199
585        257  0.268482
981        281  0.270463
563        258  0.275194
744        221  0.276018
480        234  0.277778
803        251  0.278884
581        251  0.278884
842        258  0.279070
904        261  0.279693
16           7  0.285714
51           7  0.285714
765        238  0.285714
597        223  0.295964
475        259  0.308880
64           6  0.333333
38           3  0.333333
47           6  0.333333
97           3  0.333333
87           6  0.333333
79           3  0.333333
72           3  0.333333
31           3  0.333333
55           3  0.333333
17           5  0.400000
12           2  0.500000
35           3  0.666667

[1000 rows x 2 columns]

In [42]:
data['dif_pre'][255]

223

In [43]:
data.drop(['o','t'],inplace=True)

KeyError: "['o' 't'] not found in axis"

In [44]:
data.drop('o',inplace=True)

KeyError: "['o'] not found in axis"

In [45]:
del data['o']

In [46]:
del data['t']

In [47]:
data.columns.values

array(['instance_id', 'time', 'city', 'province', 'user_tags', 'carrier',
       'devtype', 'make', 'model', 'nnt', 'os', 'osv', 'os_name', 'adid',
       'advert_id', 'orderid', 'advert_industry_inner', 'campaign_id',
       'creative_id', 'creative_tp_dnf', 'app_cate_id', 'f_channel',
       'app_id', 'inner_slot_id', 'creative_type', 'creative_width',
       'creative_height', 'creative_is_jump', 'creative_is_download',
       'creative_is_js', 'creative_is_voicead', 'creative_has_deeplink',
       'app_paid', 'advert_name', 'click', 'ad_prefix', 'order_prefix',
       'diff', 'dif_pre'], dtype=object)

In [48]:
del data['order_pre_fix']

KeyError: 'order_pre_fix'

In [49]:
del data['order_prefix']

In [50]:
data['ad_prefix']

0          15
1          14
2          15
3          15
4          14
5          15
6          15
7          15
8          15
9          15
10         15
11         15
12         15
13         15
14         15
15         15
16         15
17         15
18         15
19         15
20         15
21         14
22         15
23         15
24         15
25         15
26         15
27         15
28         15
29         15
           ..
1001620    15
1001621    15
1001622    15
1001623    15
1001624    15
1001625    15
1001626    15
1001627    15
1001628    14
1001629    15
1001630    14
1001631    15
1001632    15
1001633    15
1001634    15
1001635    15
1001636    15
1001637    15
1001638    15
1001639    15
1001640    15
1001641    14
1001642    15
1001643    15
1001644    15
1001645    15
1001646    15
1001647    15
1001648    15
1001649    15
Name: ad_prefix, Length: 1001650, dtype: int64

In [51]:
del data['ad_prefix']

In [52]:
data['city'][:5]

0    137103102105100
1    137105101100100
2    137103104111100
3    137103102113100
4    137103102109100
Name: city, dtype: int64

In [53]:
data['province'][:5]

0    137103102100100
1    137105101100100
2    137103104100100
3    137103102100100
4    137103102100100
Name: province, dtype: int64

In [54]:
data['c']=data['city'].apply(lambda x:int(str(x)[9:12]))
data['p']=data['province'].apply(lambda x:int(str(x)[5:9]))

ValueError: invalid literal for int() with base 10: ''

In [55]:
def fn(x,a,b):
    if x==0:
        return -1
    else:
        return int(str(x)[a:b])
data['c']=data['city'].apply(lambda x:fn(x,9,12))
data['p']=data['province'].apply(lambda x:fn(x,5,9))

In [56]:
data['c'][:5]

0    105
1    100
2    111
3    113
4    109
Name: c, dtype: int64

In [57]:
data['p'][:5]

0    3102
1    5101
2    3104
3    3102
4    3102
Name: p, dtype: int64

In [58]:
data['c']

0          105
1          100
2          111
3          113
4          109
5          104
6          100
7          100
8          114
9          113
10         109
11         102
12         107
13         112
14         105
15         102
16         102
17         109
18         101
19         101
20         101
21         117
22         101
23         109
24         110
25         103
26         100
27         114
28         101
29         114
          ...
1001620    114
1001621    106
1001622    101
1001623    101
1001624    106
1001625    105
1001626    102
1001627    101
1001628    104
1001629    110
1001630    111
1001631    104
1001632    109
1001633    103
1001634    101
1001635    102
1001636    113
1001637    107
1001638    111
1001639    108
1001640    108
1001641     -1
1001642    101
1001643    104
1001644    106
1001645    101
1001646    106
1001647    108
1001648    109
1001649    109
Name: c, Length: 1001650, dtype: int64

In [59]:
data['p']

0          3102
1          5101
2          3104
3          3102
4          3102
5          4104
6          3101
7          1102
8          5104
9          4101
10         5102
11         4104
12         2101
13         4103
14         3102
15         4104
16         4104
17         1103
18         6101
19         6101
20         4102
21         4104
22         4103
23         3107
24         4104
25         4104
26         3101
27         4104
28         3106
29         4106
           ...
1001620    4104
1001621    3106
1001622    1105
1001623    2102
1001624    4104
1001625    1104
1001626    1103
1001627    4103
1001628    3102
1001629    4104
1001630    3102
1001631    4104
1001632    2101
1001633    4101
1001634    4102
1001635    1104
1001636    3107
1001637    4106
1001638    3103
1001639    3107
1001640    3107
1001641      -1
1001642    4101
1001643    3104
1001644    6101
1001645    4102
1001646    1103
1001647    5103
1001648    3102
1001649    4106
Name: p, Length: 1001650, dtype: int64

In [60]:
data['p_pre']=data['p'].apply(lambda x:int(str(x)[0]))
data.groupby('p_pre')['click'].agg({'mean','count'}).sort_values('mean')

ValueError: invalid literal for int() with base 10: '-'

In [61]:
def fn(x):
    if x==-1:
        return x
    else:
        return int(str(x)[0]
data['p_pre']=data['p'].apply(lambda x:fn(x))
data.groupby('p_pre')['click'].agg({'mean','count'}).sort_values('mean')

SyntaxError: invalid syntax (<ipython-input-61-08c1a3ef47ba>, line 6)

In [62]:
def fn(x):
    if x==-1:
        return x
    else:
        return int(str(x)[0])
data['p_pre']=data['p'].apply(lambda x:fn(x))
data.groupby('p_pre')['click'].agg({'mean','count'}).sort_values('mean')

        count      mean
p_pre
 7        516  0.087209
 4     293187  0.172757
-1      17640  0.191383
 3     287477  0.199254
 1     142690  0.211458
 6      63526  0.213062
 5     110931  0.216603
 2      85683  0.229906

In [63]:
def fn(x):
    if x==-1:
        return x
    else:
        return int(str(x)[-1])
data['p_pre']=data['p'].apply(lambda x:fn(x))
data.groupby('p_pre')['click'].agg({'mean','count'}).sort_values('mean')

        count      mean
p_pre
 4     228964  0.172464
 6      63413  0.176178
-1      17640  0.191383
 5      62214  0.198975
 3     171727  0.201104
 1     176858  0.210429
 2     204023  0.212829
 7      76811  0.223913

In [64]:
data.groupby('p')['click'].agg({'mean','count'}).sort_values('mean')

        count      mean
p
 7101     164  0.054878
 7102     287  0.094077
 7103      65  0.138462
 4104  118906  0.141717
 1101   15183  0.169071
 4106   37157  0.173776
 3103   34614  0.175623
 3101   12691  0.177527
 3104   42765  0.178440
 3106   26256  0.179578
 4102   34575  0.182936
 4105    3619  0.183476
 3105   28162  0.184113
-1      17640  0.191383
 4103   35907  0.197872
 5104   24931  0.198789
 1103   57933  0.199075
 6101   31789  0.200038
 5103   14267  0.205930
 2102   25242  0.206838
 5105     585  0.208547
 4101   63023  0.210209
 6105    9551  0.210344
 3102   66178  0.214860
 1105   20297  0.216732
 5102   51849  0.223302
 3107   76811  0.223913
 5101   19299  0.229753
 6103    3209  0.230290
 6102   14370  0.232011
 1102   11522  0.235897
 1104   37755  0.237214
 6104    4607  0.237465
 2103   25732  0.238303
 2101   34709  0.240456

In [65]:
data.groupby('c')['click'].agg({'mean','count'}).sort_values('mean')

       count      mean
c
 119    3207  0.147802
 118    7344  0.164216
 121    4507  0.165298
 116   10795  0.179435
 120    4484  0.179750
 115   15469  0.187342
 117   22895  0.189561
-1     17640  0.191383
 114   19034  0.191552
 111   42449  0.191760
 112   25631  0.193594
 102  101251  0.195643
 106   54494  0.196334
 113   27898  0.196537
 107   53283  0.197418
 110   39884  0.198751
 104   52420  0.199180
 108   47446  0.200375
 100   60242  0.202384
 105   58119  0.202412
 101  230841  0.203339
 103   54573  0.204772
 109   47744  0.205303

In [66]:
def fn(x):
    if x==-1:
        return x
    else:
        return int(str(x)[1:])
data['c_pre']=data['c'].apply(lambda x:fn(x))
data.groupby('c_pre')['click'].agg({'mean','count'}).sort_values('mean')

        count      mean
c_pre
 19      3207  0.147802
 18      7344  0.164216
 21      4507  0.165298
 16     10795  0.179435
 20      4484  0.179750
 15     15469  0.187342
 17     22895  0.189561
-1      17640  0.191383
 14     19034  0.191552
 11     42449  0.191760
 12     25631  0.193594
 2     101251  0.195643
 6      54494  0.196334
 13     27898  0.196537
 7      53283  0.197418
 10     39884  0.198751
 4      52420  0.199180
 8      47446  0.200375
 0      60242  0.202384
 5      58119  0.202412
 1     230841  0.203339
 3      54573  0.204772
 9      47744  0.205303

In [67]:
data.groupby('city')['click'].agg({'mean','count'}).sort_values('mean')

                 count      mean
city
137107101100100    164  0.054878
137107102100100    287  0.094077
137104104115100   1997  0.098147
137104104113100   1835  0.100272
137104104102100  25514  0.107784
137104104107100   3259  0.113532
137103107100100     60  0.116667
137104104105100   1998  0.118619
137104104114100   2252  0.121226
137104104110100   2801  0.122456
137104104119100   2358  0.123834
137104104116100   2270  0.125110
137103103101100   3373  0.131337
137107103100100     65  0.138462
137104106106100    819  0.140415
137104104106100   7030  0.140967
137104104121100   3106  0.142305
137104104104100   3846  0.143526
137104104103100   4001  0.143964
137104104109100   3659  0.146215
137104104108100   4844  0.146986
137103104107100   2659  0.147048
137104104111100   5261  0.147500
137106103107100     61  0.147541
137106103106100     54  0.148148
137104104120100   3065  0.149103
137104106105100   1302  0.149770
137103103107100   3060  0.151634
137104104118100   6136  0.152216
137103106106100   1184  0.153716
...                ...       ...
137101105107100   1668  0.245204
137102103103100   2422  0.245252
137105102120100   1419  0.245948
137106104102100    329  0.246201
137102101111100   1022  0.246575
137102101108100   1443  0.246708
137106103105100    409  0.246944
137102101113100   2081  0.246997
137102103109100    558  0.247312
137101104106100   2293  0.248147
137106102107100    975  0.248205
137102102109100   1725  0.249855
137106102104100    512  0.250000
137103107102100  12685  0.250769
137101104109100   2180  0.251376
137101104103100   1786  0.251960
137102101112100   1508  0.251989
137106103104100    115  0.252174
137102103105100   1581  0.252372
137102101109100   1743  0.252438
137102101114100   1817  0.253165
137102103113100    288  0.253472
137102103111100    878  0.253986
137102101102100   6130  0.254323
137106105114100    287  0.254355
137101104102100   5276  0.256255
137102103102100   2973  0.261016
137102103107100   1029  0.266278
137102102106100    776  0.270619
137102102108100   1429  0.273618

[333 rows x 2 columns]

In [68]:
data['model']

0                            HUAWEI-CAZ-AL10
1                               Redmi Note 4
2                                  OPPO+R11s
3                                   OPPO A57
4                                   iPhone 7
5                                       MI 6
6                              iPhone 7 Plus
7                            HUAWEI-NXT-AL10
8                                   OPPO R9s
9                                 vivo+Y13iL
10                               vivo Xplay6
11                                  OPPO R9s
12                                      x600
13                                  vivo X9s
14                                 vivo Y19t
15                                    MI%206
16                                 OPPO R11s
17                                 vivo Y79A
18                                  OPPO+A33
19                               MI NOTE LTE
20                                  iPhone 6
21         iPhone 6 Plus (A1522/A1524/A1593)
22                             iPhone 6 Plus
23                                 iPhone7,2
24                                 OPPO R11s
25                                 iPhone7,1
26                                  iPhone 7
27                                  HWI-AL00
28                                 OPPO A57t
29                                 OPPO A59s
                         ...
1001620                             DIG-AL00
1001621                         Lenovo X3c50
1001622                                  R7c
1001623                                 MI 6
1001624                            OPPO A59m
1001625                             FLA-AL10
1001626                              m2+note
1001627                             OPPO+A57
1001628                           vivo%20Y31
1001629                                  M5s
1001630                             NEM-UL10
1001631                            iPhone9,2
1001632                             vivo+Y55
1001633                           SUGAR%20F7
1001634                             PLK-AL10
1001635                             OPPO A33
1001636                                M611D
1001637                             vivo Y51
1001638                             vivo+Y27
1001639                                GO C2
1001640                              M6+Note
1001641                            iPhone 6s
1001642                            vivo+Y75A
1001643                             DIG-TL10
1001644                            OPPO+A37m
1001645                             BLN-AL40
1001646                           vivo X9s L
1001647                             vivo Y79
1001648                             EML-AL00
1001649                             KIW-UL00
Name: model, Length: 1001650, dtype: object

In [69]:
data.groupby('model')['click'].agg({'mean','count'}).sort_values('mean')

                      count  mean
model
%25221605-A01%2522        1   0.0
SMARTISAN                 1   0.0
SMMS8L2G                  1   0.0
SMMX8H3G                  2   0.0
SM_W2015                  1   0.0
SO-03F                    1   0.0
SOAP%20R11                2   0.0
SOAP%25252525252BR11      1   0.0
SOAP-R11                  1   0.0
SOP-E8                    1   0.0
SOP-G929                  1   0.0
SOP-H7                    3   0.0
SOP-I5                    1   0.0
SOP-M5                    1   0.0
SOP-M6                    2   0.0
SOP-M60                   2   0.0
SOP-M8                    3   0.0
SOP-M9                   15   0.0
SMARTEGO S1               2   0.0
SOP-N2                   11   0.0
SM901                    19   0.0
SM-T805C                  6   0.0
SM-T350                   2   0.0
SM-T375S                  1   0.0
SM-T378L                  1   0.0
SM-T385C                  1   0.0
SM-T520                   2   0.0
SM-T530                   3   0.0
SM-T531                   1   0.0
SM-T535                   1   0.0
...                     ...   ...
Bird                      1   1.0
E150                      1   1.0
vivo-S7i(t)               1   1.0
MLLED_M3                  1   1.0
MM1103                    1   1.0
MN4A2ZP/A                 1   1.0
Hisense-E71-T             1   1.0
XIAOMI                    1   1.0
SMART-6S                  1   1.0
Hisense-E75T              1   1.0
HUAWEI+P7-L05             1   1.0
DUK                       1   1.0
XT1254                    1   1.0
XT1585                    1   1.0
Best+sonny+LT511          1   1.0
Y-518                     2   1.0
Lenovo+A338t              1   1.0
KXT-M1                    1   1.0
HUAWEI+Y625-U32           1   1.0
gionee f6l                1   1.0
vivo-1721                 1   1.0
MLLED+L1                  1   1.0
SM-T2558                  1   1.0
MLLED-L9                  1   1.0
Lenovo+2+A8-50F           1   1.0
XYT                       1   1.0
K1plus                    1   1.0
E708 3G                   1   1.0
Lenovo+A3000-H            1   1.0
HLJCW6                    1   1.0

[14053 rows x 2 columns]

In [70]:
data['make']

0                     HUAWEI
1                     Xiaomi
2                       OPPO
3                        NaN
4                      Apple
5          Xiaomi,MI 6,sagit
6                      Apple
7                     HUAWEI
8                        NaN
9                       vivo
10                      vivo
11                      OPPO
12                      x600
13                       NaN
14                       BBK
15                    Xiaomi
16                      OPPO
17                 vivo Y79A
18                      OPPO
19                    Xiaomi
20                     Apple
21                     Apple
22                     Apple
23                     Apple
24                       NaN
25                     Apple
26                     Apple
27                    HUAWEI
28                      OPPO
29                 OPPO A59s
                 ...
1001620             DIG-AL00
1001621                  NaN
1001622                 OPPO
1001623                 MI 6
1001624                  NaN
1001625                  NaN
1001626                Meizu
1001627                 OPPO
1001628                 vivo
1001629                Meizu
1001630               HUAWEI
1001631                Apple
1001632                 vivo
1001633                SUGAR
1001634               HUAWEI
1001635                 OPPO
1001636                Meizu
1001637                 vivo
1001638                  BBK
1001639            Qingcheng
1001640                Meizu
1001641                Apple
1001642                 vivo
1001643             DIG-TL10
1001644                 OPPO
1001645               HUAWEI
1001646           vivo X9s L
1001647                 vivo
1001648               HUAWEI
1001649               HUAWEI
Name: make, Length: 1001650, dtype: object

In [71]:
data.groupby('make')['click'].agg({'mean','count'})

                             count      mean
make
%25221605-A01%2522               1  0.000000
%25221707-A01%2522               1  0.000000
%25221807-A01%2522               1  0.000000
%2522ALP-AL00%2522               1  1.000000
%2522ANE-AL00%2522               1  0.000000
%2522BAC-TL00%2522               1  0.000000
%2522BKL-AL20%2522               1  0.000000
%2522BLA-TL00%2522               1  0.000000
%2522BLN-AL10%2522               2  0.000000
%2522BLN-AL40%2522               2  0.000000
%2522BND-AL10%2522               2  0.000000
%2522C6802%2522                  1  0.000000
%2522CHM-TL00H%2522              1  0.000000
%2522CLT-AL01%2522               2  0.000000
%2522COL-AL10%2522               2  0.000000
%2522CUN-TL00%2522               1  0.000000
%2522DUK-AL20%2522               1  0.000000
%2522EDI-AL10%2522               1  0.000000
%2522EML-AL00%2522               1  0.000000
%2522EVA-AL10%2522               1  0.000000
%2522F5%2522                     1  0.000000
%2522FRD-AL10%2522               1  0.000000
%2522HUAWEI%2BCAZ-AL10%2522      1  0.000000
%2522HUAWEI%2BMLA-AL10%2522      1  0.000000
%2522HUAWEI%2BMT7-CL00%2522      1  0.000000
%2522HUAWEI%2BRIO-UL00%2522      1  0.000000
%2522HWI-AL00%2522               2  0.000000
%2522JMM-AL00%2522               1  0.000000
%2522LLD-AL00%2522               1  0.000000
%2522LON-AL00%2522               1  0.000000
...                            ...       ...
yeechui                         47  0.191489
yifengzhanye                     6  0.166667
yulong                           3  0.000000
yunzhi                           2  0.000000
zh-c                             6  0.000000
zhongxinbaihe                   19  0.105263
zte                            136  0.147059
zuk                              2  0.000000
为沃                               1  0.000000
全网通                              1  0.000000
其它                               2  0.500000
华为                               2  0.000000
厘米                               2  0.500000
天语                              12  0.250000
奥特曼                              1  1.000000
宏润                               2  0.000000
我不会哄人.                           1  0.000000
摩托无线                             1  0.000000
楹﹀姩鍑哄搧                           1  0.000000
清华同方                             1  1.000000
潇爸的荣耀                            1  0.000000
红辣椒                             12  0.166667
苹果六                              1  0.000000
葫芦侠                              1  0.000000
词歌                               1  0.000000
跟李白喝酒给的                          1  0.000000
迪美                               1  0.000000
迷你世界                             1  0.000000
麦动出品                             2  0.000000
麦柴                               1  0.000000

[3140 rows x 2 columns]

In [72]:
data.groupby('make')['click'].agg({'mean','count'}).sort_values('mean')

                        count  mean
make
%25221605-A01%2522          1   0.0
Philips X596                1   0.0
Philips X598                1   0.0
Philips X818                1   0.0
Plus                        1   0.0
Plus One Japan Limited      1   0.0
Poulo                       1   0.0
Philips V800                1   0.0
Pro                         3   0.0
Q7E                         2   0.0
Q8866                       1   0.0
Q888                        1   0.0
Q9                          1   0.0
Q988                        3   0.0
Q9910                       2   0.0
Q3                          2   0.0
Q999                        3   0.0
Philips S616                1   0.0
Pantech                     1   0.0
PLK-CL00                    7   0.0
PLK-UL00                    6   0.0
PLUS                        1   0.0
PRO                        12   0.0
PRO 6                      10   0.0
PRO 6 Plus                  5   0.0
Phicomm                     1   0.0
PRO%205                     3   0.0
PRO6                        1   0.0
PRO6Plus                    2   0.0
PROTRULY V10S               1   0.0
...                       ...   ...
SHT-AL09                    1   1.0
V6                          1   1.0
Lovme-T25                   1   1.0
virgo                       2   1.0
RIM                         1   1.0
SMART-6S                    1   1.0
HUAWEI eH880                1   1.0
SM-W2014                    1   1.0
G13                         1   1.0
iToolsAVM_T0017586S         1   1.0
MANGGUO                     1   1.0
W3AT61                      1   1.0
W1T                         1   1.0
G8342                       1   1.0
ivvi i3-01                  1   1.0
Volte+4G                    1   1.0
ASUS_Z01HDA                 1   1.0
ASUS_X00GD                  1   1.0
GEMRY                       1   1.0
Heexon                      1   1.0
SM-J3308                    1   1.0
R9 Plus                     1   1.0
Heeyu                       2   1.0
msm8953                     1   1.0
oppoa57                     1   1.0
Hisense F22M                1   1.0
8848 M4                     1   1.0
SM-G930K                    1   1.0
BM Plus Q6                  1   1.0
M8_                         1   1.0

[3140 rows x 2 columns]

In [73]:
data.columns.values

array(['instance_id', 'time', 'city', 'province', 'user_tags', 'carrier',
       'devtype', 'make', 'model', 'nnt', 'os', 'osv', 'os_name', 'adid',
       'advert_id', 'orderid', 'advert_industry_inner', 'campaign_id',
       'creative_id', 'creative_tp_dnf', 'app_cate_id', 'f_channel',
       'app_id', 'inner_slot_id', 'creative_type', 'creative_width',
       'creative_height', 'creative_is_jump', 'creative_is_download',
       'creative_is_js', 'creative_is_voicead', 'creative_has_deeplink',
       'app_paid', 'advert_name', 'click', 'diff', 'dif_pre', 'c', 'p',
       'p_pre', 'c_pre'], dtype=object)

In [74]:
del data['c']
del data['p']
del data['p_pre']
del data['c_pre']

In [75]:
data.columns.values

array(['instance_id', 'time', 'city', 'province', 'user_tags', 'carrier',
       'devtype', 'make', 'model', 'nnt', 'os', 'osv', 'os_name', 'adid',
       'advert_id', 'orderid', 'advert_industry_inner', 'campaign_id',
       'creative_id', 'creative_tp_dnf', 'app_cate_id', 'f_channel',
       'app_id', 'inner_slot_id', 'creative_type', 'creative_width',
       'creative_height', 'creative_is_jump', 'creative_is_download',
       'creative_is_js', 'creative_is_voicead', 'creative_has_deeplink',
       'app_paid', 'advert_name', 'click', 'diff', 'dif_pre'],
      dtype=object)

In [76]:
del data['app_paid']
del data['creative_is_js']

In [77]:
data['creative_is_voicead'].unique()

array([False])

In [78]:
del data['creative_is_js']

KeyError: 'creative_is_js'

In [79]:
del data['creative_is_voicead']

In [80]:
data.columns.values

array(['instance_id', 'time', 'city', 'province', 'user_tags', 'carrier',
       'devtype', 'make', 'model', 'nnt', 'os', 'osv', 'os_name', 'adid',
       'advert_id', 'orderid', 'advert_industry_inner', 'campaign_id',
       'creative_id', 'creative_tp_dnf', 'app_cate_id', 'f_channel',
       'app_id', 'inner_slot_id', 'creative_type', 'creative_width',
       'creative_height', 'creative_is_jump', 'creative_is_download',
       'creative_has_deeplink', 'advert_name', 'click', 'diff', 'dif_pre'],
      dtype=object)

In [81]:
data['province'].nunique()

35

In [82]:
data.groupby('province')['click'].agg({'count','mean'})

                  count      mean
province
0                 17640  0.191383
137101101100100   15183  0.169071
137101102100100   11522  0.235897
137101103100100   57933  0.199075
137101104100100   37755  0.237214
137101105100100   20297  0.216732
137102101100100   34709  0.240456
137102102100100   25242  0.206838
137102103100100   25732  0.238303
137103101100100   12691  0.177527
137103102100100   66178  0.214860
137103103100100   34614  0.175623
137103104100100   42765  0.178440
137103105100100   28162  0.184113
137103106100100   26256  0.179578
137103107100100   76811  0.223913
137104101100100   63023  0.210209
137104102100100   34575  0.182936
137104103100100   35907  0.197872
137104104100100  118906  0.141717
137104105100100    3619  0.183476
137104106100100   37157  0.173776
137105101100100   19299  0.229753
137105102100100   51849  0.223302
137105103100100   14267  0.205930
137105104100100   24931  0.198789
137105105100100     585  0.208547
137106101100100   31789  0.200038
137106102100100   14370  0.232011
137106103100100    3209  0.230290
137106104100100    4607  0.237465
137106105100100    9551  0.210344
137107101100100     164  0.054878
137107102100100     287  0.094077
137107103100100      65  0.138462

In [83]:
for fea in data.columns.values:
    print(fea,data[fea].nunique())

instance_id 1001650
time 443670
city 333
province 35
user_tags 464200
carrier 4
devtype 4
make 3140
model 14053
nnt 6
os 3
osv 300
os_name 3
adid 2079
advert_id 38
orderid 936
advert_industry_inner 24
campaign_id 64
creative_id 862
creative_tp_dnf 40
app_cate_id 22
f_channel 73
app_id 438
inner_slot_id 1169
creative_type 5
creative_width 20
creative_height 13
creative_is_jump 2
creative_is_download 2
creative_has_deeplink 2
advert_name 34
click 2
diff 386186
dif_pre 1000

In [84]:
data['time'].sort_values()

874185    2190038403
932291    2190038408
731       2190038409
874289    2190038409
26991     2190038409
499694    2190038409
336305    2190038409
26967     2190038409
336310    2190038409
336021    2190038409
932011    2190038409
363965    2190038409
927       2190038409
676       2190038409
413402    2190038409
932190    2190038409
648947    2190038409
310555    2190038409
336556    2190038409
363766    2190038409
467966    2190038409
29784     2190038410
413491    2190038410
848987    2190038410
75911     2190038410
413598    2190038410
646       2190038410
499693    2190038410
957569    2190038410
957484    2190038410
             ...
268066    2190643059
894089    2190643059
146324    2190643062
147562    2190643063
776997    2190643064
586889    2190643065
21773     2190643066
638893    2190643067
207241    2190643068
268155    2190643069
268133    2190643069
894152    2190643069
21715     2190643070
147618    2190643071
638888    2190643071
638908    2190643072
664971    2190643072
665015    2190643073
400740    2190643073
894047    2190643073
250194    2190643074
776855    2190643074
664616    2190643076
259665    2190643076
147532    2190643077
586948    2190643078
664589    2190643078
259656    2190643078
259689    2190643078
638857    2190643079
Name: time, Length: 1001650, dtype: int64

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
train=pd.read_csv('/users/lisa/Downloads/round1_iflyad_train.txt',sep='\t')
test=pd.read_csv('/users/lisa/Downloads/round1_iflyad_test_feature.txt',sep='\t')
data=pd.concat([train,test],axis=0)

FileNotFoundError: File b'/users/lisa/Downloads/round1_iflyad_train.txt' does not exist

In [3]:
train=pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/round1_iflyad_train.txt',sep='\t')
test=pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/round1_iflyad_test_feature.txt',sep='\t')
data=pd.concat([train,test],axis=0)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

In [4]:
data['adid'].value_counts()

1577888    44709
1537089    43022
1549584    40054
1547112    36799
1574388    36466
1560128    36246
1577884    31388
1546968    26019
1579122    24001
1553872    22160
1549532    19311
1547080    18040
1552874    17238
1548194    14994
1553390    12458
1456557    12341
1453927    12282
1487765    11866
1573138     9879
1517657     9646
1517659     9533
1403645     9359
1579808     8687
1585512     7988
1585436     7113
1575800     6681
1574760     6517
1585508     6142
1518579     6114
1548446     6106
           ...
1581228        1
1578056        1
1586146        1
1579180        1
1585334        1
1578162        1
1579360        1
1579190        1
1581042        1
1581200        1
1585666        1
1578640        1
1584260        1
1580674        1
1452871        1
1577094        1
1584770        1
1585148        1
1577830        1
1518099        1
1586314        1
1581040        1
1575712        1
1577612        1
1580684        1
1581204        1
1558888        1
1576592        1
1577104        1
1579626        1
Name: adid, Length: 2113, dtype: int64

In [5]:
ad_count=data['adid'].value_counts()
ad_count.columns.values

AttributeError: 'Series' object has no attribute 'columns'

In [6]:
ad_count=data['adid'].value_counts()
ad_count[ad_count>20]

1577888    44709
1537089    43022
1549584    40054
1547112    36799
1574388    36466
1560128    36246
1577884    31388
1546968    26019
1579122    24001
1553872    22160
1549532    19311
1547080    18040
1552874    17238
1548194    14994
1553390    12458
1456557    12341
1453927    12282
1487765    11866
1573138     9879
1517657     9646
1517659     9533
1403645     9359
1579808     8687
1585512     7988
1585436     7113
1575800     6681
1574760     6517
1585508     6142
1518579     6114
1548446     6106
           ...
1585962       22
1577044       22
1580904       22
1580914       22
1584734       22
1549474       22
1576322       22
1585276       22
1577408       22
1580340       22
1559028       22
1576296       22
1576282       22
1580128       21
1452895       21
1584352       21
1580638       21
1576300       21
1576356       21
1579648       21
1576368       21
1579652       21
1577154       21
1585980       21
1558572       21
1580918       21
1585400       21
1581460       21
1576808       21
1558856       21
Name: adid, Length: 1247, dtype: int64

In [7]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue

In [8]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].count_values,data[col].count_values[data[col].count_values>20])

AttributeError: 'Series' object has no attribute 'count_values'

In [9]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].value_counts,data[col].count_values[data[col].value_counts>20])

AttributeError: 'Series' object has no attribute 'count_values'

In [10]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].value_counts,data[col].value_counts[data[col].value_counts>20])

TypeError: '>' not supported between instances of 'method' and 'int'

In [11]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].value_counts(),data[col].value_counts()[data[col].value_counts()>20])

adid 1577888    44709
1537089    43022
1549584    40054
1547112    36799
1574388    36466
1560128    36246
1577884    31388
1546968    26019
1579122    24001
1553872    22160
1549532    19311
1547080    18040
1552874    17238
1548194    14994
1553390    12458
1456557    12341
1453927    12282
1487765    11866
1573138     9879
1517657     9646
1517659     9533
1403645     9359
1579808     8687
1585512     7988
1585436     7113
1575800     6681
1574760     6517
1585508     6142
1518579     6114
1548446     6106
           ...
1581228        1
1578056        1
1586146        1
1579180        1
1585334        1
1578162        1
1579360        1
1579190        1
1581042        1
1581200        1
1585666        1
1578640        1
1584260        1
1580674        1
1452871        1
1577094        1
1584770        1
1585148        1
1577830        1
1518099        1
1586314        1
1581040        1
1575712        1
1577612        1
1580684        1
1581204        1
1558888        1
1576592        1
1577104        1
1579626        1
Name: adid, Length: 2113, dtype: int64 1577888    44709
1537089    43022
1549584    40054
1547112    36799
1574388    36466
1560128    36246
1577884    31388
1546968    26019
1579122    24001
1553872    22160
1549532    19311
1547080    18040
1552874    17238
1548194    14994
1553390    12458
1456557    12341
1453927    12282
1487765    11866
1573138     9879
1517657     9646
1517659     9533
1403645     9359
1579808     8687
1585512     7988
1585436     7113
1575800     6681
1574760     6517
1585508     6142
1518579     6114
1548446     6106
           ...
1585962       22
1577044       22
1580904       22
1580914       22
1584734       22
1549474       22
1576322       22
1585276       22
1577408       22
1580340       22
1559028       22
1576296       22
1576282       22
1580128       21
1452895       21
1584352       21
1580638       21
1576300       21
1576356       21
1579648       21
1576368       21
1579652       21
1577154       21
1585980       21
1558572       21
1580918       21
1585400       21
1581460       21
1576808       21
1558856       21
Name: adid, Length: 1247, dtype: int64
advert_id 230000063    429941
230000065    151014
230001025    135349
230001710     76097
230001696     61518
230000191     47655
230000971     28627
230000245     19208
230001547     17522
230000833     16223
230001694     13905
230001620      7196
230001722      5958
230001690      4228
230000331      3482
230001587      3351
230000413      3047
230001636      2649
230000423      2485
230001718      2114
230000469      1540
230001545      1340
230001449      1306
230001489      1221
230000179      1164
230000243       975
230001728       735
230001672       654
230001714       358
230001650       194
230001632       133
230001505       123
230000843       121
230001589        98
230001716        86
230001630        25
230000439        20
230000037        11
230001595         1
Name: advert_id, dtype: int64 230000063    429941
230000065    151014
230001025    135349
230001710     76097
230001696     61518
230000191     47655
230000971     28627
230000245     19208
230001547     17522
230000833     16223
230001694     13905
230001620      7196
230001722      5958
230001690      4228
230000331      3482
230001587      3351
230000413      3047
230001636      2649
230000423      2485
230001718      2114
230000469      1540
230001545      1340
230001449      1306
230001489      1221
230000179      1164
230000243       975
230001728       735
230001672       654
230001714       358
230001650       194
230001632       133
230001505       123
230000843       121
230001589        98
230001716        86
230001630        25
Name: advert_id, dtype: int64
advert_industry_inner 102400_102401    429941
101700_101704    360021
101900_101902     76097
101000_101002     61518
16_100509         28627
100300_100301     19208
4_100206          16223
16_100508         13905
101700_101799     10547
100600_100607      5958
101700_101711      4228
101100_101101      3482
4_100201           2670
101800_101812      2649
101500_101515      1638
100300_100307      1340
100600_100602      1221
101400_101404       735
4_100299            663
100600_100603       654
101000_101030       194
101800_101819       123
9_100110             20
9_100103             11
100400_100408         1
Name: advert_industry_inner, dtype: int64 102400_102401    429941
101700_101704    360021
101900_101902     76097
101000_101002     61518
16_100509         28627
100300_100301     19208
4_100206          16223
16_100508         13905
101700_101799     10547
100600_100607      5958
101700_101711      4228
101100_101101      3482
4_100201           2670
101800_101812      2649
101500_101515      1638
100300_100307      1340
100600_100602      1221
101400_101404       735
4_100299            663
100600_100603       654
101000_101030       194
101800_101819       123
Name: advert_industry_inner, dtype: int64
advert_name B4734117F35EE97F    429941
E257895F74792E81    151014
50822F8310CAE01D    135349
0A421D7B11EABFC5     76097
310405E93895BD58     61518
42A4CB9035B7F50E     50304
D54E631F07CA4751     28627
862FF2E9B0AD4C14     20451
68C5520FFBC5FC19     19208
37E91828E6FB695A     17522
5C84C3D2EBBB9D7C     13905
CC4602621BE800EA      8502
650A238639F48A0B      5958
F4D19C7CFB0F2D6B      3482
764D8F955C93EFF9      3405
1D3BD714403AE0FF      3351
3C2954F0FE3A8E9F      2485
35DFCB8E0D538F3A      2114
B9187893173D0922      1540
1F5BCCF2B036B218      1340
CD415FAC90F3915E      1221
6EB2087117B8DF79      1164
A44A5764011BFA5F       975
209193C1E007C91D       735
69527F99B1CB5EFE       654
CF3B238BB574CEAE       194
FE1D52275387B718       133
982890C77A4DAC79       123
15C3B9BD82DF9C8A       121
75DA90F776DED5E0        98
9E861D89C09B91A8        86
793E4A96145F206B        25
D9219D20A3A6DBE4        20
B3BF7B07B2D06440        11
14383C34DF21FC32         1
Name: advert_name, dtype: int64 B4734117F35EE97F    429941
E257895F74792E81    151014
50822F8310CAE01D    135349
0A421D7B11EABFC5     76097
310405E93895BD58     61518
42A4CB9035B7F50E     50304
D54E631F07CA4751     28627
862FF2E9B0AD4C14     20451
68C5520FFBC5FC19     19208
37E91828E6FB695A     17522
5C84C3D2EBBB9D7C     13905
CC4602621BE800EA      8502
650A238639F48A0B      5958
F4D19C7CFB0F2D6B      3482
764D8F955C93EFF9      3405
1D3BD714403AE0FF      3351
3C2954F0FE3A8E9F      2485
35DFCB8E0D538F3A      2114
B9187893173D0922      1540
1F5BCCF2B036B218      1340
CD415FAC90F3915E      1221
6EB2087117B8DF79      1164
A44A5764011BFA5F       975
209193C1E007C91D       735
69527F99B1CB5EFE       654
CF3B238BB574CEAE       194
FE1D52275387B718       133
982890C77A4DAC79       123
15C3B9BD82DF9C8A       121
75DA90F776DED5E0        98
9E861D89C09B91A8        86
793E4A96145F206B        25
Name: advert_name, dtype: int64
app_cate_id 100.0    334324
107.0    303758
108.0    182894
111.0     70415
103.0     68325
101.0     14630
109.0     11886
102.0     11871
105.0      9417
117.0      5662
119.0      5567
200.0      4870
110.0      4687
203.0      3684
106.0      2220
121.0      1878
115.0      1469
120.0      1446
104.0       298
113.0        42
118.0        29
116.0         4
Name: app_cate_id, dtype: int64 100.0    334324
107.0    303758
108.0    182894
111.0     70415
103.0     68325
101.0     14630
109.0     11886
102.0     11871
105.0      9417
117.0      5662
119.0      5567
200.0      4870
110.0      4687
203.0      3684
106.0      2220
121.0      1878
115.0      1469
120.0      1446
104.0       298
113.0        42
118.0        29
Name: app_cate_id, dtype: int64
app_id 2089397.0    207032
2089229.0    201791
2071234.0     79778
1080008.0     51102
1030051.0     44926
1110016.0     42217
1100001.0     36847
2070969.0     31869
2071003.0     28175
2071133.0     24656
1000049.0     18101
2071279.0     13951
2090600.0     13028
2070079.0     10365
2070463.0      9811
2071103.0      9729
1080001.0      8792
2070609.0      8593
2089363.0      8548
2070587.0      8099
2082869.0      7879
2071005.0      7819
2080995.0      7261
2071229.0      6991
2089303.0      6901
2070263.0      6248
2081009.0      6231
2089441.0      5819
2089365.0      5129
2071121.0      5059
              ...
2089919.0         1
2089825.0         1
2070723.0         1
2086701.0         1
2089845.0         1
2089849.0         1
2089855.0         1
2089183.0         1
2090019.0         1
2089769.0         1
2078685.0         1
2090041.0         1
2090115.0         1
2090109.0         1
2070355.0         1
2070361.0         1
2089555.0         1
2090105.0         1
2077731.0         1
2090097.0         1
2090071.0         1
2090061.0         1
2089863.0         1
2077337.0         1
2088077.0         1
2089741.0         1
2089753.0         1
2090047.0         1
2090045.0         1
2077385.0         1
Name: app_id, Length: 439, dtype: int64 2089397.0    207032
2089229.0    201791
2071234.0     79778
1080008.0     51102
1030051.0     44926
1110016.0     42217
1100001.0     36847
2070969.0     31869
2071003.0     28175
2071133.0     24656
1000049.0     18101
2071279.0     13951
2090600.0     13028
2070079.0     10365
2070463.0      9811
2071103.0      9729
1080001.0      8792
2070609.0      8593
2089363.0      8548
2070587.0      8099
2082869.0      7879
2071005.0      7819
2080995.0      7261
2071229.0      6991
2089303.0      6901
2070263.0      6248
2081009.0      6231
2089441.0      5819
2089365.0      5129
2071121.0      5059
              ...
2089163.0        40
2089587.0        40
2089631.0        38
2089621.0        33
2089151.0        32
2070301.0        32
2070781.0        31
2087813.0        30
2089211.0        30
2089607.0        29
2070559.0        29
2090634.0        28
2070533.0        28
2090590.0        28
2090580.0        27
2070747.0        26
2071185.0        26
2089633.0        26
2070611.0        26
2089353.0        26
2090602.0        25
2089671.0        24
2089589.0        24
2070219.0        23
2089639.0        22
2086989.0        22
2089411.0        21
2070305.0        21
2071161.0        21
2089219.0        21
Name: app_id, Length: 212, dtype: int64
app_paid False    1041674
Name: app_paid, dtype: int64 False    1041674
Name: app_paid, dtype: int64
campaign_id 1000023    429744
1000021    151014
1001979    135349
1003544     76097
1003456     61518
1002549     28627
1001793     20551
1002835     16223
1003348     15342
1003211     14522
1003598      9483
1003562      8421
1003600      5958
1003516      5533
1003564      5484
1003610      5087
1003608      4638
1003546      4228
1003440      3817
1003434      3705
1003328      3491
1003624      3351
1000509      3047
1003197      3000
1003514      2649
1000493      2485
1003582      2114
1003153      1991
1003155      1491
1003259      1340
            ...
1003632       735
1003578       693
1003518       569
1003626       528
1000527       420
1003596       358
1003536       222
1001025       197
1003374       194
1003538       189
1003602       153
1003364       133
1003640       123
1002581       121
1003594        98
1003590        80
1003616        42
1001053        28
1003340        25
1003628        23
1003416        20
1003402        11
1000887        11
1003528         9
1003654         7
1003660         6
1003650         5
1003656         4
1003622         1
1003646         1
Name: campaign_id, Length: 66, dtype: int64 1000023    429744
1000021    151014
1001979    135349
1003544     76097
1003456     61518
1002549     28627
1001793     20551
1002835     16223
1003348     15342
1003211     14522
1003598      9483
1003562      8421
1003600      5958
1003516      5533
1003564      5484
1003610      5087
1003608      4638
1003546      4228
1003440      3817
1003434      3705
1003328      3491
1003624      3351
1000509      3047
1003197      3000
1003514      2649
1000493      2485
1003582      2114
1003153      1991
1003155      1491
1003259      1340
1002913      1306
1003630      1165
1001623      1125
1003566       975
1000725       971
1001787       826
1003632       735
1003578       693
1003518       569
1003626       528
1000527       420
1003596       358
1003536       222
1001025       197
1003374       194
1003538       189
1003602       153
1003364       133
1003640       123
1002581       121
1003594        98
1003590        80
1003616        42
1001053        28
1003340        25
1003628        23
Name: campaign_id, dtype: int64

carrier 1    778097
2    108923
0     83457
3     71197
Name: carrier, dtype: int64 1    778097
2    108923
0     83457
3     71197
Name: carrier, dtype: int64
city 137104104102100    26255
137105102101100    20107
137105101100100    19931
0                  18342
137106101101100    16752
137104102101100    16724
137103104101100    16200
137104104101100    16146
137101101100100    15890
137103102101100    15219
137104104117100    13851
137104101101100    13333
137103107102100    13239
137103101100100    13146
137102102101100    12451
137101102100100    12062
137104106101100    11365
137104103101100    11127
137102103101100    10305
137101103101100    10265
137102101101100     9543
137101103106100     9238
137103107101100     9058
137103102105100     8663
137103103102100     8553
137103107113100     7349
137104104106100     7266
137101103102100     6983
137103105105100     6749
137101103104100     6575
                   ...
137106104104100      506
137106102113100      498
137106102103100      466
137101105103100      458
137104102107100      446
137106105113100      440
137106104105100      430
137106103105100      430
137106105108100      359
137106102114100      357
137106104102100      345
137106102102100      327
137106105109100      313
137106105115100      312
137106105114100      311
137102103113100      299
137107102100100      295
137106105102100      281
137106103108100      255
137101105112100      182
137107101100100      169
137105104110100      169
137106103104100      118
137106103103100      116
137106105112100       73
137107103100100       69
137103107100100       64
137106103107100       63
137106103106100       55
137105105107100       30
Name: city, Length: 333, dtype: int64 137104104102100    26255
137105102101100    20107
137105101100100    19931
0                  18342
137106101101100    16752
137104102101100    16724
137103104101100    16200
137104104101100    16146
137101101100100    15890
137103102101100    15219
137104104117100    13851
137104101101100    13333
137103107102100    13239
137103101100100    13146
137102102101100    12451
137101102100100    12062
137104106101100    11365
137104103101100    11127
137102103101100    10305
137101103101100    10265
137102101101100     9543
137101103106100     9238
137103107101100     9058
137103102105100     8663
137103103102100     8553
137103107113100     7349
137104104106100     7266
137101103102100     6983
137103105105100     6749
137101103104100     6575
                   ...
137106104104100      506
137106102113100      498
137106102103100      466
137101105103100      458
137104102107100      446
137106105113100      440
137106104105100      430
137106103105100      430
137106105108100      359
137106102114100      357
137106104102100      345
137106102102100      327
137106105109100      313
137106105115100      312
137106105114100      311
137102103113100      299
137107102100100      295
137106105102100      281
137106103108100      255
137101105112100      182
137107101100100      169
137105104110100      169
137106103104100      118
137106103103100      116
137106105112100       73
137107103100100       69
137103107100100       64
137106103107100       63
137106103106100       55
137105105107100       30
Name: city, Length: 333, dtype: int64
click 0.0    802863
1.0    198787
Name: click, dtype: int64 0.0    802863
1.0    198787
Name: click, dtype: int64
creative_has_deeplink False    1041372
True         302
Name: creative_has_deeplink, dtype: int64 False    1041372
True         302
Name: creative_has_deeplink, dtype: int64
creative_height 640     656630
720     278588
480      78106
300      19554
600       3203
320       2468
150       2142
728        655
1200       160
960        157
360          5
800          5
1080         1
Name: creative_height, dtype: int64 640     656630
720     278588
480      78106
300      19554
600       3203
320       2468
150       2142
728        655
1200       160
960        157
Name: creative_height, dtype: int64
creative_id 2334795    160012
2338420     98425
2337017     83076
2336951     67148
2342154     44709
2316955     35415
2332997     33668
2342152     31388
2317979     24623
2342876     22457
2339954     22160
2338402     19239
2341348     16817
2301593     12067
2323359     12012
2320155     11634
2317991     10346
2313501      9145
2316043      8370
2325035      8323
2339650      6760
2342960      6596
2341340      6517
2342730      5896
2323355      5612
2339744      5128
2313211      4903
2340088      4729
2342464      4717
2301255      4606
            ...
2342528         1
2316195         1
2340102         1
2342492         1
2317617         1
2317051         1
2316095         1
2340616         1
2340656         1
2330103         1
2340168         1
2342906         1
2343004         1
2342886         1
2315101         1
2343002         1
2339822         1
2338138         1
2316273         1
2331629         1
2338140         1
2339152         1
2341218         1
2342362         1
2342280         1
2342860         1
2343040         1
2316247         1
2342856         1
2342718         1
Name: creative_id, Length: 872, dtype: int64 2334795    160012
2338420     98425
2337017     83076
2336951     67148
2342154     44709
2316955     35415
2332997     33668
2342152     31388
2317979     24623
2342876     22457
2339954     22160
2338402     19239
2341348     16817
2301593     12067
2323359     12012
2320155     11634
2317991     10346
2313501      9145
2316043      8370
2325035      8323
2339650      6760
2342960      6596
2341340      6517
2342730      5896
2323355      5612
2339744      5128
2313211      4903
2340088      4729
2342464      4717
2301255      4606
            ...
2340968        26
2342080        26
2342580        26
2341934        25
2342608        25
2342084        25
2341812        25
2338308        25
2342584        25
2342604        25
2341554        25
2342402        25
2342414        25
2342616        24
2330199        24
2342620        24
2342180        23
2342588        23
2342704        23
2342198        22
2341466        22
2342260        22
2342268        22
2341464        22
2342624        22
2342612        21
2342568        21
2342672        21
2317485        21
2342668        21
Name: creative_id, Length: 574, dtype: int64
creative_is_download False    1022076
True       19598
Name: creative_is_download, dtype: int64 False    1022076
True       19598
Name: creative_is_download, dtype: int64
creative_is_js False    1041674
Name: creative_is_js, dtype: int64 False    1041674
Name: creative_is_js, dtype: int64
creative_is_jump True     1022076
False      19598
Name: creative_is_jump, dtype: int64 True     1022076
False      19598
Name: creative_is_jump, dtype: int64
creative_is_voicead False    1041674
Name: creative_is_voicead, dtype: int64 False    1041674
Name: creative_is_voicead, dtype: int64
creative_tp_dnf 8390430283595430291    532692
8390267734059046014    173814
8390229093704413749     80326
8390272894417697957     72024
8390422898336367555     55143
8390465404427801098     26898
8390262347072055304     24309
8390404739335806554     19551
8390450942386608675     18915
8390315526253027596     12694
8390266143715132170      5961
8390208550469153745      5062
8390444191684042888      3531
8390340620840395588      2234
8390408677558032839      2142
8390223573345972946      2063
8390206106730935773       919
8390306859109689610       734
8390219183871226435       658
8390483109367134434       655
8390386683353042630       311
8390481084525682962       271
8390474539725762824       153
8390218012708626392       153
8390269097774621091       140
8390344680474778891       122
8390250959269752400       104
8390247287855705511        27
8390248575962145764        12
8390463243185524240        11
8390417110961853357        10
8390283785102240334         7
8390465451893731029         5
8390413048789200838         5
8390331106014492062         4
8390385744224680798         4
8390453447857114156         3
8390429306397609573         3
8390246606676644621         1
8390215629401019756         1
8390376977610114501         1
8390486394401462948         1
Name: creative_tp_dnf, dtype: int64 8390430283595430291    532692
8390267734059046014    173814
8390229093704413749     80326
8390272894417697957     72024
8390422898336367555     55143
8390465404427801098     26898
8390262347072055304     24309
8390404739335806554     19551
8390450942386608675     18915
8390315526253027596     12694
8390266143715132170      5961
8390208550469153745      5062
8390444191684042888      3531
8390340620840395588      2234
8390408677558032839      2142
8390223573345972946      2063
8390206106730935773       919
8390306859109689610       734
8390219183871226435       658
8390483109367134434       655
8390386683353042630       311
8390481084525682962       271
8390474539725762824       153
8390218012708626392       153
8390269097774621091       140
8390344680474778891       122
8390250959269752400       104
8390247287855705511        27
Name: creative_tp_dnf, dtype: int64
creative_type 8     711966
5     189933
3      80326
2      58530
10       919
Name: creative_type, dtype: int64 8     711966
5     189933
3      80326
2      58530
10       919
Name: creative_type, dtype: int64

creative_width 960     537764
1280    254139
320     101286
100      55147
160      39592
240      24449
300      20473
500       3203
150       2142
50        2064
90         655
568        282
800        160
640        157
480        122
360         27
270          5
1200         5
200          1
1920         1
Name: creative_width, dtype: int64 960     537764
1280    254139
320     101286
100      55147
160      39592
240      24449
300      20473
500       3203
150       2142
50        2064
90         655
568        282
800        160
640        157
480        122
360         27
Name: creative_width, dtype: int64
devtype 2    1037966
3       2295
0       1074
1        339
Name: devtype, dtype: int64 2    1037966
3       2295
0       1074
1        339
Name: devtype, dtype: int64
f_channel iqy_2          36247
iqy_15         13458
iqy_4           8056
iqy_8           5637
iqy_1           2734
iqy_29          1969
iqy_10          1725
iqy_7           1616
iqy_27          1584
iqy_21          1553
iqy_6           1516
iqy_22          1392
iqy_5            519
iqy_12           485
iqy_25           433
iqy_3            198
iqy_32           171
iqy_17           115
iqy_31           111
iqy_28            47
iqy_23            40
iqy_0             33
iqy_16            26
iqy_13            24
iqy_30            12
iqy_26            12
iqy_24             6
iqy_20             4
iqy_40004          4
iqy_9              2
               ...
iqy_541443         1
iqy_526449         1
iqy_3010789        1
iqy_230932         1
iqy_403714         1
iqy_1898192        1
iqy_131251         1
iqy_226820         1
iqy_152289         1
iqy_4003236        1
iqy_395280         1
iqy_416897         1
iqy_218939         1
iqy_124387         1
iqy_375078         1
iqy_264336         1
iqy_278488         1
iqy_801970         1
iqy_1119477        1
iqy_757535         1
iqy_738359         1
iqy_349734         1
iqy_268629         1
iqy_2533525        1
iqy_262591         1
iqy_133702         1
iqy_459687         1
iqy_739356         1
iqy_421330         1
iqy_747000         1
Name: f_channel, Length: 77, dtype: int64 iqy_2     36247
iqy_15    13458
iqy_4      8056
iqy_8      5637
iqy_1      2734
iqy_29     1969
iqy_10     1725
iqy_7      1616
iqy_27     1584
iqy_21     1553
iqy_6      1516
iqy_22     1392
iqy_5       519
iqy_12      485
iqy_25      433
iqy_3       198
iqy_32      171
iqy_17      115
iqy_31      111
iqy_28       47
iqy_23       40
iqy_0        33
iqy_16       26
iqy_13       24
Name: f_channel, dtype: int64
inner_slot_id xf_7F9FF3BEA11FE5B3AE6332EFBBD59496        207032
xf_275C061483984E075832A4373BDDF27B        201770
xf_1587571EC0815824E91C5686EDCAC4A7         33365
xf_14BC8A931A7395C8A08134BD620278EF         31854
xf_E604BF307039B0F82DCAB82CE1180874         28175
xf_CFEDE3004A06F3CC3CFDBC7E07738EF2         26692
xf_9EFA0BFCFEDCE6FF7B644299ACB88167         25529
xf_40E6F47CD8CC59E091A7336984A6AFB8         18743
iqy_1000000000381-1-15-30                   16073
iqy_1000000000381-1-5-60                    15515
xf_09A3A0493576051C06B78C2DD5E3620A         15227
iqy_1000000000381-1-15-45                   14010
iqy_1000000000381-1-15-15                   13782
xf_CB55DC033FDE2CB1DBE2BFECC30E8D57         12046
xf_BE6D47FAEB31BC1835E60517A4958769         10677
xf_D84DAB691E2E08C5B80D2FF5135F886E         10365
iqy_1000000000381-1-5-15                     9911
xf_90C0240F17510FD280839E9ECC118EF8          9886
xf_63E7B92E204139C7B3A2D6A4E61AEE2C          9811
xf_62AD7B88C1E8FF4A0D50F8196BB1FC6F          9729
xf_64FAC0085FC8DC679F6BF49A1F98445D          9647
xf_819FBEE49F37896B3E4333AAB23DFB98          8951
xf_826A5605FD0EBC210098D47779C21CBE          8792
xf_985932B4224C236E0EE4DA67B34B199D          8593
xf_4DA478F97159B35D6FE6A55E8877ABC0          8548
xf_BC7B0173440300EEBAC4663AF0D758F9          8075
iqy_1000000000381-1-5-45                     7865
xf_B2110F504257E056C4C1C6901BE26996          7819
xf_179657A198D9CF3798924430D7EE591E          7737
xf_3DBC46FD82881510C3C49C462D88214C          7693
                                            ...
xf_83CB3659FB3E47016FF5D976E9803CB0             1
xf_BF75EEC5F1D0DE2EBC082166836920AE             1
inmobi_633144fca6044d4f855d3edbebb611f5         1
inmobi_4e51b8e1b3004127be2d0f97f1d857c8         1
inmobi_b15ea0988ae2478897ac5628e4e8c9d9         1
inmobi_8ed916689bed44e08bbb3a5e372ac4fd         1
inmobi_704207232958483381314bfb4da85cdd         1
inmobi_04aaf5735c5d4c05becd194d40db29f1         1
inmobi_1bed403688e64ddfbf4f7f1b50abf674         1
inmobi_6bcba4a117274af08834dad2eddd977d         1
inmobi_b188a496ed584c5b838d01316fd2d6f8         1
xf_02A7BD168215ACD9AFB5477DC91C485E             1
inmobi_8f597fe2d696492cb41b35e1ed80424c         1
inmobi_f274a7c2b8164b55b0bac2b313bbb3b8         1
inmobi_66cca3dd53a44338badcf4f287081284         1
inmobi_ed77418f6d32480daa5298bf29f74eaa         1
xf_C2B8C5F975A49B1F41BF847E9239844C             1
inmobi_e8ab9dabff004d7aa1a93a9fccd03f20         1
inmobi_ce8fed5ea6b340eca1b5212f806c5bcf         1
inmobi_0091d6e7a8dd4276bfc0d1f4185602b5         1
inmobi_240962d760464d96880d632e6582982c         1
inmobi_d0c79a46a6aa4834a0470397d63ee53f         1
inmobi_bae901df437e40ce931e2c1b82e240fb         1
inmobi_3850d191cf1d4c52bacc73188d12217e         1
inmobi_9f94f889623942b49cc14ce6a76c8ba4         1
xf_E2A0112230599DE20D9D6C5703C2DEA4             1
inmobi_a96ca21b73c3402a8995f69a2a882874         1
inmobi_f6741ff6c5cb49fa8c38c6fe4a5358e4         1
xf_82BA94A704B593605FB5797644ED3B91             1
xf_24D29944E1360EADAD8B81A2819830D7             1
Name: inner_slot_id, Length: 1180, dtype: int64 xf_7F9FF3BEA11FE5B3AE6332EFBBD59496        207032
xf_275C061483984E075832A4373BDDF27B        201770
xf_1587571EC0815824E91C5686EDCAC4A7         33365
xf_14BC8A931A7395C8A08134BD620278EF         31854
xf_E604BF307039B0F82DCAB82CE1180874         28175
xf_CFEDE3004A06F3CC3CFDBC7E07738EF2         26692
xf_9EFA0BFCFEDCE6FF7B644299ACB88167         25529
xf_40E6F47CD8CC59E091A7336984A6AFB8         18743
iqy_1000000000381-1-15-30                   16073
iqy_1000000000381-1-5-60                    15515
xf_09A3A0493576051C06B78C2DD5E3620A         15227
iqy_1000000000381-1-15-45                   14010
iqy_1000000000381-1-15-15                   13782
xf_CB55DC033FDE2CB1DBE2BFECC30E8D57         12046
xf_BE6D47FAEB31BC1835E60517A4958769         10677
xf_D84DAB691E2E08C5B80D2FF5135F886E         10365
iqy_1000000000381-1-5-15                     9911
xf_90C0240F17510FD280839E9ECC118EF8          9886
xf_63E7B92E204139C7B3A2D6A4E61AEE2C          9811
xf_62AD7B88C1E8FF4A0D50F8196BB1FC6F          9729
xf_64FAC0085FC8DC679F6BF49A1F98445D          9647
xf_819FBEE49F37896B3E4333AAB23DFB98          8951
xf_826A5605FD0EBC210098D47779C21CBE          8792
xf_985932B4224C236E0EE4DA67B34B199D          8593
xf_4DA478F97159B35D6FE6A55E8877ABC0          8548
xf_BC7B0173440300EEBAC4663AF0D758F9          8075
iqy_1000000000381-1-5-45                     7865
xf_B2110F504257E056C4C1C6901BE26996          7819
xf_179657A198D9CF3798924430D7EE591E          7737
xf_3DBC46FD82881510C3C49C462D88214C          7693
                                            ...
xf_2EB04D08C1EB71BEAB7172A3ECC19954            27
xf_04F42D5D01E11ACC8E26CC134CB8CDCE            26
inmobi_6b3749d896a040278adfd9c41efd67e3        26
inmobi_e931046d9c49409a9f850e2cca2b3a27        26
xf_AB098DB9AE46933463E7A1045457ED9E            26
xf_EDCCD620F70219E7BC6162B41909951D            25
xf_84142D0CA67D8A177D3D48F9F0794412            25
xf_2854B8B2D153FDC1F25392A8644C8168            24
inmobi_6ea9e604665b42bfb1bb0861c4505ee9        24
xf_7416134BEB22B8F6B78AE300D8257269            24
xf_79B69173A82D6214BDFCB48B5CACECA6            23
inmobi_897375db3bb54f84aef7ca383eb9cdc5        23
xf_22E8AB2F47891C5595310AB9CD738576            23
xf_ABC00AA8123231ECE65D80A30C7D914B            23
inmobi_30634b18a48445a7a91ad11414162f4d        23
inmobi_2089d1d387b943e8ae56877befc41b3d        23
xf_212C573F87A05AE4CDE0B2553A961EDE            23
xf_1447F1A855743BA3ED0B7A3B7512BCCE            22
xf_AA5BA544A85CF1BE167EB245A830929A            22
xf_271FC16F77AC34A5EB520F88D977FB58            22
inmobi_b32104d21ac942adbee570fb9331a6fb        22
xf_BF83BFAE0F230321CA14F80FF38DBFAD            21
xf_C343423C114CA4973345B564F3B12681            21
xf_19D61EF06078084D4C2C44F04B68A9CC            21
inmobi_2f144d906d3a4d1e8483d263a4ae45aa        21
inmobi_af3bd8767023457e844e6c3b08bcff2d        21
inmobi_90c7ff2a27da44ab98e9aaf77cd416b7        21
inmobi_efaa607516774dfaaa83e9b4308c9dcc        21
xf_44A71B2675532E0540B230A980BCCB57            21
inmobi_c8bbc717ed6a4978bb5d9509358ddc8a        21
Name: inner_slot_id, Length: 437, dtype: int64

make OPPO                                                                                                                     215457
vivo                                                                                                                     209741
HUAWEI                                                                                                                   151572
Xiaomi                                                                                                                    82761
Apple                                                                                                                     52829
Meizu                                                                                                                     37757
apple                                                                                                                     19990
samsung                                                                                                                   17696
GIONEE                                                                                                                    14359
HONOR                                                                                                                      7368
GiONEE                                                                                                                     5538
360                                                                                                                        3842
LeMobile                                                                                                                   3683
ZTE                                                                                                                        3422
APPLE                                                                                                                      3114
Letv                                                                                                                       2988
CMDC                                                                                                                       2863
Hisense                                                                                                                    2193
iPhone7,2                                                                                                                  2167
nubia                                                                                                                      2087
OnePlus                                                                                                                    2068
LENOVO                                                                                                                     2011
iPhone8,1                                                                                                                  1754
iPhone8,2                                                                                                                  1721
Coolpad                                                                                                                    1577
smartisan                                                                                                                  1528
iPhone9,2                                                                                                                  1513
BBK                                                                                                                        1455
DOOV                                                                                                                       1435
xiaomi                                                                                                                     1374
                                                                                                                          ...
OUKI P7                                                                                                                       1
koobeeS305M                                                                                                                   1
Lenovo A3890                                                                                                                  1
koobeeS106                                                                                                                    1
HMDGlobal                                                                                                                     1
%E6%88%91%E6%83%B3%E4%BF%9D%E6%8A%A4%E4%BD%A0%EF%BC%8C%E4%B8%BA%E4%BD%A0%E9%81%AE%E9%A3%8E%E6%8C%A1%E9%9B%A8%E3%80%82         1
OPPO,R7Plusm,R7Plusm                                                                                                          1
OKP6+Pro                                                                                                                      1
shanfu A5                                                                                                                     1
OPPO%20A59s                                                                                                                   1
INTKI_E85                                                                                                                     1
lephone T6 V                                                                                                                  1
Haipainoble-S6                                                                                                                1
PULID                                                                                                                         1
oneplus                                                                                                                       1
FX02                                                                                                                          1
%2522SM-A8000%2522                                                                                                            1
SM-N9508                                                                                                                      1
OPPOA53                                                                                                                       1
Xiaomi,HM NOTE 1S,gucci                                                                                                       1
BAI MI                                                                                                                        1
vivo Y15S                                                                                                                     1
%2522SM-G9508%2522                                                                                                            1
KENBO                                                                                                                         1
%2522MHA-AL00%2522                                                                                                            1
ZTE A520S                                                                                                                     1
Leneo                                                                                                                         1
EPADE                                                                                                                         1
HUAWEI,PIC-AL00,PIC-AL00                                                                                                      1
iphone7                                                                                                                       1
Name: make, Length: 3196, dtype: int64 OPPO               215457
vivo               209741
HUAWEI             151572
Xiaomi              82761
Apple               52829
Meizu               37757
apple               19990
samsung             17696
GIONEE              14359
HONOR                7368
GiONEE               5538
360                  3842
LeMobile             3683
ZTE                  3422
APPLE                3114
Letv                 2988
CMDC                 2863
Hisense              2193
iPhone7,2            2167
nubia                2087
OnePlus              2068
LENOVO               2011
iPhone8,1            1754
iPhone8,2            1721
Coolpad              1577
smartisan            1528
iPhone9,2            1513
BBK                  1455
DOOV                 1435
xiaomi               1374
                    ...
SHOWN                  22
ONEPLUS A5010          22
GN8001                 22
BLN-AL30               22
KIW-UL00               22
LND-AL40               22
1607-A01               22
iPhone7%2C2            22
vivo Z1i               22
vivoY66                22
LeBest                 22
Newman                 22
Allwinner              21
CENXIN                 21
CAM-UL00               21
YLTphone               21
PE-TL20                21
READBOY                21
PROTRULY               21
vivo Y33               21
MEIZU M6               21
LLD-AL30               21
Spreadtrum             21
Pioneer                21
HUAWEI CAZ-TL20        21
SINTAVE                21
feixun                 21
blackberry             21
JinXing                21
OD103                  21
Name: make, Length: 557, dtype: int64

model iPhone                   11485
OPPO A57                  9730
OPPO+A57                  9400
iPhone7,2                 7540
OPPO R9s                  6876
iPhone8,2                 6823
iPhone8,1                 6795
iPhone9,2                 6594
OPPO A59s                 6551
OPPO+A33                  6470
vivo X9                   6331
vivo Y66                  6033
OPPO+A37m                 5979
OPPO A37m                 5747
OPPO-A57                  5654
PACM00                    5436
vivo+Y66                  5396
MHA-AL00                  5305
iPhone9,1                 4997
OPPO R9m                  4964
OPPO R11                  4629
iPhone7,1                 4556
A31                       4544
vivo-Y66                  4530
BND-AL10                  4320
vivo X7                   4297
OPPO+A59s                 4046
vivo X20A                 4036
PADM00                    3995
OPPO A33                  3904
                         ...
A25                          1
LD700                        1
ZTEQ302C                     1
588                          1
huawei m2-801l               1
Lenovo%25252BA890e           1
mige+1s                      1
A79k                         1
GIONEEGN5006                 1
HM%25252B1SW                 1
protruly d7                  1
Hisense+C1                   1
E910-QJ                      1
Hisense-E75M                 1
vivo%25252525252BY18L        1
oppor9splust                 1
ZUKZ1                        1
zsl865_cmcc                  1
ZTE%2525252BBV0720           1
roco                         1
iPhone%252525252B4S          1
Redmi%2B6%2BPro              1
HUAWEI%252BY635-TL00         1
TCL+P528D                    1
K010                         1
K-Touch-8818                 1
G4-DL                        1
-v18                         1
ztebv0710                    1
Lenovo%2525252BZ90-7         1
Name: model, Length: 14209, dtype: int64 iPhone                                          11485
OPPO A57                                         9730
OPPO+A57                                         9400
iPhone7,2                                        7540
OPPO R9s                                         6876
iPhone8,2                                        6823
iPhone8,1                                        6795
iPhone9,2                                        6594
OPPO A59s                                        6551
OPPO+A33                                         6470
vivo X9                                          6331
vivo Y66                                         6033
OPPO+A37m                                        5979
OPPO A37m                                        5747
OPPO-A57                                         5654
PACM00                                           5436
vivo+Y66                                         5396
MHA-AL00                                         5305
iPhone9,1                                        4997
OPPO R9m                                         4964
OPPO R11                                         4629
iPhone7,1                                        4556
A31                                              4544
vivo-Y66                                         4530
BND-AL10                                         4320
vivo X7                                          4297
OPPO+A59s                                        4046
vivo X20A                                        4036
PADM00                                           3995
OPPO A33                                         3904
                                                ...
iPad6,3                                            21
OPPO%2525252BR11s%2525252BPlus                     21
HUAWEI%20NXT-DL00                                  21
vivo%25252525252BX6S%25252525252BA                 21
SOP-N9                                             21
SM-G930F                                           21
HUAWEI%20Y635-TL00                                 21
OPPOR9PlusmA                                       21
Mi%2525252BNote%2525252B3                          21
COMIO M7000+                                       21
vivo%2525252525252BY67L                            21
DOOV T20L                                          21
Coolpad 8730L                                      21
Redmi%252525252525252BNote%252525252525252B4       21
BF_A500                                            21
OPPO%252BA57t                                      21
R3                                                 21
Mi%25252BNote%25252B3                              21
GM-T5                                              21
KONKA+E1                                           21
Lovme-T26                                          21
DOOV-A8                                            21
GN9000                                             21
Lenovo Z2                                          21
scl-tl00                                           21
GIONEE-F109                                        21
Lenovo P1c58                                       21
LA-S33                                             21
ZTE BA610C                                         21
NOAIN T01                                          21
Name: model, Length: 2681, dtype: int64
nnt 1    780942
4    178674
3     60489
0     19026
2      2329
5       214
Name: nnt, dtype: int64 1    780942
4    178674
3     60489
0     19026
2      2329
5       214
Name: nnt, dtype: int64
orderid 3011318    47585
3010798    47020
3006301    44787
3011828    44709
3008491    43022
3009966    40054
3011304    31388
3012120    31114
3009488    30052
3010298    22160
3009080    21192
3009240    18040
3006467    17238
3009770    14994
3010348    12458
2300169    12341
2307861    12282
3006011    12154
2308523    12012
3012252    10653
3011158     9879
2306891     9646
2308671     9533
2300845     9359
3012264     8687
3011366     8187
3012750     7619
3011626     6681
3009834     6106
3012606     6064
           ...
3005979        3
3012640        3
3012752        3
3012250        3
3012770        3
3012282        3
3010868        3
3009294        3
2306779        2
3012760        2
3008461        2
3010756        2
3012822        2
3010776        2
3009896        2
3012584        1
3010326        1
2306775        1
2303681        1
3012786        1
3012420        1
3012296        1
3009356        1
3012664        1
3007929        1
3009916        1
3012728        1
3012724        1
3012690        1
3012764        1
Name: orderid, Length: 953, dtype: int64 3011318    47585
3010798    47020
3006301    44787
3011828    44709
3008491    43022
3009966    40054
3011304    31388
3012120    31114
3009488    30052
3010298    22160
3009080    21192
3009240    18040
3006467    17238
3009770    14994
3010348    12458
2300169    12341
2307861    12282
3006011    12154
2308523    12012
3012252    10653
3011158     9879
2306891     9646
2308671     9533
2300845     9359
3012264     8687
3011366     8187
3012750     7619
3011626     6681
3009834     6106
3012606     6064
           ...
3011742       27
3012012       27
2306743       27
3012762       27
3011550       27
3011876       27
3011870       27
3012736       26
3011926       26
3012390       25
3012088       25
2306731       25
3012092       25
3012876       25
3011546       25
3012442       24
3005079       24
2301583       23
3012220       23
3012634       23
3012602       23
3012290       23
3011964       23
3011938       22
2306765       22
2307541       22
3012074       22
3012592       21
3012656       21
3009360       21
Name: orderid, Length: 851, dtype: int64
os 2    948043
1     93612
0        19
Name: os, dtype: int64 2    948043
1     93612
Name: os, dtype: int64
os_name android    948043
ios         93612
unknown        19
Name: os_name, dtype: int64 android    948043
ios         93612
Name: os_name, dtype: int64
osv 6.0.1                149902
5.1.1                 96497
7.1.1                 92912
5.1                   83468
6.0                   72611
7.1.2                 69852
8.0.0                 65989
7.0                   62124
8.1.0                 54927
4.4.4                 44485
5.0.2                 34425
6.0.0                 29316
5.1.0                 28836
7.0.0                 25473
11.4                  22384
11.4.1                18726
4.4.2                 12175
10.3.3                 5502
11.3.1                 5488
4.3                    4062
11.3                   3928
11.2.6                 3343
5.0                    3289
4.2.2                  2624
11.1.2                 2332
10.2.1                 1883
11.2.5                 1800
11.2.1                 1750
10.3.2                 1727
11.0.3                 1359
                      ...
11_0_2                    1
iPhoneOS9.3.4             1
8.4.0                     1
iPhoneOS8.3               1
10_2                      1
10_3_2                    1
iPhoneOS9.3.5             1
9_2_1                     1
11.30000019073486         1
iOS10.0.2                 1
6.0.2                     1
iPhone OS 7.0.6           1
O                         1
8_1_2                     1
9.100000381469727         1
8_2                       1
iOS 10.0                  1
10.1.3                    1
3.1                       1
11_0_1                    1
11_2                      1
iPhoneOS9.3.3             1
iPhoneOS8.1.2             1
10_1_1                    1
3.0.1                     1
4.2.0                     1
4.4.6                     1
25.0.0                    1
8_0                       1
9_2                       1
Name: osv, Length: 303, dtype: int64 6.0.1           149902
5.1.1            96497
7.1.1            92912
5.1              83468
6.0              72611
7.1.2            69852
8.0.0            65989
7.0              62124
8.1.0            54927
4.4.4            44485
5.0.2            34425
6.0.0            29316
5.1.0            28836
7.0.0            25473
11.4             22384
11.4.1           18726
4.4.2            12175
10.3.3            5502
11.3.1            5488
4.3               4062
11.3              3928
11.2.6            3343
5.0               3289
4.2.2             2624
11.1.2            2332
10.2.1            1883
11.2.5            1800
11.2.1            1750
10.3.2            1727
11.0.3            1359
                 ...
10.0.3              74
iOS 10.3.3          69
android6.0.1        58
8.0.2               57
4.2                 56
4.0.3               53
iOS 11.3            50
7.0.4               48
19                  48
android7.0          46
2.3.6               42
iOS11.4             40
android6.0          40
21                  36
android8.1.0        34
4.1                 32
iOS 11.2.6          32
iOS 11.1.2          30
iOS 10.3.2          29
android5.1.1        29
11_4                28
android7.1.2        27
android5.1          27
iOS11.4.1           25
android8.0.0        25
iOS 10.1.1          25
iOS 10.2.1          24
android7.1.1        24
iOS 11.2.1          23
iOS 11.0.3          21
Name: osv, Length: 118, dtype: int64
province 137104104100100    122796
137103107100100     80075
137103102100100     68841
137104101100100     65598
137101103100100     60292
137105102100100     54147
137103104100100     44633
137101104100100     39396
137104106100100     38649
137104103100100     37286
137102101100100     36171
137103103100100     36102
137104102100100     35870
137106101100100     32916
137103105100100     29333
137103106100100     27282
137102103100100     26751
137102102100100     26373
137105104100100     25883
137101105100100     21049
137105101100100     19931
0                   18342
137101101100100     15890
137106102100100     14985
137105103100100     14833
137103101100100     13146
137101102100100     12062
137106105100100      9959
137106104100100      4803
137104105100100      3778
137106103100100      3355
137105105100100       614
137107102100100       295
137107101100100       169
137107103100100        69
Name: province, dtype: int64 137104104100100    122796
137103107100100     80075
137103102100100     68841
137104101100100     65598
137101103100100     60292
137105102100100     54147
137103104100100     44633
137101104100100     39396
137104106100100     38649
137104103100100     37286
137102101100100     36171
137103103100100     36102
137104102100100     35870
137106101100100     32916
137103105100100     29333
137103106100100     27282
137102103100100     26751
137102102100100     26373
137105104100100     25883
137101105100100     21049
137105101100100     19931
0                   18342
137101101100100     15890
137106102100100     14985
137105103100100     14833
137103101100100     13146
137101102100100     12062
137106105100100      9959
137106104100100      4803
137104105100100      3778
137106103100100      3355
137105105100100       614
137107102100100       295
137107101100100       169
137107103100100        69
Name: province, dtype: int64

In [12]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].nuniques(),data[col][data[col].value_counts()>20].nuniques())

AttributeError: 'Series' object has no attribute 'nuniques'

In [13]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,data[col].nuniques())

AttributeError: 'Series' object has no attribute 'nuniques'

In [14]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,len(data[col].value_counts),len(data[col].value_counts()[data[col].value_counts()>20]))

TypeError: object of type 'method' has no len()

In [15]:
for col in data.columns.values:
    if col in ["instance_id", "label", "user_tags","hour","day","time"]:
        continue
    print(col,len(data[col].value_counts()),len(data[col].value_counts()[data[col].value_counts()>20]))

adid 2113 1247
advert_id 39 36
advert_industry_inner 25 22
advert_name 35 32
app_cate_id 22 21
app_id 439 212
app_paid 1 1
campaign_id 66 56
carrier 4 4
city 333 333
click 2 2
creative_has_deeplink 2 2
creative_height 13 10
creative_id 872 574
creative_is_download 2 2
creative_is_js 1 1
creative_is_jump 2 2
creative_is_voicead 1 1
creative_tp_dnf 42 28
creative_type 5 5
creative_width 20 16
devtype 4 4
f_channel 77 24
inner_slot_id 1180 437
make 3196 557
model 14209 2681
nnt 6 6
orderid 953 851
os 3 2
os_name 3 2
osv 303 118
province 35 35

In [16]:
data['model'].unique()

array(['HUAWEI-CAZ-AL10', 'Redmi Note 4', 'OPPO+R11s', ...,
       'vivo%252BX710L', 'iPad7,4', 'HTC_D816x'], dtype=object)

In [17]:
data['make'].unique()

array(['HUAWEI', 'Xiaomi', 'OPPO', ..., 'M040', 'boway U15', 'OUGE'],
      dtype=object)

In [18]:
data['model']

0                                          HUAWEI-CAZ-AL10
1                                             Redmi Note 4
2                                                OPPO+R11s
3                                                 OPPO A57
4                                                 iPhone 7
5                                                     MI 6
6                                            iPhone 7 Plus
7                                          HUAWEI-NXT-AL10
8                                                 OPPO R9s
9                                               vivo+Y13iL
10                                             vivo Xplay6
11                                                OPPO R9s
12                                                    x600
13                                                vivo X9s
14                                               vivo Y19t
15                                                  MI%206
16                                               OPPO R11s
17                                               vivo Y79A
18                                                OPPO+A33
19                                             MI NOTE LTE
20                                                iPhone 6
21                       iPhone 6 Plus (A1522/A1524/A1593)
22                                           iPhone 6 Plus
23                                               iPhone7,2
24                                               OPPO R11s
25                                               iPhone7,1
26                                                iPhone 7
27                                                HWI-AL00
28                                               OPPO A57t
29                                               OPPO A59s
                               ...
39994                                        OPPO R9s Plus
39995                                             OPPO A57
39996    OPPO%2525252525252BR9%2525252525252BPlusm%2525...
39997                                                 F100
39998                                vivo%2525252525252BZ1
39999                                             OPPO A83
40000                                             SCL-TL00
40001                                            vivo-Y67A
40002                                             OPPO-A83
40003                                             ALE-TL00
40004                                        vivo X9s Plus
40005                                            TRT-AL00A
40006                                           iPhone10,2
40007                                             OPPO+A57
40008                                            PRA-AL00X
40009                                      vivo+X9s+Plus+L
40010                                            vivo Y67L
40011                                              H60-L11
40012                                       OPPO R9s Plust
40013                                             OPPO-A30
40014                                             Redmi-5A
40015                                             OPPO A57
40016                                         vivo Xplay5S
40017                                             SM-J5008
40018                                             EVA-AL10
40019                                             OPPO-R9s
40020                                                MI-5X
40021                                             vivo Y37
40022                                          vivo%20Y75A
40023                                                  A31
Name: model, Length: 1041674, dtype: object

In [19]:
from collection import Counter

ModuleNotFoundError: No module named 'collection'

In [20]:
from collections import Counter

In [21]:
Counter(data['model'])

Counter({'HUAWEI-CAZ-AL10': 561,
         'Redmi Note 4': 1553,
         'OPPO+R11s': 1094,
         'OPPO A57': 9730,
         'iPhone 7': 2326,
         'MI 6': 3026,
         'iPhone 7 Plus': 2872,
         'HUAWEI-NXT-AL10': 613,
         'OPPO R9s': 6876,
         'vivo+Y13iL': 241,
         'vivo Xplay6': 714,
         'x600': 252,
         'vivo X9s': 2222,
         'vivo Y19t': 9,
         'MI%206': 109,
         'OPPO R11s': 3017,
         'vivo Y79A': 1135,
         'OPPO+A33': 6470,
         'MI NOTE LTE': 646,
         'iPhone 6': 3423,
         'iPhone 6 Plus (A1522/A1524/A1593)': 48,
         'iPhone 6 Plus': 2235,
         'iPhone7,2': 7540,
         'iPhone7,1': 4556,
         'HWI-AL00': 2868,
         'OPPO A57t': 3676,
         'OPPO A59s': 6551,
         'iPhone 6s': 2776,
         'M571C': 423,
         'OPPO R9s Plus': 2889,
         'OPPO R11': 4629,
         'SM-G9006V': 57,
         'note': 127,
         'OPPO R9m': 4964,
         '8.1.2': 5,
         'iPhone 5 (GSM CDMA)': 104,
         'MIX 2S': 609,
         'OPPO%20R11': 430,
         'iPhone (undetected)': 2130,
         'OPPO R11t': 2031,
         'HUAWEI-VNS-AL00': 354,
         'RNE-AL00': 1506,
         'vivo+Y55': 1576,
         'iPhone5,2': 384,
         'Redmi Note 5': 1055,
         'A31': 4544,
         'HM 1S': 214,
         'OPPO+R7sPlus': 337,
         'HUAWEI CAZ-AL10': 1334,
         'iPhone9,2': 6594,
         'OPPO A77t': 698,
         'MI MAX 2': 1281,
         'iPhone8,2': 6823,
         'iPhone 8 Plus': 1348,
         'vivo X20A': 4036,
         'N5207': 150,
         'vivo Y75': 541,
         'HUAWEI MLA-AL10': 2317,
         'OPPO+R11': 1385,
         'SM-G9350': 1417,
         'OPPO+A37m': 5979,
         'BND-AL10': 4320,
         'vivo X9': 6331,
         'vivo Y75A': 1271,
         'HTC+E9t': 1,
         'iPhone6,2': 1542,
         'vivo+X9': 2869,
         'vivo%20X7': 461,
         'LeX620': 35,
         'Redmi 3X': 235,
         'MHA-AL00': 5305,
         'vivo Y55': 1432,
         'vivo-Y51A': 2156,
         'MI+4LTE': 385,
         'OPPO R7s': 1257,
         'OPPO-R9s': 2767,
         'Redmi Note 3': 2222,
         'iPhone X': 1594,
         'PAAM00': 1914,
         'cun-al00': 38,
         'vivo Y27': 371,
         'FRD-AL10': 2874,
         'm2': 1046,
         'SINTAVE-S1000': 2,
         'M621C': 707,
         'OPPO-A73': 1195,
         'ZUK Z1': 55,
         'OPPO-A59s': 3545,
         'vivo-Y67A': 1773,
         'vivo%20Y55A': 240,
         'koobee S309': 31,
         'HUAWEI VNS-TL00': 264,
         'OPPO A59m': 3179,
         'M+A5': 341,
         'vivo Y85': 817,
         'OPPO%20R9tm': 251,
         'vivo X7': 4297,
         'SM-N900J': 2,
         'huawei crr-cl00': 2,
         'vivo V3M A': 1219,
         'vivo%20Y67': 301,
         'PLK-TL00': 193,
         'OPPO A83': 3087,
         'Redmi 3S': 881,
         'iPhone9,1': 4997,
         'OPPO-R9sk': 1350,
         'HUAWEITAG-AL00': 24,
         'vivoV3MA': 26,
         'vivo+X20A': 1615,
         'ALP-AL00': 2581,
         'Best sonny_LT986': 2,
         'Redmi Note 5A': 1338,
         'M6': 568,
         'PLE-703L': 291,
         'PLK-TL01H': 690,
         'vivo Y66': 6033,
         'vivo Y51': 2999,
         'vivo+Y67A': 1999,
         'M3s': 1749,
         'OPPO-R9m': 2015,
         'BLN-AL10': 3860,
         'vivo-X9s-L': 402,
         'OPPO+R9tm': 896,
         'vivo-X9s-Plus': 548,
         'vivo-X20A': 1774,
         'ALP-TL00': 248,
         'GN5001S': 2498,
         'MI 5X': 2071,
         'HUAWEI-SC-UL10': 24,
         'vivo+Y35': 545,
         'lephone T7+': 148,
         'OD105': 264,
         'vivo-Y66i-A': 1155,
         'vivo%2525252525252BX6S%2525252525252BA': 31,
         'TRT-AL00A': 3297,
         'vivo-Y66': 4530,
         'A31t': 405,
         '1501_M02': 417,
         'OPPO-A79kt': 112,
         'OPPO+A33m': 2787,
         'OPPO+A57': 9400,
         'vivo y66': 63,
         'vivo X7Plus': 2296,
         'OPPO+R9s+Plus': 1305,
         'VTR-TL00': 262,
         'MP1602': 193,
         'OPPO%25252525252BR9sk': 48,
         'HUAWEI+G750-T01': 35,
         'vivo X6Plus D': 599,
         'iPhone8,1': 6795,
         'm3': 1792,
         'vivo X21': 675,
         'Lenovo A360t': 22,
         'vivo%2525252525252BY67': 48,
         'KIW-AL10': 1822,
         'Redmi-Note-4X': 2093,
         'MI5': 8,
         'Redmi 4A': 1836,
         'HUAWEI GRA-TL00': 255,
         nan: 7793,
         'iPhone8,4': 502,
         'vivo Y79': 513,
         'vivo V3Max A': 2009,
         'M623C': 516,
         'H60-L02': 148,
         'CAM-TL00': 2301,
         'iPhone': 11485,
         'C1230L': 12,
         'iPhone8%2C2': 262,
         'OPPO A37t': 1973,
         'CAM-AL00': 2074,
         'MI-4LTE': 668,
         'vivo%2525252BXplay6L': 3,
         'HUAWEI ALE-CL00': 173,
         'ALE-UL00': 447,
         'MI 8': 1179,
         'Mi Note 3': 1430,
         'OPPO-A83t': 972,
         'Meizu+S6': 223,
         'VIE-AL10': 1073,
         'OPPO-R11': 1901,
         'vivo Xplay5A': 661,
         'GN5001': 266,
         'OPPO-R11t': 771,
         'OPPO A53': 777,
         'NEM-UL10': 274,
         'vivo-X7Plus': 979,
         'MI 5s': 774,
         'GT-I8552': 26,
         'iPhone 6s Plus': 2814,
         'G13': 47,
         'huawei caz-al10': 15,
         'OPPO+A59s': 4046,
         'vivo X20': 1415,
         'HUAWEI-MLA-AL10': 1016,
         'M3X': 369,
         'OPPO A79k': 465,
         'JMM-AL10': 1100,
         'Redmi-Note-3': 1635,
         'MI%205s': 50,
         'OPPO-A83': 2606,
         'R7Plus': 1012,
         'm2+note': 1010,
         'KIW-CL00': 296,
         'MI MAX': 894,
         'iPhone 5s': 335,
         'BLN-AL20': 1306,
         'edi-al10': 13,
         'vivo+Y75': 574,
         'Mi-4c': 1102,
         'GEM-703L': 168,
         'EVA-AL10': 2375,
         'oppo r9sk': 54,
         'vivo X21A': 2424,
         'OPPO-R9s-Plus': 1086,
         'DLI-AL10': 1796,
         'SM-G9009D': 70,
         'vivo-Y85A': 1699,
         'Lenovo K52t38': 5,
         'bnd-al00': 7,
         'vivo+X5Pro+V': 105,
         'LON-AL00': 1122,
         'vivo X9Plus': 2238,
         'HUAWEI MT7-TL10': 402,
         'Redmi Note 4X': 3203,
         'HUAWEI+MLA-AL10': 608,
         'SLA-TL10': 1081,
         'vivo-Y66L': 1661,
         'vivo-Y53': 541,
         'OPPO%252525252525252BR11': 72,
         'HUAWEI-MT7-TL00': 93,
         'OPPO R9tm': 2416,
         'MI-MAX': 505,
         'HUAWEI-ALE-CL00': 91,
         'HUAWEI+TIT-AL00': 220,
         'OS103': 55,
         'CHM-TL00': 776,
         'PRA-AL00': 2973,
         'Redmi-Note-5A': 1151,
         'vivo x20': 13,
         'OPPO A73': 1654,
         'PADM00': 3995,
         'OPPO A33': 3904,
         'Redmi-4X': 1173,
         'vivo%20Y79A': 77,
         'OYSIN MX6': 14,
         'vivo+Y66': 5396,
         'Redmi 5 Plus': 2083,
         'vivo X9s Plus L': 449,
         'vivo+Y66i+A': 1632,
         'vivo x9s plus': 15,
         'vivo Y66i': 723,
         'GT-I9500': 104,
         'Redmi 6': 113,
         'oppo r7sm': 98,
         'Le+X820': 41,
         'NEM-AL10': 2196,
         'vivo-X9s-Plus-L': 213,
         'vivo Y71A': 1202,
         'PAAT00': 541,
         'NOAIN R9S': 37,
         'vivo+Y31A': 1493,
         'OPPO+A77': 900,
         'WP': 89,
         'SM-G9250': 581,
         'MX6': 1105,
         'ANE-AL00': 1512,
         'MIX 2': 1209,
         'vivo-X9Plus': 927,
         'HM-2A': 523,
         'HUAWEI-C199s': 16,
         'vivo%20X20A': 367,
         'COL-AL10': 1615,
         'vivo-X5Pro-D': 328,
         'SCL-TL00H': 691,
         'GM-Q5-': 20,
         'bln-al10': 29,
         '2014813': 1769,
         'vivo X9i': 1641,
         'HUAWEI%20NXT-TL00': 63,
         'PACM00': 5436,
         'vivo+Y53': 678,
         'm2 note': 696,
         'OPPO-R9skt': 87,
         'DIG-AL00': 2663,
         'LDN-AL00': 717,
         'Note 1LTETD': 1,
         'sm-a3000': 1,
         'Redmi+4X': 1084,
         '1505-a02': 41,
         'Le%252525252525252BX620': 27,
         'vivo%20Y66': 570,
         'vivo Y51A': 3051,
         'vivo+Y55A': 2488,
         'OPPO A37m': 5747,
         'OPPO-A57': 5654,
         'vivo+Y31': 1058,
         'vivo%20Y66L': 221,
         'OPPO-A59m': 1529,
         'Redmi 4X': 1448,
         'OPPO R7': 1025,
         'SM-A7000': 578,
         'vivo Y66L': 2540,
         'Coolpad 8675-HD': 77,
         'JMM-AL00': 1628,
         'ZTE+C880U': 4,
         'OPPO-A37m': 3373,
         'vivo X9L': 1290,
         'vivo Y23L': 695,
         'vivo+X6SPlus+D': 269,
         'huawei rio-al00': 43,
         'vivo X6D': 1381,
         'OPPO A53m': 673,
         'vivo X6L': 208,
         'CHM-UL00': 414,
         'vivo%20X9Plus': 235,
         'OPPO A73t': 783,
         'Che1-CL10': 721,
         'vivo%2525252BY51': 51,
         'MP1701': 82,
         'SM-G9500': 623,
         'HM NOTE 1LTE': 744,
         'vivo%20Y67A': 231,
         'HUAWEI NXT-CL00': 89,
         'vivo+Y66i': 1009,
         'vivo-X21A': 1157,
         'DUK-AL20': 2639,
         'SM-C7100': 159,
         'mi max': 22,
         'HUAWEI TAG-AL00': 1090,
         'ZUK Z2121': 134,
         'CHM-CL00': 612,
         'RedmiNote4': 40,
         'OPPO-R7': 573,
         'OPPO R9sk': 3159,
         'Che2-TL00': 376,
         'OPPO%2525252525252BR7st': 3,
         'M6-Note': 645,
         'vivo X9s Plus': 1169,
         'HUAWEI C8816': 25,
         'OPPOA57': 111,
         'MX4 Pro': 135,
         'vivo-V3Max-A': 1167,
         'vivo%20X9s': 183,
         'Redmi-3': 589,
         'M5+Note': 1871,
         'GN9010': 612,
         'OPPO+R7sm': 741,
         'MI-MAX-2': 572,
         'X820': 308,
         'VKY-AL00': 2008,
         'MI 4LTE': 963,
         'OPPO-R11s': 1414,
         '1605-A01': 505,
         'R7005': 139,
         'vivoY67A': 37,
         'vivo+Y79': 387,
         'SCL-AL00': 1069,
         'GN5003': 786,
         'iPhone10,3': 3722,
         'vivo Y67A': 2794,
         'Redmi-3S': 801,
         'vivo Y31A': 1188,
         'vivo+Y37': 422,
         'HUAWEI NXT-AL10': 2091,
         '7 plus': 6,
         'letv x500': 25,
         'Coolpad 8737': 77,
         'M1 E': 797,
         'MI-5X': 1160,
         'vivo-X9': 3322,
         'OPPO+R11st': 595,
         'huawei nxt-al10': 75,
         'CK3-01': 200,
         'Le X621': 119,
         'vivo+Y51': 3454,
         'MX5': 1441,
         'OPPO%20A57': 560,
         'OPPO+R9+Plusm+A': 714,
         'vivo-Y55': 1067,
         'iPhone%252525252B8': 13,
         'vivo Y69A': 89,
         'F103S': 56,
         'RedmiNote4X': 52,
         'LND-AL40': 425,
         'PADT00': 1147,
         'EVA-TL00': 693,
         'SLA-AL00': 2591,
         'vivo x9i': 15,
         'BF_T15': 2,
         'SM-N9500': 276,
         '8676-A01': 99,
         'OPPO R11st': 1259,
         'OPPO+A57t': 3664,
         'vivo+V3Max': 43,
         'M5 Note': 2259,
         'Redmi Note 2': 1223,
         'M6 Note': 1446,
         'vivo-Y31': 583,
         'OPPO%252BA59m': 43,
         'BAC-TL00': 371,
         'iPhone 8': 875,
         'OPPO+R9sk': 1423,
         'Redmi 3': 720,
         'MIX': 346,
         'HUAWEI C8817E': 38,
         'OPPO%20A33m': 129,
         'EVA-AL00': 1159,
         'Lenovo K30-T': 140,
         'H60-L01': 616,
         'RedmiPro': 6,
         'MI 5s Plus': 678,
         'vivo X3L': 168,
         'SM-C7000': 820,
         'R7c': 424,
         'HUAWEI GRA-CL00': 95,
         'PIC-AL00': 989,
         'vivo X5L': 155,
         'MI 8 SE': 312,
         'GN9010L': 34,
         'STF-AL10': 2338,
         'SM-G7106': 104,
         'M5s': 1909,
         'F8': 8,
         'vivo Y55A': 2589,
         'OPPO R11s Plus': 629,
         'M2 E': 676,
         'MI%204LTE': 82,
         'vivo Y67': 2524,
         'Redmi 4': 568,
         'gn5001s': 66,
         'MI2': 77,
         'iPhone 5s (A1457/A1518/A1528/A1530)': 21,
         'Le X620': 1461,
         'vivo%20X3L': 23,
         'M1%20E': 48,
         'OPPO%20A83': 146,
         'SM-G5108Q': 88,
         '1503-A01': 162,
         'ATH-AL00': 913,
         'YP P880S': 1,
         'PRA-TL10': 779,
         'vivo%20X20': 143,
         'SM-G9550': 736,
         'vivo+X5Pro+D': 313,
         'OPPO+R9m': 1842,
         'iPhone 5s (Global)': 471,
         'NX569H': 294,
         'G620-L75': 86,
         'TRT-TL10A': 1306,
         'R7Plusm': 1650,
         'vivoX20A': 47,
         'vivo+Y79A': 760,
         'Coolpad-Y82-820': 19,
         'm1 metal': 650,
         'ONEPLUS A5000': 483,
         '1713-A01': 308,
         'Redmi+5+Plus': 864,
         'NX563J': 268,
         'vivo Y35': 555,
         'GN9011': 272,
         'ONEPLUS A5010': 437,
         'KOB-L09': 56,
         'OPPO%25252525252BA59m': 49,
         'CHM-TL00H': 923,
         'HUAWEIMLA-AL10': 68,
         'GIONEE+S10BL': 39,
         'vivo Y67L': 1681,
         'm3 note': 1123,
         'SM-G6000': 419,
         'vivo Y55L': 1144,
         'SM919': 78,
         'MIX%25252525252B2': 10,
         '1801-A01': 489,
         'X520': 216,
         'vivo X21i A': 503,
         '1607-a01': 72,
         '1707-A01': 460,
         '2014812': 344,
         '1505-A01': 367,
         'OPPO%20R11t': 224,
         'LND-TL40': 133,
         'GIONEE%20S10C': 15,
         'che1-cl20': 19,
         'CAM-TL00H': 802,
         'MI2SC': 98,
         'GN8003': 1175,
         'KNT-AL20': 700,
         'CUN-AL00': 1949,
         'vivo+Y23L': 714,
         'vivo+X9i': 1009,
         'sm-c9000': 17,
         'vivo Y83': 373,
         'OPPO%20A59m': 251,
         'STF-AL00': 1532,
         'vivo Y53': 684,
         'OPPO%20A83t': 74,
         'OPPO+A79t': 190,
         's9l': 5,
         'EYU T5S': 12,
         'vivo+X6D': 733,
         'iPhone10,1': 1723,
         'MI NOTE Pro': 179,
         'huawei g7-tl00': 18,
         '4G+': 98,
         'MI 5': 1551,
         'HUAWEI M2-A01L': 10,
         'oppo a59s': 128,
         'BKL-TL10': 107,
         'vivo NEX A': 267,
         'vivo+X7L': 47,
         'COL-TL10': 78,
         'OPPO R11 Plus': 835,
         'HUAWEI MLA-TL10': 145,
         'MI 6X': 981,
         'OWWO A8': 19,
         'SM-C7010': 189,
         'Redmi%20Note%204': 170,
         'vivo%252525252BX9i': 10,
         'OPPO R9km': 413,
         'ZTE C2016': 41,
         'pra-al00': 15,
         'PRO 7-H': 115,
         'OPPO+A53m': 880,
         'vivo%252BX21A': 45,
         'BND-AL00': 1645,
         'gn8003': 79,
         'HUAWEI GRA-UL10': 225,
         'S9': 656,
         'vivo+Y51A': 3436,
         'CLT-AL01': 280,
         'KNT-AL10': 714,
         'vivo Z1i': 182,
         'SM-G9208': 103,
         'G7-TL00': 1,
         'OC105': 181,
         'HUAWEI MT7-TL00': 262,
         'MI2S': 180,
         'MEIZU M6': 327,
         'GT-S7278': 9,
         'vivo-X6S-A': 601,
         'OPPO%20A33': 195,
         'OPPO+A59m': 1653,
         'VTR-AL00': 2730,
         'HM+2A': 286,
         'HM+NOTE+1LTE': 380,
         'CLT-AL00': 776,
         'MP1503': 188,
         'iPad4,1': 152,
         'SM-G6100': 214,
         'vivo+Y67': 1678,
         'Redmi%2525252525252B5': 2,
         'M5-Note': 1144,
         'iPhone 5c (GSM)': 9,
         'Redmi-4A': 1553,
         'SM-A9100': 163,
         'vivo%25252BY75': 9,
         'vivo%2525252BX9': 214,
         'vivo-X5Max-': 236,
         'vivo-Y55A': 1699,
         'PIC-TL00': 228,
         'OPPO-R9-Plusm-A': 904,
         'OPPO%20R9s': 686,
         'vivo%25252525252BY67A': 37,
         'vivo-Y55L': 657,
         'koobee-S309': 4,
         'Redmi-Note-4': 975,
         '8681-M02': 101,
         'vivo Y33': 369,
         'A51': 726,
         'SM-A8000': 402,
         'OPPO%25252BA37m': 93,
         'vivo-Y67L': 1007,
         'OPPO%25252525252BA59s': 90,
         'ALOES': 52,
         'GIONEE GN5007': 139,
         'R8207': 1273,
         'MI-6': 402,
         'KNT-UL10': 407,
         'vivo+V3': 458,
         'vivo+X9s': 1076,
         'vivo Y31': 859,
         'Letv%20X500': 71,
         'vivo-Y29L': 105,
         'OPPO%25252BA79t': 6,
         'Bird D08': 22,
         'iPad': 276,
         'Redmi-Note-2': 957,
         'vivo+X6Plus+A': 149,
         'vivo%20X6Plus%20D': 74,
         'BLN-TL10': 1379,
         'Le X520': 193,
         'M5': 2623,
         'OPPO%252525252525252BA59s': 86,
         'PLK-CL00': 107,
         'Meizu S6': 345,
         'NCE-AL00': 704,
         'OPPO+A59st': 200,
         'OPPO%25252BR9%25252BPlustm%25252BA': 11,
         'vivo X9s L': 906,
         'vivo X6SPlus D': 491,
         'm3%252525252525252Bnote': 10,
         '1107': 422,
         'Redmi+Note+4X': 1360,
         'OPPO+R9s': 3005,
         'YU-FLY-F9': 85,
         'Letv X500': 455,
         'GIONEE-S10': 171,
         'vivo-Y79A': 735,
         'vivo%20Y71A': 39,
         'BLN-AL40': 2909,
         'CHE-TL00H': 655,
         'OPPO-R9km': 209,
         'PAR-AL00': 178,
         'F103': 820,
         'vivo%2525252BY66': 109,
         'ZTE BA910': 57,
         'vivo-Y51': 2016,
         'Redmi%25252BNote%25252B4': 16,
         'OPPO%2525252525252BR9%2525252525252BPlusm%2525252525252BA': 29,
         'M1-E': 320,
         'GN8001': 445,
         'vivo+X5M': 639,
         'LLD-AL20': 448,
         'vivo-Y71A': 1083,
         'Coolpad+8675-HD': 12,
         'MHA-L09': 1,
         'Che2-TL00H': 20,
         'ZTE-BV0720': 17,
         'OPPO A77': 1247,
         'U20': 387,
         'iPhone10,2': 3271,
         'PRA-AL00X': 3365,
         'HUAWEI+RIO-AL00': 269,
         'Redmi+Note+3': 1043,
         'HUAWEI-NXT-TL00': 134,
         'Coolpad-5380CA': 12,
         'DOOV+V17': 1,
         'vivo Xplay3S': 126,
         'OPPO-R11st': 566,
         'vivo-Y53L': 275,
         'FIG-AL00': 444,
         'vivo-Y67': 1543,
         'SM-N9100': 199,
         'GIONEE%252525252525252BS10C': 6,
         'GIONEE%20S10': 54,
         'vivo-Y31A': 788,
         'vivo%25252BY85A': 45,
         'vivo Y71': 690,
         'HUAWEI%25252BTIT-AL00': 7,
         'OPPO-A33': 2112,
         'H30-T10': 72,
         'OPPO%2525252BA59m': 74,
         'vivo X5M': 672,
         'oppor7s': 32,
         'Redmi%252525252525252BNote%252525252525252B4X': 17,
         'vivo-X6L': 127,
         'vivo%252525252525252BX20A': 63,
         'CHE-TL00': 500,
         'HUAWEI%20VNS-AL00': 92,
         'OPPO+A79k': 294,
         'ONEPLUS-A3010': 27,
         'OPPO-R7s': 667,
         'SM-C5000': 810,
         'OPPO R9st': 1006,
         'vivo+X21A': 780,
         'Lenovo-K50-t5': 24,
         'vivo+X9s+Plus+L': 286,
         'vivo+Y55L': 1157,
         'F100': 1019,
         'U10': 245,
         'Letv+X500': 148,
         'HUAWEI NXT-TL00': 396,
         'F5': 504,
         'vivo%20X6D': 184,
         'DIG-TL10': 736,
         'vivo Y85A': 1987,
         'Hisense+M30': 11,
         'vivo-X6A': 408,
         'HUAWEI-TAG-AL00': 586,
         'OPPO R9 Plustm A': 756,
         'vivo Y923': 91,
         'LLD-AL00': 1473,
         'OPPO%25252BA57': 130,
         'vivo+X9L': 695,
         'YU%252525252525252BFLY%252525252525252BF9': 2,
         'OPPO%2525252BA57': 152,
         'vivo+X3F': 32,
         'NX541J': 130,
         'vivo-Y13': 27,
         'Le X528': 180,
         'vivo-Y35': 393,
         'vivo-X20': 629,
         'vivo X6SPlus A': 118,
         'vivo X5S L': 328,
         'Redmi 5A': 855,
         'OPPO A33m': 1775,
         'Mi Note 2': 274,
         'OPPO R11 Pluskt': 397,
         'vivo-Xplay5A': 226,
         'VKY-TL00': 106,
         'GN3002L': 53,
         'LND-AL30': 1364,
         'Coolpad 8721': 24,
         'FLA-AL10': 569,
         'cam-al00': 23,
         'KOPO L9': 83,
         'M681C': 52,
         'Best sonny LT999': 73,
         'SCL-CL00': 412,
         'lephone T7A': 256,
         'LLD-AL10': 1338,
         'HUAWEI%2525252BRIO-AL00': 14,
         '1515-A01': 22,
         'maichai': 6,
         'HUAWEI Y635-TL00': 33,
         'iPhone10%2C2': 138,
         'ZTE+V0840': 63,
         'GIONEE-F109L': 12,
         'HUAWEI C199': 64,
         'BND-TL10': 649,
         'vivo+V3M+A': 1067,

In [22]:
Counter(data['make'])

Counter({'HUAWEI': 151572,
         'Xiaomi': 82761,
         'OPPO': 215457,
         nan: 103043,
         'Apple': 52829,
         'Xiaomi,MI 6,sagit': 5,
         'vivo': 209741,
         'x600': 63,
         'BBK': 1455,
         'vivo Y79A': 107,
         'OPPO A59s': 755,
         'samsung': 17696,
         'm1': 84,
         'HTC': 393,
         'iPhone6,2': 401,
         'LeMobile': 3683,
         'vivo Y55': 83,
         'Meizu': 37757,
         'SINTAVE': 21,
         'ZUK': 480,
         'koobee': 1118,
         'meizu': 740,
         'GiONEE': 5538,
         'xiaomi': 1374,
         'Blephone': 769,
         'smartisan': 1528,
         '360': 3842,
         'Meitu': 753,
         'APPLE': 3114,
         'LENOVO': 2011,
         'vivo Y79': 71,
         'vivo V3Max A': 230,
         'PHICOMM': 61,
         'HUAWEI ALE-CL00': 15,
         'OUKI': 119,
         'OPPO A57': 861,
         'OPPO A79k': 61,
         'GEM-703L': 12,
         'iPhone9,1': 1197,
         'Huawei': 996,
         'NOAIN': 232,
         'WellPhone': 45,
         'HONOR': 7368,
         'xiaolajiao': 789,
         '2014813': 34,
         'PADM00': 237,
         'MI 6': 219,
         'YuLong': 1321,
         'ZTE': 3422,
         'OPPO A53m': 44,
         'OPPO R9s Plus': 477,
         'HUAWEI NXT-CL00': 13,
         'CHM-CL00': 17,
         'RedmiNote4': 5,
         'vivo X20A': 529,
         'Le': 882,
         'VKY-AL00': 166,
         'iphone': 567,
         'iPhone10,3': 941,
         'VIVO': 320,
         'letv': 13,
         'Yulong': 695,
         'apple': 19990,
         'MHA-AL00': 402,
         'EVA-TL00': 45,
         'bifer': 15,
         'Letv': 2988,
         'iPhone8,1': 1754,
         'iPhone7,2': 2167,
         'QiKU': 264,
         'Lenovo A938t': 1,
         'PIC-AL00': 76,
         'LeBest': 22,
         'ALPS': 29,
         'nubia': 2087,
         'Coolpad': 1577,
         'OnePlus': 2068,
         'PRA-AL00': 136,
         'GIONEE': 14359,
         'HUAWEIMLA-AL10': 15,
         'KNT-AL20': 59,
         'CUN-AL00': 53,
         'EYU': 229,
         'h7571': 53,
         'OPPO R11 Plus': 136,
         'vivo Y66L': 236,
         'M5 Note': 165,
         'OWWO': 62,
         'vivo Y67L': 215,
         'HUAWEI MLA-AL10': 288,
         'SM-G9550': 77,
         'vivo Y31A': 56,
         'KNT-UL10': 36,
         'Letv%20X500': 2,
         'SPRD': 378,
         'MI MAX 2': 103,
         'LDN-AL00': 24,
         'NCE-AL00': 26,
         'YU-FLY': 3,
         'DOOV': 1435,
         'vivo Xplay3S': 11,
         'OPPO A37t': 68,
         'vivo Y71': 57,
         'MI': 114,
         'oppo': 894,
         'vivo Y67A': 324,
         '8681-M02': 3,
         'Hisense': 2193,
         'Redmi 5 Plus': 185,
         'YUFLY': 407,
         'Redmi 5A': 32,
         'SM-C5000': 69,
         'OPPO R11st': 199,
         'vivo X9i': 284,
         'FLA-AL10': 40,
         'KOPO': 275,
         'Best sonny': 119,
         'lephone': 525,
         'GN5001S': 91,
         'vivo Y66': 573,
         'vivo X9': 837,
         'DIG-TL10': 35,
         'vivo X5S L': 23,
         'LeEco': 682,
         'SOP': 155,
         'iPhone9,2': 1513,
         'Lenovo': 714,
         'EML-AL00': 150,
         'OPPO R9s': 878,
         'iPhone10,1': 327,
         'LEX720': 78,
         'vivo,vivo V3Max A,PD1523': 3,
         'vivo Y66i': 59,
         'WAS-AL00': 167,
         'EVA-AL10': 209,
         'Sony Ericsson': 8,
         'ZYDZ': 44,
         'iPhone7,1': 1305,
         'OPPO R11': 609,
         'asus': 209,
         'UOOGOU': 139,
         'vivo Xplay5A': 96,
         'iPhone8,2': 1721,
         'vivo X7': 509,
         'CMDC': 2863,
         'PACM00': 454,
         'BLN-TL10': 69,
         'lge': 98,
         'OPPO R11t': 263,
         'RNE-AL00': 112,
         'OPPO A59m': 311,
         'X9007': 3,
         'vivo X21i A': 72,
         'vivo Y51': 237,
         'Edward': 5,
         'SMARTISAN': 255,
         'iPhone10,2': 637,
         'HUAWEI VNS-AL00': 52,
         'KONKA': 682,
         'OPPO R9m': 563,
         'OPPO A73t': 95,
         'BLA-AL00': 129,
         'ASUSTek Computer Inc': 16,
         'AoleDior': 57,
         'QMobile': 1,
         'OPPO A33': 216,
         'GOME': 146,
         'HWI-AL00': 232,
         'KOOBEE': 3,
         'vivo X9L': 155,
         'vivo Y55A': 223,
         'BND-AL00': 102,
         'vivo Y71A': 98,
         'boway': 69,
         'OYSIN': 90,
         'HUAWEI RIO-AL00': 79,
         'alps': 714,
         'Honor': 674,
         'ZOL': 3,
         'BIFER': 154,
         'NX523J_V1': 100,
         'GIONEE S10L': 26,
         'CMCC': 176,
         'SM-C7000': 59,
         'YUSUN': 95,
         'Sony': 298,
         'blackshark': 144,
         'OPPO A77': 127,
         'MI%204LTE': 5,
         'iPhone8,4': 123,
         'huawei': 265,
         'OPPOR11t': 3,
         'COMIO': 248,
         'HMD Global': 222,
         'DLI-AL10': 53,
         'Qingcheng': 285,
         'SLA-AL00': 97,
         'OPPO A83': 284,
         'HUAWEI TIT-AL00': 35,
         'TCL': 333,
         'GuangXin': 166,
         'InFocus': 18,
         'OPPO A57t': 322,
         'MYA-AL10': 30,
         'MeiLai': 14,
         'GIONEE S10BL': 10,
         'YU': 66,
         'vivo X20Plus A': 109,
         'vivo X9Plus': 338,
         'ivvi': 296,
         'OPPO R9sk': 420,
         'PAAT00': 54,
         'San+Cup': 5,
         'FRD-AL10': 227,
         'HUAWEI TAG-TL00': 52,
         'vivo X21A': 362,
         'honor': 607,
         'Android': 136,
         'vivo Y85A': 234,
         'NX511J_V3': 15,
         'Redmi 3': 38,
         'KIW-TL00H': 41,
         'vivo X6S A': 140,
         'XBS': 3,
         'Le X620': 127,
         'Le X528': 15,
         'EDI-AL10': 48,
         'Redmi Note 2': 58,
         'iPad4,1': 20,
         'sprd': 356,
         'HUAWEI CAZ-AL10': 150,
         'vivo Y53': 27,
         'Redmi Note 3': 147,
         'MI 8': 77,
         'vivo NEX A': 41,
         'Kumai 920': 1,
         'vivo Y51A': 220,
         'Changhong': 361,
         'OPPO A33m': 115,
         'OPPO R11s': 416,
         'MEIZU M6': 21,
         'Redmi Note 5A': 92,
         'NX612J': 1,
         'Redmi Note 4': 134,
         'NEM-AL10': 103,
         'vivo X21': 111,
         'OPPO R9 Plusm A': 278,
         'BLN-AL20': 95,
         'LND-AL30': 55,
         'vivo X9Plus L': 52,
         '4G+': 72,
         'OPPO A37m': 355,
         'BLN-AL40': 135,
         'OPPO R7sPlus': 51,
         'vivo Y67': 289,
         'K-Touch': 82,
         'KING HON': 6,
         'JMM-AL00': 66,
         'm3': 47,
         'EVA-AL00': 81,
         'CLT-AL01': 39,
         'ETON': 79,
         'Ctyon': 1,
         'NX529J': 167,
         'honglajiao': 69,
         'iPad5,2': 2,
         'TRT-TL10': 45,
         'DUK-AL20': 219,
         'DIG-AL00': 102,
         'TRT-AL00': 70,
         'HMD+Global+Oy': 33,
         'HMD-Global': 48,
         'AOSON M8': 1,
         'OPPO R7s': 117,
         'vivo X20': 225,
         'G108': 2,
         'SEUIC': 66,
         'UBX': 9,
         'SUGAR': 583,
         'forme': 4,
         'vivo,vivo Y71A,PD1731': 2,
         'OPPO A79': 82,
         'OPPO A73': 162,
         'YITAI': 7,
         'VIE-AL10': 90,
         'HUAWEI NXT-AL10': 221,
         'NEO-AL00': 4,
         'SM-G9500': 66,
         'CHM-TL00H': 24,
         '%2522vivo%2BX9%2522': 3,
         'coolpad': 123,
         'PADT00': 65,
         'PACT00': 142,
         'LON-AL00': 116,
         'Lovme-T19': 28,
         'vivo X9s': 268,
         'iPhone': 85,
         'LA-S35': 12,
         'Mi Note 2': 27,
         '%2522MI%2B8%2BSE%2522': 1,
         'DUXIU': 7,
         'OPPO R9s Plust': 25,
         'vivo Y53L': 20,
         'MIX 2': 81,
         'SOAP': 10,
         'SAF': 13,
         'GN8003L': 15,
         'doov': 26,
         'zte': 138,
         'AUM-AL20': 12,
         'vivo X6D': 142,
         'HOSIN': 3,
         'LGE': 191,
         'BND-AL10': 214,
         'Skyhon': 32,
         'vivo X9s L': 137,
         'ALOES': 37,
         'vivo X9s Plus L': 76,
         'SM-G5700': 11,
         'Mytel': 50,
         'Redmi 4': 51,
         'G123': 10,
         'PRA-AL00X': 193,
         'SL600': 1,
         'CLT-AL00': 76,
         'Y01(YP01)': 8,
         'BAC-AL00': 126,
         'STF-AL10': 207,
         'DOOV M2': 2,
         'iPhone10%2C3': 15,
         '4G': 373,
         'A51': 13,
         'ATH-AL00': 56,
         'm3note': 1,
         'Redmi 4A': 91,
         'GIONEE F6L': 13,
         'FRD-AL00': 119,
         'LA-S33': 15,
         'N5207': 4,
         'YLTphone': 21,
         'YAX': 7,
         'OPPO A79t': 45,
         'ONEPLUS': 44,
         'lenovo': 94,
         'common': 39,
         'iPad6,11': 32,
         'Samsung': 101,
         'vivo X21UD A': 74,
         'SAGA': 238,
         'OPPO R9tm': 299,
         'BESTSONNY': 10,
         'iPhone5,2': 53,
         'Gree': 124,
         'PAAM00': 155,
         'm1%20metal': 8,
         'KIW-TL00': 37,
         'Lovme': 91,
         'M651CY': 6,
         'LETV': 6,
         '%2522STF-AL00%2522': 1,
         'Mi-4c': 36,
         'MI MAX': 78,
         'BKL-AL20': 181,
         'CM': 6,
         'M6 Note': 71,
         'iPhone9,4': 58,
         'gionee': 49,
         'vivo X5Pro D': 51,
         'YLT X9-mi6': 1,
         'HM NOTE 1S': 33,
         'HMD-Global-Oy': 19,
         'STF-AL00': 95,
         'TRT-AL00A': 206,
         'MX6': 45,
         'D888': 2,
         'HUAWEI MT7-TL10': 34,
         'GN8001': 22,
         'SHARP': 81,
         'ALP-AL00': 189,
         'GIONEE S10CL': 15,
         'OPPO R7': 65,
         'HUAWEI,SCL-AL00,SCL-AL00': 3,
         'BAC-TL00': 29,
         'R7Plus': 58,
         'VTR-AL00': 252,
         'F8909': 3,
         'OPPO R7sm': 145,
         'YQ601': 6,
         'ZTE BA510': 4,
         'BLN-AL10': 260,
         'OPPO%20R9s': 15,
         'haipainoble S8': 2,
         'vivo X7Plus': 285,
         'F105': 9,
         'C106-9': 15,
         'T1': 88,
         'Angelcare-F5': 1,
         'R7Plusm': 102,
         'CAM-TL00': 70,
         'hx711': 4,
         'VK': 26,
         'Lovme-T23': 3,
         'HM': 12,
         'vivo Y33': 21,
         'Generic': 161,
         'BOWAY': 160,
         'ALE-UL00': 23,
         'YLT': 16,
         'Bird': 80,
         'NX575J': 7,
         'vivo Y55L': 68,
         'yeechui': 48,
         'Lezhou': 26,
         'MI 6X': 95,
         'vivo X6Plus A': 32,
         '麦动出品': 2,
         'hasee': 82,
         'LLD-AL10': 81,
         'Bifer': 24,
         'VKY-TL00': 9,
         'MTK': 7,
         'GN9011': 15,
         'BirdL9': 1,
         'vivo Y83A': 70,
         'Redmi 3S': 81,
         'imoo': 96,
         'vivo Y85': 103,
         'Redmi Note 5': 86,
         'KNT-AL10': 39,
         'DLI-TL20': 31,
         'Redmi Note 4X': 308,
         'S36': 15,
         'vivo Y75A': 133,
         'SM-A5000': 33,
         'COR-AL00': 11,
         'OPPO R11s Plust': 43,
         'KIW-AL10': 91,
         'NX569H': 33,
         'VOTO': 166,
         'PBAM00': 19,
         'BTV-DL09': 10,
         'HUAWEI C8816': 1,
         'ZTE BA603': 2,
         'MX5': 146,
         'HTC D816t': 2,
         'Philips': 70,
         'MEIIGOO': 8,
         'NG2': 8,
         'GN5005': 27,
         'OPPO A77t': 64,
         'android': 16,
         'M2017': 5,
         'vivo Y23L': 17,
         'Tinai': 12,
         'K-TOUCH': 20,
         'M5': 67,
         'A31': 34,
         'GN9012': 18,
         'OPPOA59s': 6,
         'OS105': 34,
         'Nokia': 91,
         'motorola': 302,
         'MI 5X': 182,
         'M-16': 2,
         'Neolix': 42,
         'COR-AL10': 26,
         'hipad': 24,
         'vivo,vivo X9,PD1616': 19,
         'vivo Xplay6': 115,
         'SM-G5500': 19,
         'S9L': 3,
         'sony': 73,
         'm2': 31,
         '1603-A03': 6,
         'JMM-AL10': 48,
         '4G-': 35,
         'DAJ': 14,
         'FIG-AL10': 62,
         'SM919': 4,
         'OPPO%20R9m': 20,
         'SAST': 51,
         'XYANGSHU': 2,
         'GXI': 17,
         'PPTV': 62,
         'm3 note': 60,
         'GIONEE S10': 63,
         'AE+G16': 1,
         'lnd-al30': 1,
         'OPPO R9skt': 24,
         'Mi Note 3': 143,
         'Jlinksz': 14,
         'SCL-CL00': 5,
         'AGM': 23,
         'Newland': 30,
         'OPPO R9 Plustm A': 91,
         'HUAWEICAZ-AL10': 4,
         'SCL-TL00H': 13,
         'MI 5': 115,
         'LGTD': 18,
         'Spreadtrum': 21,
         'X-apple': 77,
         'Mi 4': 2,
         'COL-AL10': 137,
         'HUAWEITIT-TL00': 4,
         'HUAGAN': 76,
         'OPPOA73': 2,
         'GO': 37,
         'Letv X501': 26,
         'NEXUS': 3,
         'HEYUF': 13,
         'YEPEN': 70,
         'XIAOMI': 9,
         'HUAWEI GRA-UL10': 29,
         'hisense': 67,
         'OPPO A83t': 132,
         'SLA-TL10': 48,
         'MIX 2S': 32,
         'F106L': 8,
         'htc': 44,
         'NX563J': 11,
         'MI 5s Plus': 54,
         'JYD': 20,
         'Halove': 5,
         'OPSSON': 49,
         '%2522OPPO%2BR11t%2522': 3,
         'CongMetal': 1,
         'OPPO R11s Plus': 86,
         'vivo V3': 48,
         'VTR-TL00': 20,
         'PLK-AL10': 66,
         'OPPO R9t': 25,
         'vivo V3M A': 107,
         'KIW-UL00': 22,
         'vivo Y31': 41,
         'Redmi 4X': 124,
         'DOOV L8 Plus': 4,
         '3005': 1,
         'Allwinner': 21,
         'Lovme-T25': 1,
         'CLT-TL00': 4,
         'GOLY': 4,
         'HMD Global Oy': 81,
         'hoonxin': 43,
         'Ukooo': 2,
         '%2522M636%2522': 1,
         'ALP-TL00': 19,
         'ONEPLUS A3010': 18,
         'CAM-AL00': 78,
         'weiimi': 32,
         'Vivo': 145,
         'HUAWEI CAZ-TL10': 18,
         'GN3003': 12,
         'iPhone9,3': 41,
         'Letv X500': 25,
         'M A5': 7,
         'iPhone8%2C2': 17,
         'vivo X6SPlus D': 67,
         'PRO': 13,
         'vivoX9': 15,
         'OPPO R11 Pluskt': 59,
         'HUIZUU': 43,
         'vivo X5Max+': 33,
         'vivo X6A': 83,
         'SuperD': 12,
         'NEM-TL00': 18,
         'BlackBerry': 12,
         'DUK-TL30': 14,
         'MI%205': 38,
         'Caredear': 14,
         'iPad5,3': 27,
         'HM 2A': 13,
         'VOLTE': 181,
         'QUKI': 3,
         'uuloop': 1,
         'SM-G950F': 2,
         'SIM': 1,
         'K600': 2,
         'ONEPLUS A3000': 3,
         'PRO 7-S': 27,
         'HUAWEI TAG-AL00': 97,
         'DAQ': 17,
         'iPad5,1': 14,
         'HUAWEINXT-AL10': 12,
         'ZTE C2017': 2,
         'SM-C7010': 13,
         'OUJIA': 50,
         'SM-J7008': 8,
         'OPPO R9st': 100,
         'iPad6,7': 1,
         'iPhone6,1': 40,
         'ZTE BV0701': 1,
         'vivo X9s Plus': 154,
         'MP1602': 10,
         'R7PLUSM': 7,
         'KIW-CL00': 9,
         'M3 Max': 15,
         'SM-A7009': 6,
         'vivoX9s': 3,
         'BND-TL10': 50,
         'CBL': 11,
         'Onefive': 39,
         'C106': 11,
         'TETC': 70,
         'H60-L01': 23,
         'UNITONE': 47,
         'LON-AL00-PD': 2,
         'HUAWEI MLA-TL10': 17,
         'Teetot': 5,
         'NX569J': 9,
         'vivo Y66i A': 84,
         'F5': 19,
         'Gionee': 19,
         'Motorola': 3,
         'vivo X20Plus': 46,
         'XLJ': 38,
         'G19': 24,
         'T19': 1,
         'PRO 6 Plus': 5,
         'AOLE': 6,
         'Xiami': 2,
         'Haier': 49,
         'MBI-i7': 1,
         '%2522MYA-AL10%2522': 2,
         'Redmi 3X': 29,
         'ares': 2,
         'SM-G9308': 4,
         'ANE-AL00': 109,
         'SM-J5108': 12,
         'M5Note': 9,
         'OPPO,R7Plusm,R7Plusm': 1,
         'vivo,vivo X20Plus,PD1710': 4,
         'NCE-AL10': 28,
         'FLA-AL20': 45,
         'vivo Y69A': 2,
         'GREE': 29,
         'YU+FLY': 1,
         'R8207': 32,
         'MT6517': 2,
         'vivo%20X7': 7,
         'Che1-CL10': 19,
         'M653': 6,
         'HUAWEI%20CAZ-AL10': 2,
         'FIG-TL10': 18,
         'YK': 3,
         'NX510J': 15,
         'LEX626': 23,
         'CHE-TL00H': 16,
         'M3': 18,
         'COL-TL10': 5,
         'TRT-TL10A': 82,
         'vivi': 53,
         'vivo X21i': 20,
         'GIONEE F6': 10,
         'vivo Y937': 6,
         'LLD-AL00': 69,
         'OPPO,OPPO R9sk,R9sk': 4,
         'SM-G9280': 57,
         'vivo Z1i': 22,
         'vivo Y75': 45,
         'MANN': 13,
         'H60-L03': 11,
         'SeeDream': 2,
         'Redmi%20Note%204': 14,
         'READBOY': 21,
         'WaterWorld': 14,
         'BJH': 1,
         'iPhone7%2C1': 6,
         '%E5%A4%A9%E8%AF%AD': 9,
         'REDMI': 97,
         'lemobile': 7,
         'ZTE BA601': 2,
         'Best+sonny': 23,
         'HUAWEI%20CAZ-TL10': 3,
         '%2522BAC-TL00%2522': 1,
         'OPPO,OPPO R9s,R9s': 8,
         'BKL-TL10': 12,
         'NX513J': 33,
         'YK5001': 1,
         '%2522vivo%2BY67%2522': 2,
         'Lovme-T16': 3,
         'VVETIME': 18,
         'XT1635-03': 3,
         'KDOOR': 55,
         'MI6': 4,
         'MAN': 1,
         'v10': 6,
         'Haipainoble-S6': 1,
         'ONEPLUS A5000': 23,
         'HHT6C': 14,
         '1707-A01': 16,
         'M621C': 24,
         'Ben1': 3,
         'HUAWEI MLA-AL00': 13,
         'Lovme-T26': 6,
         'HUASEN': 47,
         'HAIMI': 3,
         'vivo X6Plus D': 65,
         'NEM-UL10': 11,
         'KTC, Inc.': 1,
         'vivo Y35': 39,
         'SM-G9650': 14,
         'HUAWEI,STF-AL10,STF-AL10': 5,
         '15': 1,
         'OPPO R11 Plusk': 48,
         'M6': 13,
         'SM-N9200': 18,
         'MX4': 37,
         'HUAWEI VNS-TL00': 25,
         'MI 8 SE': 19,
         'vivo%20X6D': 14,
         'G13': 1,
         'SM-G9350': 116,
         'iPhone7%2C2': 22,
         'SM-G6100': 17,
         'SM-J5008': 25,
         'vivo Y13L': 4,
         'Qiku': 10,
         'BIHEE': 78,
         'vivo,vivo X9i,PD1624': 3,
         'China Mobile': 19,
         '8675': 1,
         'SM-G9250': 45,
         'bird': 59,
         'iOS': 4,
         'JTY': 34,
         'iPad2,5': 9,
         'CHM-TL00': 30,
         'Xiaomi,Redmi Note 4,nikel': 1,
         'blackberry': 21,
         'Pioneer': 21,
         'Hisense,Hisense M20-T,M20-T': 1,
         'OPPO,PACM00,PACM00': 5,
         'SHOWN_P1': 9,
         'UNNO': 15,
         'LeX620': 9,
         'freeme': 30,
         'SM-A5009': 8,
         'MiNote3': 3,
         'HUAWEI VNS-DL00': 15,
         'SM-G9508': 4,
         'iPhone10,5': 11,
         'ZUK Z2121': 6,
         'ZTE BA611C': 3,
         'LLD-TL10': 11,
         'SM-J3119': 9,
         'PIC-TL00': 13,
         'vivo Y83': 31,
         'LLD-AL30': 21,
         'ASUS_X00GD': 1,
         'M3X': 13,
         'F100': 18,
         '1807-A01': 9,
         '%E6%88%91%E6%83%B3%E4%BF%9D%E6%8A%A4%E4%BD%A0%EF%BC%8C%E4%B8%BA%E4%BD%A0%E9%81%AE%E9%A3%8E%E6%8C%A1%E9%9B%A8%E3%80%82': 1,
         'OPPO A79kt': 36,
         'BLA-TL00': 6,
         'EVA-DL00': 17,
         'ASUSTek+Computer+Inc': 2,
         'YUFEILAI': 4,
         'YV': 25,
         'SM-G9200': 29,
         'R1001': 1,
         'iPhone10,6': 24,
         'RedmiNote4X': 9,
         'NOMI': 5,
         'R7007': 5,
         'HUAWEI%20NXT-AL10': 30,
         'CPPC': 4,
         'Redmi 6A': 1,
         'Hasee-X50-TS': 1,
         'CAM-TL00H': 17,
         '%E5%BF%83%E5%8A%A8%E5%A5%88%E4%BD%95%E6%83%85%E5%B7%B2%E8%BF%9C': 1,
         'vivo Y37': 42,
         'GN8003': 68,
         'Redmi 5': 28,
         'MI 5s': 51,
         'ZX': 4,
         'Doov': 47,
         'GN8002S': 58,
         'PLK-UL00': 6,
         'laaboo': 2,
         'EEBBK': 50,
         'ChangHong': 1,
         'vivo X20Plus UD': 4,
         'Xiaomi,Redmi 4X,santoni': 2,
         'LenovoX2-TO': 1,
         '1107': 5,
         'HUAWEI,G621-TL00,G621-TL00': 1,
         'KEJIAN': 39,
         'x-apple': 7,
         '潇爸的荣耀': 1,
         'OPPO,OPPO R7sm,R7sm': 1,
         'cayon': 4,
         'OPPO R9km': 62,
         'vivo Y51t L': 24,
         'XIAOSONGSHU': 1,

In [23]:
data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [24]:
data.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            40014, 40015, 40016, 40017, 40018, 40019, 40020, 40021, 40022,
            40023],
           dtype='int64', length=1041674)

In [25]:
data.columns

Index(['adid', 'advert_id', 'advert_industry_inner', 'advert_name',
       'app_cate_id', 'app_id', 'app_paid', 'campaign_id', 'carrier', 'city',
       'click', 'creative_has_deeplink', 'creative_height', 'creative_id',
       'creative_is_download', 'creative_is_js', 'creative_is_jump',
       'creative_is_voicead', 'creative_tp_dnf', 'creative_type',
       'creative_width', 'devtype', 'f_channel', 'inner_slot_id',
       'instance_id', 'make', 'model', 'nnt', 'orderid', 'os', 'os_name',
       'osv', 'province', 'time', 'user_tags'],
      dtype='object')

In [26]:
data.index.values

array([    0,     1,     2, ..., 40021, 40022, 40023])

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from scipy import sparse
from sklearn.preprocessing import OneHotEncoder

In [2]:
data = np.random.random((10,4))*10.astype('int32')

SyntaxError: invalid syntax (<ipython-input-2-e5394b68969e>, line 1)

In [3]:
data = np.random.random((10,4))

In [4]:
data=data*10

In [5]:
data.astype('int32')
print(data)

[[2.13691433 0.81100793 7.0650795  8.89893013]
 [8.02606348 2.05217624 7.98866077 8.61629203]
 [8.75013275 4.48672561 2.86424272 3.79309083]
 [6.25478495 4.13327084 6.36463615 6.61095327]
 [1.38202158 6.54757703 0.56858324 0.58242893]
 [8.09289798 6.44521171 0.50326514 8.77851929]
 [3.80365004 6.33751678 2.06900685 6.70266903]
 [2.80050738 5.95314892 3.12240477 5.68939247]
 [1.93485141 3.95103339 4.4023795  1.44792493]
 [2.01513983 6.08137386 7.84772605 9.91751568]]

In [6]:
data=data.astype('int32')
print(data)

[[2 0 7 8]
 [8 2 7 8]
 [8 4 2 3]
 [6 4 6 6]
 [1 6 0 0]
 [8 6 0 8]
 [3 6 2 6]
 [2 5 3 5]
 [1 3 4 1]
 [2 6 7 9]]

In [7]:
data

array([[2, 0, 7, 8],
       [8, 2, 7, 8],
       [8, 4, 2, 3],
       [6, 4, 6, 6],
       [1, 6, 0, 0],
       [8, 6, 0, 8],
       [3, 6, 2, 6],
       [2, 5, 3, 5],
       [1, 3, 4, 1],
       [2, 6, 7, 9]], dtype=int32)

In [8]:
enc=OneHotEncoder()
for n in range(data.shape[1]):
    enc.fit(data[n].reshape(-1,1))
    print(enc.transform(data[n].reshape(-1,1)))

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (0, 3)	1.0
  (1, 2)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 1)	1.0

In [9]:
csr=sparse.csr_matrix((10,0))
csr.toarray()

array([], shape=(10, 0), dtype=float64)

In [10]:
enc.fit(data[0].reshape(-1,1))
temp=enc.transform(data[0].reshape(-1,1))
type(temp)
temp.shape

(4, 4)

In [11]:
type(temp)

scipy.sparse.csr.csr_matrix

In [12]:
temp

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [13]:
print(temp)

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 2)	1.0
  (3, 3)	1.0

In [14]:
temp.toarray()

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
enc.fit(data[:,0].reshape(-1,1))
temp=enc.transform(data[:,0].reshape(-1,1))

In [16]:
temp

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [17]:
temp.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [18]:
data[:,0]

array([2, 8, 8, 6, 1, 8, 3, 2, 1, 2], dtype=int32)

In [19]:
print(temp)

  (0, 1)	1.0
  (1, 4)	1.0
  (2, 4)	1.0
  (3, 3)	1.0
  (4, 0)	1.0
  (5, 4)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 0)	1.0
  (9, 1)	1.0

In [20]:
type(temp)

scipy.sparse.csr.csr_matrix

In [21]:
temp.data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
temp.index

AttributeError: index not found

In [23]:
temp.indices

array([1, 4, 4, 3, 0, 4, 2, 1, 0, 1], dtype=int32)

In [24]:
temp.indptr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [25]:
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
csr = sparse.csr_matrix((10,0))
for n in range(data.shape[1]):
    enc.fit(data[n].reshape(-1,1))
    csr = sparse.hstack(csr,enc.transform(data[n].reshape(-1,1)),'csr','bool')
svd = TruncatedSVD(n_components=50)
svd_data = svd.fit_transform(csr)
svd_columns = ["svd_{i}".format(i=i) for i in range(50)]

In [26]:
csr = sparse.csr_matrix((10,0))
csr = sparse.hstack(csr,enc.transform(data[0].reshape(-1,1)),'csr')
csr.toarray()

ValueError: blocks must be 2-D

In [27]:
csr = sparse.csr_matrix((10,0))
csr = sparse.hstack(csr,temp,'csr')
csr.toarray()

ValueError: blocks must be 2-D

In [28]:
csr = sparse.csr_matrix((10,0))

In [29]:
csr.toarray()

array([], shape=(10, 0), dtype=float64)

In [30]:
temp.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [31]:
sparse.hstack((csr,temp),'csr')

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [32]:
sparse.hstack((csr,temp),'csr').toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [33]:
csr=sparse.hstack((csr,temp),'csr').toarray()
temp = enc.transform(data[:,1].reshape(-1,1))
csr=sparse.hstack((csr,temp),'csr').toarray()
print(csr)
print(csr.toarray())

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]]

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [34]:
csr = sparse.csr_matrix((10,0))
csr=sparse.hstack((csr,temp),'csr')
temp = enc.transform(data[:,1].reshape(-1,1))
csr=sparse.hstack((csr,temp),'csr')
print(csr)
print(csr.toarray())

  (1, 1)	1.0
  (1, 6)	1.0
  (4, 3)	1.0
  (4, 8)	1.0
  (5, 3)	1.0
  (5, 8)	1.0
  (6, 3)	1.0
  (6, 8)	1.0
  (8, 2)	1.0
  (8, 7)	1.0
  (9, 3)	1.0
  (9, 8)	1.0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]]

In [35]:
csr

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [36]:
svd = TruncatedSVD(n_components=6)
svd_data = svd.fit_transform(csr)
print(svd_data)
#svd_columns = ["svd_{i}".format(i=i) for i in range(6)]

[[-9.37996977e-16 -5.89245010e-19  4.02362585e-16  1.26896439e-16
   1.96471266e-18  3.22996245e-18]
 [-1.90606624e-16  1.30170385e+00 -5.52781236e-01  8.09268332e-33
   1.45729510e-34  5.80617084e-34]
 [ 7.17675957e-18  1.75090293e-17  1.26199708e-16 -2.37420206e-18
   2.96055706e-19 -8.81471400e-19]
 [ 1.10490866e-28  2.91978094e-31 -0.00000000e+00 -6.79194338e-28
  -4.72810863e-29  2.55209169e-29]
 [ 1.41421356e+00  5.10882548e-17 -1.63813788e-18  2.34125888e-17
  -3.29626329e-17 -7.84523838e-18]
 [ 1.41421356e+00  5.10092123e-17 -9.28161360e-17  6.11436386e-18
   4.55168742e-17 -3.35861564e-18]
 [ 1.41421356e+00  5.10964099e-17 -1.33031937e-17 -2.02463796e-17
  -1.16610035e-17  9.43905882e-18]
 [-8.84147990e-18 -1.46974826e-21  3.77344737e-18  8.38151330e-19
   5.23573920e-19 -3.16538634e-19]
 [-7.56403161e-17  5.52781236e-01  1.30170385e+00 -1.90439816e-32
  -3.47344745e-34 -1.36725240e-33]
 [ 1.41421356e+00  5.10742846e-17  1.02644161e-16 -9.28057306e-18
  -8.93237717e-19  1.76479519e-18]]

In [37]:
type(svd_data)

numpy.ndarray

In [38]:
strs = [['a','b','c'],['c','d'],['b','c','e'],['a','c'],['e']]

In [39]:
cv = CountVectorizer(min_df=2)
cv.fit(strs)
temp = cv.transform(strs)
print(temp)

AttributeError: 'list' object has no attribute 'lower'

In [40]:
strs = [['a','b','c'],['c','d'],['b','c','e'],['a','c'],['e']]
strs = pd.DataFrame(strs)

In [41]:
strs

   0     1     2
0  a     b     c
1  c     d  None
2  b     c     e
3  a     c  None
4  e  None  None

In [42]:
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/round1_iflyad_train.txt',sep='\t')
strs = train['user_tags']
strs

0                                                        NaN
1          2100191,2100078,3001825,,3001781,3001791,30017...
2                                                        NaN
3          2100098,gd_2100000,3001791,3001795,3002193,300...
4                                                        NaN
5          3002265,3002613,3002993,3003055,3003147,300331...
6                                                        NaN
7          gd_2100000,2100143,ag_2100040,3001837,3002907,...
8          ,3004484,3004430,3004434,3004490,3004468,30045...
9          2100197,2100150,2100094,2100237,2100132,ag_210...
10         2100480,2100118,2101058,2100042,2100017,210013...
11                                                       NaN
12                     gd_2100001,ag_2100039,3004430,3004434
13                                                       NaN
14                                                       NaN
15         gd_2100000,3001771,3001881,3001889,3001899,300...
16                                                       NaN
17                                                       NaN
18                   3003779,3004059,3004214,3004430,3004434
19         ag_2100040,3002847,3003097,3003255,3003321,300...
20                                                       NaN
21                                                       NaN
22                                                       NaN
23                                                       NaN
24                                   3004081,3004430,3004434
25                                                       NaN
26                                                       NaN
27                                           3004430,3004434
28                                   3004406,3004430,3004434
29         2100078,3001769,3001771,3001797,3001799,300187...
                                 ...
1001620    2100121,2100011,gd_2100001,2100120,2100041,210...
1001621                                                  NaN
1001622    gd_2100000,3001747,3001791,3001793,3001847,300...
1001623    3003779,3003819,3003843,3003845,3003851,300386...
1001624    3002747,3003379,3003509,3003537,3003559,300365...
1001625                                      3004430,3004434
1001626                gd_2100001,ag_2100040,3004430,3004434
1001627                                              3003783
1001628                                      3004430,3004434
1001629                                                  NaN
1001630                                      3004430,3004434
1001631                                                  NaN
1001632                                      3004430,3004434
1001633                      2100017,2101117,2100078,2100122
1001634           gd_2100000,3004093,3004095,3004430,3004434
1001635    gd_2100001,3001825,,3001779,3001787,3001955,30...
1001636                                              3004430
1001637     gd_2100000,ag_2100039,3007639321,3004430,3004434
1001638                                                  NaN
1001639                                                  NaN
1001640    2100782,2100501,2100144,2101264,2100133,gd_210...
1001641                                                  NaN
1001642                                                  NaN
1001643                                                  NaN
1001644    gd_2100001,2100042,2100041,3002313,3002567,300...
1001645                                                  NaN
1001646    3003123,3003123,3003313,3003321,3003323,300337...
1001647                                                  NaN
1001648      3004406,3004450,3004430,3004434,3004448,3004500
1001649                                                  NaN
Name: user_tags, Length: 1001650, dtype: object

In [43]:
strs.astype(str)

0                                                        nan
1          2100191,2100078,3001825,,3001781,3001791,30017...
2                                                        nan
3          2100098,gd_2100000,3001791,3001795,3002193,300...
4                                                        nan
5          3002265,3002613,3002993,3003055,3003147,300331...
6                                                        nan
7          gd_2100000,2100143,ag_2100040,3001837,3002907,...
8          ,3004484,3004430,3004434,3004490,3004468,30045...
9          2100197,2100150,2100094,2100237,2100132,ag_210...
10         2100480,2100118,2101058,2100042,2100017,210013...
11                                                       nan
12                     gd_2100001,ag_2100039,3004430,3004434
13                                                       nan
14                                                       nan
15         gd_2100000,3001771,3001881,3001889,3001899,300...
16                                                       nan
17                                                       nan
18                   3003779,3004059,3004214,3004430,3004434
19         ag_2100040,3002847,3003097,3003255,3003321,300...
20                                                       nan
21                                                       nan
22                                                       nan
23                                                       nan
24                                   3004081,3004430,3004434
25                                                       nan
26                                                       nan
27                                           3004430,3004434
28                                   3004406,3004430,3004434
29         2100078,3001769,3001771,3001797,3001799,300187...
                                 ...
1001620    2100121,2100011,gd_2100001,2100120,2100041,210...
1001621                                                  nan
1001622    gd_2100000,3001747,3001791,3001793,3001847,300...
1001623    3003779,3003819,3003843,3003845,3003851,300386...
1001624    3002747,3003379,3003509,3003537,3003559,300365...
1001625                                      3004430,3004434
1001626                gd_2100001,ag_2100040,3004430,3004434
1001627                                              3003783
1001628                                      3004430,3004434
1001629                                                  nan
1001630                                      3004430,3004434
1001631                                                  nan
1001632                                      3004430,3004434
1001633                      2100017,2101117,2100078,2100122
1001634           gd_2100000,3004093,3004095,3004430,3004434
1001635    gd_2100001,3001825,,3001779,3001787,3001955,30...
1001636                                              3004430
1001637     gd_2100000,ag_2100039,3007639321,3004430,3004434
1001638                                                  nan
1001639                                                  nan
1001640    2100782,2100501,2100144,2101264,2100133,gd_210...
1001641                                                  nan
1001642                                                  nan
1001643                                                  nan
1001644    gd_2100001,2100042,2100041,3002313,3002567,300...
1001645                                                  nan
1001646    3003123,3003123,3003313,3003321,3003323,300337...
1001647                                                  nan
1001648      3004406,3004450,3004430,3004434,3004448,3004500
1001649                                                  nan
Name: user_tags, Length: 1001650, dtype: object

In [44]:
strs = strs.astype(str)

In [45]:
cv.fit(strs)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [46]:
temp = cv.transform(strs)

In [47]:
temp

<1001650x1377 sparse matrix of type '<class 'numpy.int64'>'
	with 19615828 stored elements in Compressed Sparse Row format>

In [48]:
temp.toarray()[0]

array([0, 0, 0, ..., 0, 1, 0])

In [49]:
svd = TruncatedSVD(n_components=50)
svd_data = svd.fit_transform(temp)
svd_columns = ["svd_{i}".format(i=i) for i in range(50)]
svd_df = pd.DataFrame(data=svd_data, columns=svd_columns)

In [50]:
svd_df

,svd_0,svd_1,svd_2,svd_3,svd_4,svd_5,svd_6,svd_7,svd_8,svd_9,...,svd_40,svd_41,svd_42,svd_43,svd_44,svd_45,svd_46,svd_47,svd_48,svd_49
0,-1.778082e-12,3.928761e-10,-4.316836e-10,-1.089337e-09,4.751475e-10,8.081044e-10,1.000000e+00,-2.443348e-10,-3.770944e-10,-1.972161e-10,...,-1.065278e-08,8.970054e-09,-1.821167e-09,1.165840e-09,1.333966e-09,1.001669e-09,7.089221e-09,-9.017636e-09,-2.386908e-09,2.666572e-09
1,5.977980e+00,-8.528978e-01,-2.290405e+00,1.503704e+00,1.840756e+00,1.115468e+00,-6.275410e-07,-6.146851e-02,-1.245750e+00,3.376853e-01,...,3.102822e-02,-1.735809e-01,-3.545404e-01,-3.395491e-02,-4.182177e-01,-7.942828e-01,1.307699e+00,-2.978531e-01,-2.539470e-01,-3.385750e-01
2,-3.091989e-14,6.442172e-13,1.115232e-10,-2.591135e-11,-6.053027e-10,-3.399338e-10,1.000000e+00,1.983227e-10,-7.656794e-11,5.017749e-10,...,-1.068180e-08,8.363271e-09,-2.111063e-09,-1.045373e-10,2.293802e-09,4.429948e-10,6.105497e-09,-8.282400e-09,-1.419575e-09,2.615095e-09
3,4.883390e+00,-9.515546e-01,2.679862e-01,1.442047e+00,-1.028089e+00,3.245202e-01,2.581721e-06,4.023801e-01,9.156454e-01,-2.180173e-01,...,4.363771e-02,-6.207200e-01,-1.722301e-01,-3.992986e-01,-4.672455e-02,-8.314802e-02,2.506598e-01,9.029651e-02,1.373820e-02,5.176638e-02
4,-3.014587e-14,3.559328e-13,3.097541e-11,3.097950e-11,-1.833726e-10,-1.055000e-10,1.000000e+00,-6.792727e-11,5.084050e-10,1.281366e-10,...,-1.111443e-08,8.041262e-09,-2.307021e-09,3.376117e-10,3.108781e-09,8.777486e-11,7.538047e-09,-7.920180e-09,-3.206757e-09,2.282571e-09
5,3.188377e+00,-5.909214e-01,-3.810731e-01,-1.168991e-01,2.364223e+00,2.587430e-01,1.301992e-05,-2.365374e-01,3.554726e-02,-3.053677e-01,...,-6.338663e-02,-3.544039e-01,-3.317141e-01,2.746100e-02,-4.700030e-01,-1.472251e-02,7.946214e-02,-6.013804e-02,-3.386467e-01,1.139792e-01
6,-3.010083e-14,4.366747e-13,-1.454144e-11,6.295035e-11,1.091897e-10,-3.272065e-10,1.000000e+00,-6.356279e-10,1.330868e-09,-3.705808e-10,...,-1.138538e-08,8.397924e-09,-1.920837e-09,1.516713e-09,2.284715e-09,5.169437e-10,5.972361e-09,-8.906057e-09,-2.406597e-09,2.324619e-09
7,2.961621e+00,-5.880558e-01,6.561475e-01,-5.130268e-01,2.600679e-01,3.992617e-01,-1.109805e-06,-2.910448e-01,1.003578e+00,-2.438512e-01,...,-2.100084e-01,-4.217113e-03,-1.345693e-02,-2.138153e-01,2.553070e-01,-3.001933e-01,2.043197e-01,8.431253e-02,-2.083311e-01,-3.934343e-02
8,1.034541e+00,-2.521984e-01,7.213254e-01,-4.641763e-01,9.769794e-01,-2.701042e-01,-2.508719e-06,2.025257e-01,-1.575601e-01,-1.574778e-01,...,6.382594e-02,-1.101995e-01,-1.450933e-01,5.977230e-02,-2.271271e-02,1.789311e-02,-2.034266e-02,2.236378e-01,3.127827e-02,-6.171497e-02
9,3.213880e+00,-7.126328e-02,-7.700064e-01,-2.148537e+00,-9.584618e-01,6.586211e-01,-9.260580e-06,4.571349e-01,-1.250871e+00,3.500460e-01,...,3.446393e-01,-4.092181e-01,2.624388e-01,-2.115724e-01,-4.954174e-01,7.025185e-01,-3.872755e-01,5.646377e-01,2.832914e-02,-1.415025e-01
10,2.822502e+00,6.841218e+00,-2.071744e+00,-1.368906e+00,4.501289e-01,-2.582130e+00,1.429593e-05,1.895781e+00,-4.886449e-01,8.589611e-01,...,-1.335598e+00,8.780156e-01,-7.141544e-01,-1.040003e+00,4.909332e-01,6.341208e-01,-3.429170e-01,1.751573e-01,-3.146647e-02,-9.451294e-01
11,-2.950940e-14,5.510321e-14,8.341700e-13,8.207103e-13,-4.654503e-12,3.628136e-11,1.000000e+00,-9.917296e-11,-3.398448e-11,-1.345110e-10,...,-1.062253e-08,8.723290e-09,-1.838664e-09,1.429060e-09,1.543312e-09,9.704913e-10,6.761163e-09,-8.763451e-09,-1.888450e-09,2.775719e-09
12,5.919734e-01,-1.350163e-01,5.412560e-01,-6.315222e-01,2.298298e-01,7.536547e-02,-2.251131e-07,8.915762e-01,-2.117206e-01,6.351782e-02,...,-1.679048e-01,3.962880e-02,9.203704e-03,3.896253e-02,1.203598e-01,-4.842550e-02,5.512858e-02,-8.130524e-03,-9.171177e-02,4.608547e-02
13,-2.949507e-14,5.392748e-14,-3.631082e-13,4.748084e-13,8.989968e-12,2.395558e-11,1.000000e+00,-1.780130e-10,-7.031575e-11,2.629674e-10,...,-1.046530e-08,8.789984e-09,-1.417841e-09,1.547777e-09,1.837293e-09,9.505278e-10,6.767453e-09,-8.005805e-09,-2.523823e-09,2.908450e-09
14,-2.949369e-14,5.612888e-14,-5.857694e-13,1.400857e-13,1.431252e-11,1.590442e-11,1.000000e+00,-1.794871e-10,-3.516199e-11,6.687625e-11,...,-1.047600e-08,8.151237e-09,-1.814092e-09,1.177471e-09,1.760966e-09,5.647455e-10,6.669567e-09,-8.060790e-09,-2.304798e-09,2.930293e-09
15,4.853039e+00,-8.315351e-01,-1.661539e+00,9.799674e-01,2.737981e+00,7.953142e-01,-3.198918e-07,1.443254e-01,8.576001e-01,1.557955e+00,...,-3.005360e-01,2.762674e-01,1.301370e+00,-2.750269e-01,-1.838090e-01,3.506539e-02,-2.156933e-01,3.165669e-01,-5.827401e-01,4.455481e-02
16,-2.949807e-14,5.568700e-14,-2.541337e-13,1.009176e-12,9.029404e-12,2.011449e-11,1.000000e+00,-1.941829e-10,-5.549557e-11,2.110506e-10,...,-1.078967e-08,8.746067e-09,-1.997142e-09,6.138460e-10,2.037035e-09,4.681543e-10,6.254723e-09,-8.796928e-09,-2.097394e-09,2.561526e-09
17,-2.949971e-14,5.451442e-14,-9.556245e-14,2.077921e-12,5.220372e-12,2.628242e-11,1.000000e+00,-1.757137e-10,-5.583030e-11,2.767440e-10,...,-1.096123e-08,8.008478e-09,-2.102698e-09,1.435923e-09,1.066336e-09,1.068400e-09,6.050913e-09,-8.726262e-09,-1.874680e-09,3.186536e-09
18,1.204781e+00,-2.993937e-01,9.476672e-01,-7.264874e-01,2.252187e-01,-2.283110e-02,2.886686e-07,6.515364e-01,-1.495265e-01,2.651385e-01,...,-6.999059e-02,-9.701460e-02,1.358114e-02,1.331620e-02,-6.569464e-02,-9.039714e-02,-7.897936e-02,-2.707854e-01,2.605889e-02,2.147921e-02
19,2.275522e+00,-4.223401e-01,4.136905e-01,-2.435951e-01,1.297658e+00,-2.067672e-01,-9.354898e-07,3.943201e-03,2.093216e-01,-5.370563e-01,...,4.248346e-02,7.615821e-03,-3.618039e-01,4.779895e-03,6.163889e-02,-1.205021e-01,2.957811e-01,4.589937e-01,-1.506354e-01,-1.171092e-01
20,-2.949434e-14,5.503447e-14,-3.875359e-13,1.390056e-13,9.544121e-12,2.190971e-11,1.000000e+00,-1.867739e-10,-7.017182e-11,1.828965e-10,...,-1.092190e-08,8.377547e-09,-1.970903e-09,1.307987e-09,1.496907e-09,1.148538e-09,6.797504e-09,-8.405160e-09,-1.993018e-09,3.058879e-09
21,-2.949615e-14,5.486880e-14,-3.944758e-13,7.020552e-13,8.994688e-12,2.233686e-11,1.000000e+00,-1.856626e-10,-5.483462e-11,1.927130e-10,...,-1.088527e-08,8.238072e-09,-1.927823e-09,1.289546e-09,1.202674e-09,1.261688e-09,6.516865e-09,-8.653963e-09,-2.137667e-09,2.798926e-09
22,-2.949772e-14,5.446672e-14,-3.248028e-13,1.144389e-12,7.670903e-12,2.380334e-11,1.000000e+00,-1.872195e-10,-5.492564e-11,2.294561e-10,...,-1.094146e-08,8.605638e-09,-2.232973e-09,9.443395e-10,1.516898e-09,8.239086e-10,6.427567e-09,-8.718025e-09,-1.784161e-09,2.985404e-09
23,-2.949624e-14,5.490269e-14,-4.119956e-13,7.876401e-13,8.721666e-12,2.263471e-11,1.000000e+00,-1.889770e-10,-5.544515e-11,2.164527e-10,...,-1.088995e-08,8.278568e-09,-2.258660e-09,1.028067e-09,1.403483e-09,5.565774e-10,6.293765e-09,-8.911462e-09,-2.031446e-09,2.734118e-09
24,7.431732e-01,-1.856601e-01,6.940572e-01,-5.001460e-01,2.680467e-01,-5.618095e-02,8.709888e-07,6.803618e-01,-1.413696e-01,2.920407e-02,...,9.776279e-02,3.415179e-03,-1.841234e-02,-3.065933e-02,-2.666100e-02,2.691915e-02,-7.876245e-02,1.709662e-01,-9.846242e-02,-1.587525e-01
25,-2.949650e-14,5.483629e-14,-3.799672e-13,8.771030e-13,8.662803e-12,2.277210e-11,1.000000e+00,-1.882931e-10,-5.506511e-11,2.187356e-10,...,-1.090734e-08,8.179440e-09,-1.966838e-09,1.293542e-09,1.440863e-09,8.341643e-10,6.632641e-09,-8.643633e-09,-1.397281e-09,3.192583e-09
26,-2.949672e-14,5.470694e-14,-3.756877e-13,8.481885e-13,8.441102e-12,2.295893e-11,1.000000e+00,-1.874532e-10,-5.626555e-11,2.120997e-10,...,-1.100415e-08,8.452727e-09,-2.027298e-09,1.202823e-09,1.377902e-09,9.025451e-10,6.329063e-09,-8.754000e-09,-2.090618e-09,2.763538e-09
27,5.192115e-01,-1.325943e-01,5.814945e-01,-5.322892e-01,2.890544e-01,-3.626035e-02,-6.385094e-09,7.891724e-01,-1.962124e-01,9.367097e-02,...,1.158901e-01,3.086493e-02,-1.858897e-03,-1.749768e-02,-1.350763e-02,2.756306e-02,4.028770e-02,-8.015967e-02,-1.402903e-02,1.237311e-02
28,6.516728e-01,-1.632078e-01,6.140728e-01,-5.322647e-01,2.848743e-01,-9.493239e-02,1.992645e-07,8.647271e-01,-1.781818e-01,7.930824e-02,...,1.284796e-01,7.165908e-02,-7.270148e-04,-2.758023e-02,-4.576766e-03,2.116606e-02,3.613810e-02,-5.088793e-02,-3.779177e-02,1.166661e-02
29,5.221002e+00,-6.323741e-01,-1.985457e+00,1.018029e+00,2.404157e+00,3.386054e-01,1.082677e-07,6.488188e-01,1.142106e-01,-2.648860e+00,...,-1.583125e-01,-4.914609e-02,-1.540130e-01,4.864763e-02,7.536385e-01,6.892007e-01,1.381877e-01,-2.847758e-01,3.100658e-01,2.160891e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001620,2.577414e+00,-3.127404e-01,-3.533461e-02,-1.352181e+00,-5.752998e-01,1.219805e+00,-1.448443e-06,4.008685e-01,-9.113023e-01,-2.126233e-01,...,3.071012e-02,2.910971e-02,-3.089408e-01,-3.593150e-02,4.151500e-01,-8.937686e-01,-3.735820e-01,-1.125841e-02,-1.506192e-01,-2.605706e-01
1001621,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001622,3.871444e+00,-5.243609e-01,-3.063365e-01,-8.547921e-01,6.585537e-02,6.907458e-01,3.090792e-06,-1.697180e-01,1.508999e-01,-1.919850e-01,...,2.560945e-01,8.573911e-01,5.515617e-01,-2.434220e-01,-1.148996e-01,-2.409679e-02,-2.715162e-01,-1.829899e-01,-1.927747e-01,-1.526564e-01
1001623,3.937021e+00,-7.661514e-01,9.161447e-01,1.813071e+00,5.299137e-01,-1.284581e+00,-2.102633e-06,3.616940e-02,-1.107806e+00,1.563059e-01,...,2.934617e-01,1.074811e+00,-7.590176e-02,4.743731e-01,-5.756457e-01,8.135198e-02,5.063859e-02,6.447976e-02,-4.634192e-01,3.027023e-01
1001624,3.483570e+00,-7.259917e-01,3.102201e-01,1.502693e+00,-1.399131e+00,2.668741e-01,-7.320937e-07,1.392974e+00,4.490134e-01,2.167531e-02,...,4.727692e-01,-1.323690e-01,-5.133389e-02,-3.649328e-01,-6.780107e-02,6.681284e-02,3.013003e-01,3.038210e-01,4.299963e-02,8.123005e-02
1001625,5.192115e-01,-1.325943e-01,5.814945e-01,-5.322892e-01,2.890544e-01,-3.626035e-02,-6.384995e-09,7.891724e-01,-1.962124e-01,9.367097e-02,...,1.158901e-01,3.086493e-02,-1.858897e-03,-1.749768e-02,-1.350763e-02,2.756306e-02,4.028770e-02,-8.015967e-02,-1.402903e-02,1.237311e-02
1001626,5.919106e-01,-1.350294e-01,5.479843e-01,-6.379438e-01,2.412153e-01,7.287207e-02,-7.731896e-07,9.155331e-01,-1.953474e-01,6.824865e-02,...,-1.640087e-01,5.337769e-02,7.151985e-03,3.201011e-02,1.224658e-01,-7.625076e-02,3.405936e-02,-2.801871e-02,-7.503196e-02,5.596910e-02
1001627,4.809326e-04,-1.796870e-04,6.562265e-04,-5.565553e-04,3.054554e-04,1.292880e-04,7.681958e-09,1.358844e-03,4.238464e-04,3.169211e-05,...,-6.294329e-04,-4.922157e-04,-6.191253e-05,2.089247e-04,2.494233e-04,8.706032e-04,-1.012369e-04,-3.483883e-04,1.793717e-03,-6.393186e-04
1001628,5.192115e-01,-1.325943e-01,5.814945e-01,-5.322892e-01,2.890544e-01,-3.626035e-02,-6.384995e-09,7.891724e-01,-1.962124e-01,9.367097e-02,...,1.158901e-01,3.086493e-02,-1.858897e-03,-1.749768e-02,-1.350763e-02,2.756306e-02,4.028770e-02,-8.015967e-02,-1.402903e-02,1.237311e-02
1001629,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001630,5.192115e-01,-1.325943e-01,5.814945e-01,-5.322892e-01,2.890544e-01,-3.626035e-02,-6.384995e-09,7.891724e-01,-1.962124e-01,9.367097e-02,...,1.158901e-01,3.086493e-02,-1.858897e-03,-1.749768e-02,-1.350763e-02,2.756306e-02,4.028770e-02,-8.015967e-02,-1.402903e-02,1.237311e-02
1001631,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001632,5.192115e-01,-1.325943e-01,5.814945e-01,-5.322892e-01,2.890544e-01,-3.626035e-02,-6.384995e-09,7.891724e-01,-1.962124e-01,9.367097e-02,...,1.158901e-01,3.086493e-02,-1.858897e-03,-1.749768e-02,-1.350763e-02,2.756306e-02,4.028770e-02,-8.015967e-02,-1.402903e-02,1.237311e-02
1001633,8.024761e-02,2.060402e-01,-8.086006e-02,-1.155430e-02,-2.666118e-03,-1.414178e-01,3.603596e-06,-1.309177e-02,-1.542003e-02,-5.778589e-02,...,-1.093704e-01,-1.002872e-01,-6.299585e-02,-1.236972e-01,-6.122758e-02,-5.238099e-02,-3.105320e-02,8.501273e-03,9.711870e-03,8.724871e-02
1001634,8.269297e-01,-1.912508e-01,5.297751e-01,-3.113548e-01,2.750088e-01,-8.407326e-02,-1.127941e-06,1.005918e+00,-2.657035e-01,-3.005584e-01,...,-8.165854e-02,-5.764346e-02,-3.681253e-02,2.215638e-02,1.248334e-02,-1.120799e-02,1.133103e-02,-2.889869e-02,-9.239198e-02,7.212961e-04
1001635,2.238570e+00,-3.974255e-01,2.547110e-01,-1.064281e+00,-2.079444e-01,8.235395e-01,2.545342e-06,7.261894e-01,-7.293550e-02,3.909698e-01,...,-2.466365e-01,4.434117e-01,5.083725e-01,1.283876e-01,-1.248517e-01,3.540579e-01,3.839205e-01,-2.825861e-01,-9.086705e-03,1.063288e-02
1001636,2.621518e-01,-6.684938e-02,2.913224e-01,-2.660126e-01,1.439139e-01,-1.794564e-02,-3.113942e-08,3.902638e-01,-9.622977e-02,4.578905e-02,...,5.049041e-02,1.414789e-02,-8.097521e-04,-7.754285e-03,-5.366790e-03,1.114619e-02,1.711961e-02,-3.514429e-02,-4.017256e-03,5.162936e-03
1001637,6.110955e-01,-1.441333e-01,5.208751e-01,-6.582103e-01,3.043463e-01,5.771260e-02,-1.965662e-07,9.682615e-01,-1.127394e-01,1.743905e-01,...,-1.339324e-01,1.536859e-02,-2.205365e-02,5.377298e-02,4.499064e-02,-5.432655e-02,6.340580e-02,-1.103315e-02,-7.524077e-02,6.742545e-02
1001638,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001639,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001640,6.503626e+00,5.511095e+00,-2.695367e+00,-1.014446e+00,1.671125e+00,-2.075054e+00,8.202279e-06,-3.382932e-02,-4.322281e-02,-1.536452e-01,...,8.180366e-01,-1.500669e+00,2.436272e-01,1.697486e+00,1.418084e+00,-5.390905e-01,6.103612e-01,2.116354e-01,1.720258e-01,5.154520e-01
1001641,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001642,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001643,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001644,3.191919e+00,-5.357092e-01,-9.187050e-04,-1.063048e-01,-1.312223e+00,9.997978e-01,6.534475e-06,1.448710e+00,-1.155417e+00,-9.627593e-01,...,-5.132411e-02,-2.860750e-01,-1.961878e-01,-3.116181e-01,3.712132e-01,-1.954389e-02,3.548646e-01,9.426774e-02,-1.526728e-01,-2.431446e-01
1001645,-2.949669e-14,5.470857e-14,-3.819971e-13,8.345716e-13,8.425828e-12,2.295710e-11,1.000000e+00,-1.873428e-10,-5.629133e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001646,3.167168e+00,-5.566143e-01,-4.449861e-01,-8.853312e-02,1.488946e+00,5.760205e-01,-6.342663e-07,-8.717930e-01,6.493639e-01,-1.954248e-01,...,5.243403e-01,6.173132e-01,-4.507003e-02,9.220835e-02,-1.876959e-01,1.942987e-01,-8.827242e-01,1.438728e-01,1.373614e+00,4.462952e-01
1001647,-2.949669e-14,5.470857e-14,-3.819957e-13,8.345732e-13,8.425851e-12,2.295704e-11,1.000000e+00,-1.873428e-10,-5.629136e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09
1001648,8.757108e-01,-2.163489e-01,7.398860e-01,-5.425995e-01,4.533493e-01,-1.978783e-01,-8.824058e-07,6.066084e-01,-1.050228e-01,-8.251209e-02,...,5.616046e-02,6.398960e-02,-9.169395e-04,3.149530e-02,1.958619e-02,-8.076299e-04,7.687058e-02,1.010214e-01,1.069188e-02,3.771170e-02
1001649,-2.949669e-14,5.470857e-14,-3.819957e-13,8.345732e-13,8.425851e-12,2.295704e-11,1.000000e+00,-1.873428e-10,-5.629136e-11,2.110282e-10,...,-1.087693e-08,8.452731e-09,-2.050809e-09,1.127930e-09,1.451126e-09,8.734307e-10,6.501560e-09,-8.617481e-09,-1.995636e-09,2.818605e-09

In [51]:
train.head()

,instance_id,time,city,province,user_tags,carrier,devtype,make,model,nnt,...,creative_width,creative_height,creative_is_jump,creative_is_download,creative_is_js,creative_is_voicead,creative_has_deeplink,app_paid,advert_name,click
0,86294719979897807,2190219034,137103102105100,137103102100100,NaN,1,2,HUAWEI,HUAWEI-CAZ-AL10,1,...,1280,720,True,False,False,False,False,False,B4734117F35EE97F,0
1,2699289844928136052,2190221070,137105101100100,137105101100100,"2100191,2100078,3001825,,3001781,3001791,30017...",3,2,Xiaomi,Redmi Note 4,1,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
2,3117527168445845752,2190219793,137103104111100,137103104100100,NaN,3,2,OPPO,OPPO+R11s,1,...,960,640,True,False,False,False,False,False,E257895F74792E81,0
3,3398484891050993371,2190221704,137103102113100,137103102100100,"2100098,gd_2100000,3001791,3001795,3002193,300...",0,2,NaN,OPPO A57,1,...,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
4,2035477570591176488,2190220024,137103102109100,137103102100100,NaN,1,2,Apple,iPhone 7,3,...,960,640,True,False,False,False,False,False,B4734117F35EE97F,0

In [52]:
temp = train['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']

KeyError: ('advert_industry_inner', 'advert_name', 'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf')

In [53]:
temp = train[['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']]

In [54]:
temp.head()

,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf
0,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
1,102400_102401,B4734117F35EE97F,1000023,2310417,8,8390208550469153745
2,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
3,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
4,102400_102401,B4734117F35EE97F,1000023,2305409,8,8390208550469153745

In [ ]:
temp.append(train['creative_height'])
for col in temp.columns.values:
    print(col,'combining')
    x=temp[col]
    x_counter = Counter(x)
    filter_num_list = list()
    for item, cnt in x_counter.items():
        if cnt > threshold:
            continue
        filter_num_list.append(item)
        # print(item)
    for item in filter_num_list:
        temp[col] = x.apply(lambda _item: -1 if _item == item else _item)

In [1]:
import pandas as pd
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/round1_iflyad_train.txt',sep='\t')

In [ ]:
temp = train[['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']]
temp.append(train['creative_height'])
for col in temp.columns.values:
    print(col,'combining')
    x=temp[col]
    x_counter = Counter(x)
    filter_num_list = list()
    for item, cnt in x_counter.items():
        if cnt > threshold:
            continue
        filter_num_list.append(item)
        # print(item)
    for item in filter_num_list:
        temp[col] = x.apply(lambda _item: -1 if _item == item else _item)

In [1]:
import pandas as pd
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/round1_iflyad_train.txt',sep='\t')

In [2]:
temp = train[['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']]

In [3]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

In [5]:
selector = VarianceThreshold(threshold=0.05).fit(train)

ValueError: could not convert string to float: 'E257895F74792E81'

In [ ]:
selector

In [6]:
import pandas as pd
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/combining_data.txt',sep=',')

FileNotFoundError: File b'/users/lisa/Downloads/kedaxunfei/data/combining_data.txt' does not exist

In [7]:
import pandas as pd
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/combining_data.csv',sep=',')

In [8]:
train.head()

,adid,advert_id,advert_industry_inner,advert_name,app_cate_id,app_id,app_paid,campaign_id,carrier,city,...,osv,province,time,user_tags,day,hour,advert_industry_inner_1,ad_prefix,area,label
0,1560128,230000063,102400_102401,B4734117F35EE97F,107.0,2089229.0,False,1000023,1,137103102105100,...,7.0.0,137103102100100,2190219034,-1,29,2,102400,156,921600,0
1,1488859,230000063,102400_102401,B4734117F35EE97F,108.0,2070079.0,False,1000023,3,137105101100100,...,6.0,137105101100100,2190221070,"2100191,2100078,3001825,,3001781,3001791,30017...",29,2,102400,148,614400,0
2,1537089,230000065,101700_101704,E257895F74792E81,100.0,2089397.0,False,1000021,3,137103104111100,...,7.1.1,137103104100100,2190219793,-1,29,2,101700,153,614400,0
3,1577884,230001710,101900_101902,0A421D7B11EABFC5,100.0,2071234.0,False,1003544,0,137103102113100,...,6.0.1,137103102100100,2190221704,"2100098,gd_2100000,3001791,3001795,3002193,300...",29,2,101900,157,921600,0
4,1432367,230000063,102400_102401,B4734117F35EE97F,103.0,1030051.0,False,1000023,1,137103102109100,...,11.1.1,137103102100100,2190220024,-1,29,2,102400,143,614400,0

In [9]:
train.columns.values

array(['adid', 'advert_id', 'advert_industry_inner', 'advert_name',
       'app_cate_id', 'app_id', 'app_paid', 'campaign_id', 'carrier',
       'city', 'creative_has_deeplink', 'creative_height', 'creative_id',
       'creative_is_download', 'creative_is_js', 'creative_is_jump',
       'creative_is_voicead', 'creative_tp_dnf', 'creative_type',
       'creative_width', 'devtype', 'f_channel', 'inner_slot_id',
       'instance_id', 'make', 'model', 'nnt', 'orderid', 'os', 'os_name',
       'osv', 'province', 'time', 'user_tags', 'day', 'hour',
       'advert_industry_inner_1', 'ad_prefix', 'area', 'label'],
      dtype=object)

In [10]:
train.nunique()

adid                          1248
advert_id                       37
advert_industry_inner           23
advert_name                     33
app_cate_id                     22
app_id                         213
app_paid                         1
campaign_id                     57
carrier                          4
city                           333
creative_has_deeplink            2
creative_height                 11
creative_id                    575
creative_is_download             2
creative_is_js                   1
creative_is_jump                 2
creative_is_voicead              1
creative_tp_dnf                 29
creative_type                    5
creative_width                  17
devtype                          4
f_channel                       25
inner_slot_id                  438
instance_id                1041674
make                           558
model                         2682
nnt                              6
orderid                        852
os                               3
os_name                          3
osv                            119
province                        35
time                        474309
user_tags                   481796
day                              8
hour                            24
advert_industry_inner_1         14
ad_prefix                       19
area                            17
label                            3
dtype: int64

In [11]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

In [12]:
data=train[['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']]

In [13]:
data

,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf
0,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
1,102400_102401,B4734117F35EE97F,1000023,2310417,8,8390208550469153745
2,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
3,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
4,102400_102401,B4734117F35EE97F,1000023,2305409,8,8390208550469153745
5,4_100206,862FF2E9B0AD4C14,1002835,2340236,5,8390266143715132170
6,101000_101002,310405E93895BD58,1003456,2342232,5,8390272894417697957
7,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
8,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
9,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
10,101000_101002,310405E93895BD58,1003456,2341752,5,8390272894417697957
11,100300_100301,68C5520FFBC5FC19,1003598,2342432,5,8390404739335806554
12,101700_101704,50822F8310CAE01D,1001979,2332997,8,8390430283595430291
13,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
14,101700_101704,E257895F74792E81,1000021,2338390,8,8390430283595430291
15,100300_100301,68C5520FFBC5FC19,1003598,2342396,5,8390272894417697957
16,100300_100301,68C5520FFBC5FC19,1003598,2342428,8,8390430283595430291
17,102400_102401,B4734117F35EE97F,1000023,2307411,5,8390465404427801098
18,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
19,101000_101002,310405E93895BD58,1003456,2341736,5,8390272894417697957
20,101000_101002,310405E93895BD58,1003456,2342144,5,8390272894417697957
21,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
22,101000_101002,310405E93895BD58,1003456,2342144,5,8390272894417697957
23,16_100508,5C84C3D2EBBB9D7C,1003562,2341484,2,8390422898336367555
24,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
25,101000_101002,310405E93895BD58,1003456,2341696,5,8390272894417697957
26,101000_101002,310405E93895BD58,1003456,2342178,5,8390272894417697957
27,101700_101704,37E91828E6FB695A,1003211,2341440,5,8390450942386608675
28,101700_101704,E257895F74792E81,1000021,2338402,8,8390430283595430291
29,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
...,...,...,...,...,...,...
1041644,101700_101704,50822F8310CAE01D,1001979,2320155,8,8390430283595430291
1041645,101900_101902,0A421D7B11EABFC5,1003544,2342154,3,8390229093704413749
1041646,102400_102401,B4734117F35EE97F,1000023,2317979,2,8390422898336367555
1041647,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
1041648,102400_102401,B4734117F35EE97F,1000023,2317979,2,8390422898336367555
1041649,101700_101704,E257895F74792E81,1000021,2338402,8,8390430283595430291
1041650,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041651,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041652,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041653,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
1041654,101700_101704,50822F8310CAE01D,1001979,2342730,8,8390430283595430291
1041655,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041656,102400_102401,B4734117F35EE97F,1000023,2307527,5,8390272894417697957
1041657,101700_101799,CC4602621BE800EA,1003328,2341346,8,8390430283595430291
1041658,101700_101704,E257895F74792E81,1000021,2338402,8,8390430283595430291
1041659,102400_102401,B4734117F35EE97F,1000023,2342876,8,8390430283595430291
1041660,101700_101704,50822F8310CAE01D,1001979,2332997,8,8390430283595430291
1041661,101900_101902,0A421D7B11EABFC5,1003544,2342154,3,8390229093704413749
1041662,102400_102401,B4734117F35EE97F,1000023,2342334,5,8390450942386608675
1041663,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041664,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041665,101800_101812,42A4CB9035B7F50E,1003514,2341004,8,8390430283595430291
1041666,101900_101902,0A421D7B11EABFC5,1003544,2342154,3,8390229093704413749
1041667,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041668,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
1041669,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
1041670,16_100509,D54E631F07CA4751,1002549,2341348,8,8390430283595430291
1041671,101700_101704,50822F8310CAE01D,1001979,2342730,8,8390430283595430291
1041672,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
1041673,16_100509,D54E631F07CA4751,1002549,2341348,8,8390430283595430291

In [14]:
data = data[:100]

In [15]:
data

,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf
0,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
1,102400_102401,B4734117F35EE97F,1000023,2310417,8,8390208550469153745
2,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
3,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
4,102400_102401,B4734117F35EE97F,1000023,2305409,8,8390208550469153745
5,4_100206,862FF2E9B0AD4C14,1002835,2340236,5,8390266143715132170
6,101000_101002,310405E93895BD58,1003456,2342232,5,8390272894417697957
7,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
8,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
9,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
10,101000_101002,310405E93895BD58,1003456,2341752,5,8390272894417697957
11,100300_100301,68C5520FFBC5FC19,1003598,2342432,5,8390404739335806554
12,101700_101704,50822F8310CAE01D,1001979,2332997,8,8390430283595430291
13,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
14,101700_101704,E257895F74792E81,1000021,2338390,8,8390430283595430291
15,100300_100301,68C5520FFBC5FC19,1003598,2342396,5,8390272894417697957
16,100300_100301,68C5520FFBC5FC19,1003598,2342428,8,8390430283595430291
17,102400_102401,B4734117F35EE97F,1000023,2307411,5,8390465404427801098
18,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
19,101000_101002,310405E93895BD58,1003456,2341736,5,8390272894417697957
20,101000_101002,310405E93895BD58,1003456,2342144,5,8390272894417697957
21,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
22,101000_101002,310405E93895BD58,1003456,2342144,5,8390272894417697957
23,16_100508,5C84C3D2EBBB9D7C,1003562,2341484,2,8390422898336367555
24,101900_101902,0A421D7B11EABFC5,1003544,2342152,3,8390229093704413749
25,101000_101002,310405E93895BD58,1003456,2341696,5,8390272894417697957
26,101000_101002,310405E93895BD58,1003456,2342178,5,8390272894417697957
27,101700_101704,37E91828E6FB695A,1003211,2341440,5,8390450942386608675
28,101700_101704,E257895F74792E81,1000021,2338402,8,8390430283595430291
29,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
...,...,...,...,...,...,...
70,101700_101704,37E91828E6FB695A,1003211,2340088,8,8390430283595430291
71,101000_101002,310405E93895BD58,1003456,2341712,5,8390272894417697957
72,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
73,102400_102401,B4734117F35EE97F,1000023,2317991,8,8390430283595430291
74,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
75,101000_101002,310405E93895BD58,1003456,2341712,5,8390272894417697957
76,101000_101002,310405E93895BD58,1003456,2341838,5,8390272894417697957
77,101000_101002,310405E93895BD58,1003456,2341738,5,8390404739335806554
78,16_100509,D54E631F07CA4751,1002549,2341338,8,8390267734059046014
79,101700_101704,42A4CB9035B7F50E,1003516,2341134,5,8390272894417697957
80,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
81,101700_101704,50822F8310CAE01D,1001979,2336951,8,8390267734059046014
82,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
83,101000_101002,310405E93895BD58,1003456,2341764,5,8390272894417697957
84,101700_101704,50822F8310CAE01D,1001979,2336951,8,8390267734059046014
85,101700_101704,37E91828E6FB695A,1003211,2341440,5,8390450942386608675
86,101000_101002,310405E93895BD58,1003456,2341838,5,8390272894417697957
87,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
88,100600_100607,650A238639F48A0B,1003600,2342520,5,8390450942386608675
89,101700_101704,E257895F74792E81,1000021,2337017,8,8390430283595430291
90,101000_101002,310405E93895BD58,1003456,2342160,5,8390272894417697957
91,101700_101704,42A4CB9035B7F50E,1003348,2338162,5,8390315526253027596
92,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
93,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
94,102400_102401,B4734117F35EE97F,1000023,2316955,8,8390430283595430291
95,101700_101704,50822F8310CAE01D,1001979,2336951,8,8390267734059046014
96,101000_101002,310405E93895BD58,1003456,2341940,5,8390272894417697957
97,102400_102401,B4734117F35EE97F,1000023,2334795,8,8390430283595430291
98,102400_102401,B4734117F35EE97F,1000023,2338420,8,8390267734059046014
99,101700_101704,50822F8310CAE01D,1001979,2336951,8,8390267734059046014

In [16]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for feat in ['advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf']:
    enc.fit(data[feat])
    data[feat] = enc.transform(data[feat])

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [17]:
data

,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf
0,5,10,1,16,3,6
1,5,10,1,4,3,1
2,3,12,0,11,3,11
3,4,0,10,43,1,3
4,5,10,1,2,3,1
5,8,9,4,21,2,5
6,2,1,8,47,2,7
7,5,10,1,16,3,6
8,4,0,10,43,1,3
9,5,10,1,9,3,11
10,2,1,8,35,2,7
11,0,7,13,53,2,9
12,3,4,2,8,3,11
13,4,0,10,43,1,3
14,3,12,0,14,3,11
15,0,7,13,50,2,7
16,0,7,13,51,3,11
17,5,10,1,3,2,13
18,5,10,1,9,3,11
19,2,1,8,32,2,7
20,2,1,8,42,2,7
21,5,10,1,6,3,11
22,2,1,8,42,2,7
23,6,5,11,27,0,10
24,4,0,10,43,1,3
25,2,1,8,28,2,7
26,2,1,8,45,2,7
27,3,2,5,26,2,12
28,3,12,0,15,3,11
29,5,10,1,9,3,11
...,...,...,...,...,...,...
70,3,2,5,18,3,11
71,2,1,8,29,2,7
72,3,12,0,11,3,11
73,5,10,1,7,3,11
74,3,12,0,11,3,11
75,2,1,8,29,2,7
76,2,1,8,38,2,7
77,2,1,8,33,2,9
78,7,11,3,23,3,6
79,3,3,9,22,2,7
80,5,10,1,9,3,11
81,3,4,2,10,3,6
82,3,12,0,11,3,11
83,2,1,8,37,2,7
84,3,4,2,10,3,6
85,3,2,5,26,2,12
86,2,1,8,38,2,7
87,5,10,1,16,3,6
88,1,6,14,56,2,12
89,3,12,0,11,3,11
90,2,1,8,44,2,7
91,3,3,7,13,2,8
92,5,10,1,9,3,11
93,5,10,1,16,3,6
94,5,10,1,6,3,11
95,3,4,2,10,3,6
96,2,1,8,39,2,7
97,5,10,1,9,3,11
98,5,10,1,16,3,6
99,3,4,2,10,3,6

In [18]:
data=data.astype(int)

In [19]:
data

,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf
0,5,10,1,16,3,6
1,5,10,1,4,3,1
2,3,12,0,11,3,11
3,4,0,10,43,1,3
4,5,10,1,2,3,1
5,8,9,4,21,2,5
6,2,1,8,47,2,7
7,5,10,1,16,3,6
8,4,0,10,43,1,3
9,5,10,1,9,3,11
10,2,1,8,35,2,7
11,0,7,13,53,2,9
12,3,4,2,8,3,11
13,4,0,10,43,1,3
14,3,12,0,14,3,11
15,0,7,13,50,2,7
16,0,7,13,51,3,11
17,5,10,1,3,2,13
18,5,10,1,9,3,11
19,2,1,8,32,2,7
20,2,1,8,42,2,7
21,5,10,1,6,3,11
22,2,1,8,42,2,7
23,6,5,11,27,0,10
24,4,0,10,43,1,3
25,2,1,8,28,2,7
26,2,1,8,45,2,7
27,3,2,5,26,2,12
28,3,12,0,15,3,11
29,5,10,1,9,3,11
...,...,...,...,...,...,...
70,3,2,5,18,3,11
71,2,1,8,29,2,7
72,3,12,0,11,3,11
73,5,10,1,7,3,11
74,3,12,0,11,3,11
75,2,1,8,29,2,7
76,2,1,8,38,2,7
77,2,1,8,33,2,9
78,7,11,3,23,3,6
79,3,3,9,22,2,7
80,5,10,1,9,3,11
81,3,4,2,10,3,6
82,3,12,0,11,3,11
83,2,1,8,37,2,7
84,3,4,2,10,3,6
85,3,2,5,26,2,12
86,2,1,8,38,2,7
87,5,10,1,16,3,6
88,1,6,14,56,2,12
89,3,12,0,11,3,11
90,2,1,8,44,2,7
91,3,3,7,13,2,8
92,5,10,1,9,3,11
93,5,10,1,16,3,6
94,5,10,1,6,3,11
95,3,4,2,10,3,6
96,2,1,8,39,2,7
97,5,10,1,9,3,11
98,5,10,1,16,3,6
99,3,4,2,10,3,6

In [20]:
d=data
selector = VarianceThreshold(threshold=0.05).fit(data)
selector_index = selector.get_support(indices=True)
selector_columns = data.columns[selector_index]

In [21]:
selector

VarianceThreshold(threshold=0.05)

In [22]:
selector_index

array([0, 1, 2, 3, 4, 5])

In [23]:
data=d
selector = VarianceThreshold(threshold=0.2).fit(data)
selector_index = selector.get_support(indices=True)
print(selector_index)
selector_columns = data.columns[selector_index]

[0 1 2 3 4 5]

In [24]:
data=d
selector = VarianceThreshold(threshold=0.5).fit(data)
selector_index = selector.get_support(indices=True)
print(selector_index)
selector_columns = data.columns[selector_index]

[0 1 2 3 4 5]

In [25]:
data.append(train['creatice_is_js'])

KeyError: 'creatice_is_js'

In [ ]:
selector_columns

In [1]:
import pandas as pd
train = pd.read_csv('/users/lisa/Downloads/kedaxunfei/data/combining_data.csv',sep=',')

In [2]:
data=train

In [3]:
cate_features=['adid', 'advert_id', 'orderid', 'advert_industry_inner_1', 'advert_industry_inner', 'advert_name',
                   'campaign_id', 'creative_id', 'creative_type', 'creative_tp_dnf', 'creative_has_deeplink',
                   'creative_is_jump', 'creative_is_download','ad_prefix']
data=train[cate_features]
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for feat in cate_features:
    enc.fit(data[feat])
    data[feat] = enc.transform(data[feat])

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [4]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

selector = VarianceThreshold(threshold=0.05).fit(data)
selector_index = selector.get_support(indices=True)
selector_columns = data.columns[selector_index]

In [5]:
data.shape
selector_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13])

In [6]:
data.shape

(1041674, 14)

In [7]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

selector = VarianceThreshold(threshold=0.2).fit(data)
selector_index = selector.get_support(indices=True)
selector_columns = data.columns[selector_index]

In [8]:
selector_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13])

In [9]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

selector = VarianceThreshold(threshold=2).fit(data)
selector_index = selector.get_support(indices=True)
selector_columns = data.columns[selector_index]
selector_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 13])

In [10]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier

selector = VarianceThreshold(threshold=50).fit(data)
selector_index = selector.get_support(indices=True)
selector_columns = data.columns[selector_index]
selector_index

array([0, 1, 2, 5, 6, 7])

In [11]:
selector_columns

Index(['adid', 'advert_id', 'orderid', 'advert_name', 'campaign_id',
       'creative_id'],
      dtype='object')

In [12]:
data[selecor_columns]

NameError: name 'selecor_columns' is not defined

In [13]:
data[selector_columns]

         adid  advert_id  orderid  advert_name  campaign_id  creative_id
0         389          1      268           24            2          119
1          45          1       62           24            2           18
2         128          2      194           30            1           99
3         668         31      303            1           35          400
4           7          1       11           24            2            5
5         365         11      104           20           15          168
6         951         30      581            6           29          424
7         389          1      268           24            2          119
8         668         31      303            1           35          400
9         674          1      584           24            2           82
10        762         30      406            6           29          287
11        963          6      648           14           45          470
12        167         14      229           11           12           75
13        668         31      303            1           35          400
14        409          2       52           30            1          114
15        935          6      639           14           45          457
16        960          6      646           14           45          468
17        426          1      298           24            2           12
18        162          1      227           24            2           82
19        755         30      399            6           29          281
20        868         30      544            6           29          398
21         15          1       27           24            2           31
22        868         30      544            6           29          398
23        478         29      317           12           37          234
24        668         31      303            1           35          400
25        743         30      379            6           29          262
26        929         30      559            6           29          408
27        469         19      332            8           20          228
28        142          2      203           30            1          118
29        467          1       61           24            2           82
...       ...        ...      ...          ...          ...          ...
1041644  1237         14      845           11           12           43
1041645   670         31      449            1           35          401
1041646    29          1        1           24            2           38
1041647    91          1       25           24            2           31
1041648    29          1        1           24            2           38
1041649   142          2      203           30            1          118
1041650   186          1      199           24            2           82
1041651  1191          1      169           24            2           82
1041652  1208          1      268           24            2           82
1041653   187          2      240           30            1           99
1041654  1214         14      779           11           12          553
1041655  1191          1      169           24            2           82
1041656    57          1       73           24            2           13
1041657   688         22      594           26           22          217
1041658   142          2      203           30            1          118
1041659  1182          1      584           24            2          564
1041660  1117         14      771           11           12           75
1041661   670         31      449            1           35          401
1041662  1202          1      826           24            2          436
1041663  1191          1      169           24            2           82
1041664  1208          1      268           24            2           82
1041665   483         25      291           10           30          196
1041666   670         31      449            1           35          401
1041667   410          1      292           24            2           82
1041668    91          1       25           24            2           31
1041669  1191          1      169           24            2           82
1041670  1211         13      315           29           13          218
1041671  1247         14      851           11           12          553
1041672   100          1      145           24            2           31
1041673   463         13      269           29           13          218

[1041674 rows x 6 columns]

In [14]:
drop_columns = [column for column in features if column not in selector_columns]
data = data.drop(columns=drop_columns)
data

NameError: name 'features' is not defined

In [15]:
drop_columns = [column for column in cate_features if column not in selector_columns]
data = data.drop(columns=drop_columns)
data

         adid  advert_id  orderid  advert_name  campaign_id  creative_id
0         389          1      268           24            2          119
1          45          1       62           24            2           18
2         128          2      194           30            1           99
3         668         31      303            1           35          400
4           7          1       11           24            2            5
5         365         11      104           20           15          168
6         951         30      581            6           29          424
7         389          1      268           24            2          119
8         668         31      303            1           35          400
9         674          1      584           24            2           82
10        762         30      406            6           29          287
11        963          6      648           14           45          470
12        167         14      229           11           12           75
13        668         31      303            1           35          400
14        409          2       52           30            1          114
15        935          6      639           14           45          457
16        960          6      646           14           45          468
17        426          1      298           24            2           12
18        162          1      227           24            2           82
19        755         30      399            6           29          281
20        868         30      544            6           29          398
21         15          1       27           24            2           31
22        868         30      544            6           29          398
23        478         29      317           12           37          234
24        668         31      303            1           35          400
25        743         30      379            6           29          262
26        929         30      559            6           29          408
27        469         19      332            8           20          228
28        142          2      203           30            1          118
29        467          1       61           24            2           82
...       ...        ...      ...          ...          ...          ...
1041644  1237         14      845           11           12           43
1041645   670         31      449            1           35          401
1041646    29          1        1           24            2           38
1041647    91          1       25           24            2           31
1041648    29          1        1           24            2           38
1041649   142          2      203           30            1          118
1041650   186          1      199           24            2           82
1041651  1191          1      169           24            2           82
1041652  1208          1      268           24            2           82
1041653   187          2      240           30            1           99
1041654  1214         14      779           11           12          553
1041655  1191          1      169           24            2           82
1041656    57          1       73           24            2           13
1041657   688         22      594           26           22          217
1041658   142          2      203           30            1          118
1041659  1182          1      584           24            2          564
1041660  1117         14      771           11           12           75
1041661   670         31      449            1           35          401
1041662  1202          1      826           24            2          436
1041663  1191          1      169           24            2           82
1041664  1208          1      268           24            2           82
1041665   483         25      291           10           30          196
1041666   670         31      449            1           35          401
1041667   410          1      292           24            2           82
1041668    91          1       25           24            2           31
1041669  1191          1      169           24            2           82
1041670  1211         13      315           29           13          218
1041671  1247         14      851           11           12          553
1041672   100          1      145           24            2           31
1041673   463         13      269           29           13          218

[1041674 rows x 6 columns]

In [16]:
data.iloc[selector_index]

   adid  advert_id  orderid  advert_name  campaign_id  creative_id
0   389          1      268           24            2          119
1    45          1       62           24            2           18
2   128          2      194           30            1           99
5   365         11      104           20           15          168
6   951         30      581            6           29          424
7   389          1      268           24            2          119

In [17]:
data=train[cate_features]
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for feat in cate_features:
    enc.fit(data[feat])
    data[feat] = enc.transform(data[feat])
d=data

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [18]:
data

,adid,advert_id,orderid,advert_industry_inner_1,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf,creative_has_deeplink,creative_is_jump,creative_is_download,ad_prefix
0,389,1,268,13,17,24,2,119,3,11,0,1,0,16
1,45,1,62,13,17,24,2,18,3,2,0,1,0,8
2,128,2,194,10,11,30,1,99,3,22,0,1,0,13
3,668,31,303,12,16,1,35,400,1,6,0,1,0,17
4,7,1,11,13,17,24,2,5,3,2,0,1,0,3
5,365,11,104,1,21,20,15,168,2,10,0,1,0,15
6,951,30,581,6,6,6,29,424,2,13,0,1,0,18
7,389,1,268,13,17,24,2,119,3,11,0,1,0,16
8,668,31,303,12,16,1,35,400,1,6,0,1,0,17
9,674,1,584,13,17,24,2,82,3,22,0,1,0,17
10,762,30,406,6,6,6,29,287,2,13,0,1,0,17
11,963,6,648,4,1,14,45,470,2,19,0,1,0,18
12,167,14,229,10,11,11,12,75,3,22,0,1,0,14
13,668,31,303,12,16,1,35,400,1,6,0,1,0,17
14,409,2,52,10,11,30,1,114,3,22,0,1,0,17
15,935,6,639,4,1,14,45,457,2,13,0,1,0,18
16,960,6,646,4,1,14,45,468,3,22,0,1,0,18
17,426,1,298,13,17,24,2,12,2,25,0,1,0,17
18,162,1,227,13,17,24,2,82,3,22,0,1,0,14
19,755,30,399,6,6,6,29,281,2,13,0,1,0,17
20,868,30,544,6,6,6,29,398,2,13,0,1,0,18
21,15,1,27,13,17,24,2,31,3,22,0,1,0,5
22,868,30,544,6,6,6,29,398,2,13,0,1,0,18
23,478,29,317,3,18,12,37,234,0,21,0,1,0,17
24,668,31,303,12,16,1,35,400,1,6,0,1,0,17
25,743,30,379,6,6,6,29,262,2,13,0,1,0,17
26,929,30,559,6,6,6,29,408,2,13,0,1,0,18
27,469,19,332,10,11,8,20,228,2,24,0,1,0,17
28,142,2,203,10,11,30,1,118,3,22,0,1,0,14
29,467,1,61,13,17,24,2,82,3,22,0,1,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1041644,1237,14,845,10,11,11,12,43,3,22,0,1,0,18
1041645,670,31,449,12,16,1,35,401,1,6,0,1,0,17
1041646,29,1,1,13,17,24,2,38,0,21,0,1,0,5
1041647,91,1,25,13,17,24,2,31,3,22,0,1,0,11
1041648,29,1,1,13,17,24,2,38,0,21,0,1,0,5
1041649,142,2,203,10,11,30,1,118,3,22,0,1,0,14
1041650,186,1,199,13,17,24,2,82,3,22,0,1,0,14
1041651,1191,1,169,13,17,24,2,82,3,22,0,1,0,18
1041652,1208,1,268,13,17,24,2,82,3,22,0,1,0,18
1041653,187,2,240,10,11,30,1,99,3,22,0,1,0,14
1041654,1214,14,779,10,11,11,12,553,3,22,0,1,0,18
1041655,1191,1,169,13,17,24,2,82,3,22,0,1,0,18
1041656,57,1,73,13,17,24,2,13,2,13,0,1,0,9
1041657,688,22,594,10,13,26,22,217,3,22,0,1,0,17
1041658,142,2,203,10,11,30,1,118,3,22,0,1,0,14
1041659,1182,1,584,13,17,24,2,564,3,22,0,1,0,18
1041660,1117,14,771,10,11,11,12,75,3,22,0,1,0,18
1041661,670,31,449,12,16,1,35,401,1,6,0,1,0,17
1041662,1202,1,826,13,17,24,2,436,2,24,0,1,0,18
1041663,1191,1,169,13,17,24,2,82,3,22,0,1,0,18
1041664,1208,1,268,13,17,24,2,82,3,22,0,1,0,18
1041665,483,25,291,11,14,10,30,196,3,22,0,1,0,17
1041666,670,31,449,12,16,1,35,401,1,6,0,1,0,17
1041667,410,1,292,13,17,24,2,82,3,22,0,1,0,17
1041668,91,1,25,13,17,24,2,31,3,22,0,1,0,11
1041669,1191,1,169,13,17,24,2,82,3,22,0,1,0,18
1041670,1211,13,315,3,19,29,13,218,3,22,0,1,0,18
1041671,1247,14,851,10,11,11,12,553,3,22,0,1,0,18
1041672,100,1,145,13,17,24,2,31,3,22,0,1,0,11
1041673,463,13,269,3,19,29,13,218,3,22,0,1,0,17

In [19]:
data=data[:100]

In [20]:
selector_columns

Index(['adid', 'advert_id', 'orderid', 'advert_name', 'campaign_id',
       'creative_id'],
      dtype='object')

In [21]:
selector_index

array([0, 1, 2, 5, 6, 7])

In [22]:
data=d

In [23]:
data[selecor_columns]

NameError: name 'selecor_columns' is not defined

In [24]:
data[selector_columns][:100]

    adid  advert_id  orderid  advert_name  campaign_id  creative_id
0    389          1      268           24            2          119
1     45          1       62           24            2           18
2    128          2      194           30            1           99
3    668         31      303            1           35          400
4      7          1       11           24            2            5
5    365         11      104           20           15          168
6    951         30      581            6           29          424
7    389          1      268           24            2          119
8    668         31      303            1           35          400
9    674          1      584           24            2           82
10   762         30      406            6           29          287
11   963          6      648           14           45          470
12   167         14      229           11           12           75
13   668         31      303            1           35          400
14   409          2       52           30            1          114
15   935          6      639           14           45          457
16   960          6      646           14           45          468
17   426          1      298           24            2           12
18   162          1      227           24            2           82
19   755         30      399            6           29          281
20   868         30      544            6           29          398
21    15          1       27           24            2           31
22   868         30      544            6           29          398
23   478         29      317           12           37          234
24   668         31      303            1           35          400
25   743         30      379            6           29          262
26   929         30      559            6           29          408
27   469         19      332            8           20          228
28   142          2      203           30            1          118
29   467          1       61           24            2           82
..   ...        ...      ...          ...          ...          ...
70  1006         19      676            8           20          153
71   751         30      387            6           29          270
72   128          2      194           30            1           99
73   173          1      232           24            2           39
74   128          2      194           30            1           99
75   749         30      389            6           29          270
76   842         30      443            6           29          321
77   754         30      400            6           29          282
78   440         13      308           29           13          215
79   424          4      274           10           31          204
80   410          1      292           24            2           82
81   436         14      305           11           12           97
82   128          2      194           30            1           99
83   770         30      413            6           29          293
84   436         14      305           11           12           97
85   469         19      332            8           20          228
86   845         30      425            6           29          321
87   389          1      268           24            2          119
88  1013         35      593           13           46          490
89   128          2      194           30            1           99
90   921         30      551            6           29          403
91   727          4      623           10           24          106
92   674          1      584           24            2           82
93   143          1      169           24            2          119
94    92          1       43           24            2           31
95   436         14      305           11           12           97
96   883         30      478            6           29          350
97   188          1      241           24            2           82
98   199          1      175           24            2          119
99   436         14      305           11           12           97

[100 rows x 6 columns]

In [25]:
data.shape

(1041674, 14)

In [26]:
drop_columns = [column for column in cate_features if column not in selector_columns]
drop_columns

['advert_industry_inner_1',
 'advert_industry_inner',
 'creative_type',
 'creative_tp_dnf',
 'creative_has_deeplink',
 'creative_is_jump',
 'creative_is_download',
 'ad_prefix']

In [27]:
data.drop(columns=drop_columns)

         adid  advert_id  orderid  advert_name  campaign_id  creative_id
0         389          1      268           24            2          119
1          45          1       62           24            2           18
2         128          2      194           30            1           99
3         668         31      303            1           35          400
4           7          1       11           24            2            5
5         365         11      104           20           15          168
6         951         30      581            6           29          424
7         389          1      268           24            2          119
8         668         31      303            1           35          400
9         674          1      584           24            2           82
10        762         30      406            6           29          287
11        963          6      648           14           45          470
12        167         14      229           11           12           75
13        668         31      303            1           35          400
14        409          2       52           30            1          114
15        935          6      639           14           45          457
16        960          6      646           14           45          468
17        426          1      298           24            2           12
18        162          1      227           24            2           82
19        755         30      399            6           29          281
20        868         30      544            6           29          398
21         15          1       27           24            2           31
22        868         30      544            6           29          398
23        478         29      317           12           37          234
24        668         31      303            1           35          400
25        743         30      379            6           29          262
26        929         30      559            6           29          408
27        469         19      332            8           20          228
28        142          2      203           30            1          118
29        467          1       61           24            2           82
...       ...        ...      ...          ...          ...          ...
1041644  1237         14      845           11           12           43
1041645   670         31      449            1           35          401
1041646    29          1        1           24            2           38
1041647    91          1       25           24            2           31
1041648    29          1        1           24            2           38
1041649   142          2      203           30            1          118
1041650   186          1      199           24            2           82
1041651  1191          1      169           24            2           82
1041652  1208          1      268           24            2           82
1041653   187          2      240           30            1           99
1041654  1214         14      779           11           12          553
1041655  1191          1      169           24            2           82
1041656    57          1       73           24            2           13
1041657   688         22      594           26           22          217
1041658   142          2      203           30            1          118
1041659  1182          1      584           24            2          564
1041660  1117         14      771           11           12           75
1041661   670         31      449            1           35          401
1041662  1202          1      826           24            2          436
1041663  1191          1      169           24            2           82
1041664  1208          1      268           24            2           82
1041665   483         25      291           10           30          196
1041666   670         31      449            1           35          401
1041667   410          1      292           24            2           82
1041668    91          1       25           24            2           31
1041669  1191          1      169           24            2           82
1041670  1211         13      315           29           13          218
1041671  1247         14      851           11           12          553
1041672   100          1      145           24            2           31
1041673   463         13      269           29           13          218

[1041674 rows x 6 columns]

In [28]:
data.loc[selector_index]

,adid,advert_id,orderid,advert_industry_inner_1,advert_industry_inner,advert_name,campaign_id,creative_id,creative_type,creative_tp_dnf,creative_has_deeplink,creative_is_jump,creative_is_download,ad_prefix
0,389,1,268,13,17,24,2,119,3,11,0,1,0,16
1,45,1,62,13,17,24,2,18,3,2,0,1,0,8
2,128,2,194,10,11,30,1,99,3,22,0,1,0,13
5,365,11,104,1,21,20,15,168,2,10,0,1,0,15
6,951,30,581,6,6,6,29,424,2,13,0,1,0,18
7,389,1,268,13,17,24,2,119,3,11,0,1,0,16

In [29]:
selector_index

array([0, 1, 2, 5, 6, 7])

In [30]:
data[[selector_index]]

KeyError: '[(0, 1, 2, 5, 6, 7)] not in index'

In [31]:
selector.transform(data)

array([[ 389,    1,  268,   24,    2,  119],
       [  45,    1,   62,   24,    2,   18],
       [ 128,    2,  194,   30,    1,   99],
       ...,
       [1247,   14,  851,   11,   12,  553],
       [ 100,    1,  145,   24,    2,   31],
       [ 463,   13,  269,   29,   13,  218]])

In [ ]:
pd.DataFrame()